import { readFileSync } from 'node:fs';

/** A spec state as TLC serializes it: variable name → value. */
export type SpecView = Readonly<Record<string, unknown>>;

/**
 * A spec's reachable state graph (FM-R7): distinct states, the states `Init` produces, and edges
 * `[from, to, action]` as view indices plus the step's action label. Canonically sorted, committed
 * as `<Module>/graph.json`, and regenerated by the Java tier.
 */
export type SpecGraph = {
  readonly initial: readonly number[];
  readonly views: readonly SpecView[];
  readonly edges: ReadonlyArray<readonly [number, number, string]>;
};

/** One shortest behaviour per (source phase, action) class, as view indices into its graph. */
export type CoveringSuite = { readonly phase: string; readonly behaviours: ReadonlyArray<readonly number[]> };

/** JSON with object keys sorted, so equal values have equal text. */
export const canonicalJson = (value: unknown): string =>
  JSON.stringify(value, (_key, item: unknown) =>
    item !== null && typeof item === 'object' && !Array.isArray(item)
      ? Object.fromEntries(
          Object.entries(item as Record<string, unknown>).sort(([left], [right]) =>
            left < right ? -1 : left > right ? 1 : 0,
          ),
        )
      : item,
  );

/** Reads a dotted path such as `turn.phase` out of a view. */
export const viewField = (view: SpecView, dotted: string): unknown => {
  let value: unknown = view;
  for (const key of dotted.split('.')) {
    value = value !== null && typeof value === 'object' ? (value as Record<string, unknown>)[key] : undefined;
  }
  return value;
};

/**
 * Builds the canonical graph from TLC's edge export: one `[from, to]` pair per generated transition.
 * `action` names the variable that labels each step (`act` in `TurnProtocol`).
 */
export const buildSpecGraph = (pairs: ReadonlyArray<readonly [SpecView, SpecView]>, action: string): SpecGraph => {
  const texts = new Set<string>();
  for (const [from, to] of pairs) {
    texts.add(canonicalJson(from));
    texts.add(canonicalJson(to));
  }
  const sorted = [...texts].sort();
  const index = new Map(sorted.map((text, position) => [text, position]));
  const edgeTexts = new Set<string>();
  const edges: Array<readonly [number, number, string]> = [];
  const targets = new Set<number>();
  for (const [from, to] of pairs) {
    const edge = [
      index.get(canonicalJson(from)) ?? -1,
      index.get(canonicalJson(to)) ?? -1,
      canonicalJson(viewField(to, action)),
    ] as const;
    const key = JSON.stringify(edge);
    if (!edgeTexts.has(key)) {
      edgeTexts.add(key);
      edges.push(edge);
      targets.add(edge[1]);
    }
  }
  edges.sort(
    (left, right) => left[0] - right[0] || left[1] - right[1] || (left[2] < right[2] ? -1 : left[2] > right[2] ? 1 : 0),
  );
  const initial = sorted.map((_text, position) => position).filter((position) => !targets.has(position));
  return { initial, views: sorted.map((text) => JSON.parse(text) as SpecView), edges };
};

export const readSpecGraph = (file: string): SpecGraph => JSON.parse(readFileSync(file, 'utf8')) as SpecGraph;

export const serializeGraph = (graph: SpecGraph): string =>
  `{"initial":${JSON.stringify(graph.initial)},\n"views":[\n${graph.views.map((view) => canonicalJson(view)).join(',\n')}\n],\n"edges":[\n${graph.edges.map((edge) => JSON.stringify(edge)).join(',\n')}\n]}\n`;

export const serializeSuite = (suite: CoveringSuite): string =>
  `{"phase":${JSON.stringify(suite.phase)},\n"behaviours":[\n${suite.behaviours.map((behaviour) => JSON.stringify(behaviour)).join(',\n')}\n]}\n`;

const successorsOf = (graph: SpecGraph): Map<number, Array<readonly [number, string]>> => {
  const successors = new Map<number, Array<readonly [number, string]>>();
  for (const [from, to, action] of graph.edges) {
    successors.set(from, [...(successors.get(from) ?? []), [to, action]]);
  }
  return successors;
};

/**
 * Shortest behaviours that together take every (source phase, action) class of the graph (S6):
 * breadth-first from the initial states, keeping the first path that takes each class.
 */
export const coveringSuite = (graph: SpecGraph, phase: string): CoveringSuite => {
  const successors = successorsOf(graph);
  const pathTo = new Map<number, number[]>(graph.initial.map((state) => [state, [state]]));
  const queue = [...graph.initial];
  const suite = new Map<string, number[]>();
  // Breadth-first: `queue` grows while it is walked, which a for…of over an array does visit.
  for (const state of queue) {
    const path = pathTo.get(state) ?? [state];
    for (const [next, action] of successors.get(state) ?? []) {
      const candidate = [...path, next];
      const key = `${canonicalJson(viewField(graph.views[state] ?? {}, phase))}|${action}`;
      if (!suite.has(key)) {
        suite.set(key, candidate);
      }
      if (!pathTo.has(next)) {
        pathTo.set(next, candidate);
        queue.push(next);
      }
    }
  }
  return {
    phase,
    behaviours: [...suite].sort(([left], [right]) => (left < right ? -1 : 1)).map(([, behaviour]) => behaviour),
  };
};

/** The behaviours of a suite as spec states. */
export const suiteBehaviours = (graph: SpecGraph, suite: CoveringSuite): SpecView[][] =>
  suite.behaviours.map((behaviour) => behaviour.map((state) => graph.views[state] ?? {}));

/** One implementation path in the spec's vocabulary: the start, then each step's action label and view. */
export type WalkPath = {
  readonly initial: SpecView;
  readonly steps: ReadonlyArray<{ readonly action: string; readonly view: SpecView }>;
};

export type Rejection = {
  readonly path: number;
  readonly step: number;
  readonly action: string;
  readonly allowed: readonly SpecView[];
  readonly actual: SpecView;
};

/** True when every field the implementation's view names equals the spec state's (the refinement mapping). */
export const agrees = (spec: SpecView, actual: SpecView): boolean =>
  Object.entries(actual).every(([field, value]) => canonicalJson(spec[field]) === canonicalJson(value));

/**
 * Backward walk (S6 bridge c): every implementation path must be a behaviour of the spec graph.
 * Paths come from shortest-path enumeration over the machine (W2's `pathTable`).
 */
export const walkPaths = (graph: SpecGraph, paths: readonly WalkPath[]): Rejection[] => {
  const successors = successorsOf(graph);
  return paths.flatMap((path, index): Rejection[] => {
    let frontier = graph.initial.filter((state) => agrees(graph.views[state] ?? {}, path.initial));
    if (frontier.length === 0) {
      return [
        {
          path: index,
          step: 0,
          action: 'Init',
          allowed: graph.initial.map((state) => graph.views[state] ?? {}),
          actual: path.initial,
        },
      ];
    }
    for (const [step, { action, view }] of path.steps.entries()) {
      const labelled = frontier.flatMap((state) =>
        (successors.get(state) ?? []).filter(([, label]) => label === action).map(([next]) => next),
      );
      const matching = [...new Set(labelled)].filter((state) => agrees(graph.views[state] ?? {}, view));
      if (matching.length === 0) {
        return [
          {
            path: index,
            step: step + 1,
            action,
            allowed: labelled.map((state) => graph.views[state] ?? {}),
            actual: view,
          },
        ];
      }
      frontier = matching;
    }
    return [];
  });
};
