import { readFileSync } from 'node:fs';

/**
 * A spec state as TLC serializes it: variable name → value.
 *
 * @public
 */
export type SpecView = Readonly<Record<string, unknown>>;

/**
 * A spec's reachable state graph (FM-R7): distinct states, the states `Init` produces, and edges
 * `[from, to, action]` as view indices plus the step's action label. Canonically sorted, committed
 * as `<Module>/graph.json`, and regenerated by the Java tier.
 *
 * @public
 */
export type SpecGraph = {
  readonly initial: readonly number[];
  readonly views: readonly SpecView[];
  readonly edges: ReadonlyArray<readonly [number, number, string]>;
};

/**
 * One shortest behaviour per (source phase, action) class, as view indices into its graph.
 *
 * @public
 */
export type CoveringSuite = { readonly phase: string; readonly behaviours: ReadonlyArray<readonly number[]> };

/**
 * JSON with object keys sorted, so equal values have equal text.
 *
 * @public
 */
export const canonicalJson = (value: unknown): string =>
  JSON.stringify(value, (_key, item: unknown) =>
    item !== null && typeof item === 'object' && !Array.isArray(item)
      ? Object.fromEntries(
          Object.entries(item as Record<string, unknown>).sort(([left], [right]) =>
            left < right ? -1 : left > right ? 1 : 0,
          ),
        )
      : item,
  );

/**
 * Reads a dotted path such as `turn.phase` out of a view.
 *
 * @public
 */
export const viewField = (view: SpecView, dotted: string): unknown => {
  let value: unknown = view;
  for (const key of dotted.split('.')) {
    value = value !== null && typeof value === 'object' ? (value as Record<string, unknown>)[key] : undefined;
  }
  return value;
};

/**
 * Builds the canonical graph from TLC's edge export: one `[from, to]` pair per generated transition.
 * `action` names the variable that labels each step (`act` in `TurnProtocol`).
 *
 * @public
 */
export const buildSpecGraph = (pairs: ReadonlyArray<readonly [SpecView, SpecView]>, action: string): SpecGraph => {
  const texts = new Set<string>();
  for (const [from, to] of pairs) {
    texts.add(canonicalJson(from));
    texts.add(canonicalJson(to));
  }
  const sorted = [...texts].sort();
  const index = new Map(sorted.map((text, position) => [text, position]));
  const edgeTexts = new Set<string>();
  const edges: Array<readonly [number, number, string]> = [];
  const targets = new Set<number>();
  for (const [from, to] of pairs) {
    const edge = [
      index.get(canonicalJson(from)) ?? -1,
      index.get(canonicalJson(to)) ?? -1,
      canonicalJson(viewField(to, action)),
    ] as const;
    const key = JSON.stringify(edge);
    if (!edgeTexts.has(key)) {
      edgeTexts.add(key);
      edges.push(edge);
      targets.add(edge[1]);
    }
  }
  edges.sort(
    (left, right) => left[0] - right[0] || left[1] - right[1] || (left[2] < right[2] ? -1 : left[2] > right[2] ? 1 : 0),
  );
  const initial = sorted.map((_text, position) => position).filter((position) => !targets.has(position));
  return { initial, views: sorted.map((text) => JSON.parse(text) as SpecView), edges };
};

/**
 * Reads a committed `graph.json`.
 *
 * @public
 */
export const readSpecGraph = (file: string): SpecGraph => {
  const stored = JSON.parse(readFileSync(file, 'utf8')) as SpecGraph | CompactSpecGraph;
  if (!('fields' in stored)) {
    return stored;
  }
  const { initial, fields, values, views, actions, edges } = stored;
  return {
    initial,
    views: views.map((row) =>
      Object.fromEntries(
        fields.flatMap((field, column) => (row[column] === -1 ? [] : [[field, values[column]?.[row[column] ?? -1]]])),
      ),
    ),
    edges: edges.map((packed) => {
      const action = packed % actions.length;
      const target = Math.floor(packed / actions.length) % views.length;
      return [Math.floor(packed / actions.length / views.length), target, actions[action] ?? ''] as const;
    }),
  };
};

type CompactSpecGraph = {
  readonly initial: readonly number[];
  readonly fields: readonly string[];
  readonly values: ReadonlyArray<readonly unknown[]>;
  readonly views: ReadonlyArray<readonly number[]>;
  readonly actions: readonly string[];
  /** Each edge packs `(from * stateCount + to) * actionCount + actionIndex`. */
  readonly edges: readonly number[];
};

/**
 * The committed text of a spec graph: canonical JSON, one trailing newline.
 *
 * @public
 */
export const serializeGraph = (graph: SpecGraph): string => {
  const plain = `{"initial":${JSON.stringify(graph.initial)},\n"views":[\n${graph.views.map((view) => canonicalJson(view)).join(',\n')}\n],\n"edges":[\n${graph.edges.map((edge) => JSON.stringify(edge)).join(',\n')}\n]}\n`;
  // Plain JSON grows under the repository formatter; compact large graphs before that step.
  if (Buffer.byteLength(plain) <= 600_000) {
    return plain;
  }

  const fields = [...new Set(graph.views.flatMap((view) => Object.keys(view)))].sort();
  const values = fields.map((field) =>
    [...new Set(graph.views.flatMap((view) => (Object.hasOwn(view, field) ? [canonicalJson(view[field])] : [])))]
      .sort()
      .map((text) => JSON.parse(text) as unknown),
  );
  const indices = values.map((column) => new Map(column.map((value, index) => [canonicalJson(value), index])));
  const views = graph.views.map((view) =>
    fields.map((field, column) =>
      Object.hasOwn(view, field) ? (indices[column]?.get(canonicalJson(view[field])) ?? -1) : -1,
    ),
  );
  const actions = [...new Set(graph.edges.map((edge) => edge[2]))].sort();
  const actionIndices = new Map(actions.map((action, index) => [action, index]));
  const edges = graph.edges.map(
    ([from, to, action]) => (from * views.length + to) * actions.length + (actionIndices.get(action) ?? -1),
  );
  return `${JSON.stringify({ initial: graph.initial, fields, values, views, actions, edges })}\n`;
};

/**
 * The committed text of a covering suite: canonical JSON, one trailing newline.
 *
 * @public
 */
export const serializeSuite = (suite: CoveringSuite): string =>
  `{"phase":${JSON.stringify(suite.phase)},\n"behaviours":[\n${suite.behaviours.map((behaviour) => JSON.stringify(behaviour)).join(',\n')}\n]}\n`;

const successorsOf = (graph: SpecGraph): Map<number, Array<readonly [number, string]>> => {
  const successors = new Map<number, Array<readonly [number, string]>>();
  for (const [from, to, action] of graph.edges) {
    successors.set(from, [...(successors.get(from) ?? []), [to, action]]);
  }
  return successors;
};

/**
 * Shortest behaviours that together take every (source phase, action) class of the graph (S6):
 * breadth-first from the initial states, keeping the first path that takes each class.
 *
 * @public
 */
export const coveringSuite = (graph: SpecGraph, phase: string): CoveringSuite => {
  const successors = successorsOf(graph);
  const pathTo = new Map<number, number[]>(graph.initial.map((state) => [state, [state]]));
  const queue = [...graph.initial];
  const suite = new Map<string, number[]>();
  // Breadth-first: `queue` grows while it is walked, which a for…of over an array does visit.
  for (const state of queue) {
    const path = pathTo.get(state) ?? [state];
    for (const [next, action] of successors.get(state) ?? []) {
      const candidate = [...path, next];
      const key = `${canonicalJson(viewField(graph.views[state] ?? {}, phase))}|${action}`;
      if (!suite.has(key)) {
        suite.set(key, candidate);
      }
      if (!pathTo.has(next)) {
        pathTo.set(next, candidate);
        queue.push(next);
      }
    }
  }
  return {
    phase,
    behaviours: [...suite].sort(([left], [right]) => (left < right ? -1 : 1)).map(([, behaviour]) => behaviour),
  };
};

/**
 * The behaviours of a suite as spec states.
 *
 * @public
 */
export const suiteBehaviours = (graph: SpecGraph, suite: CoveringSuite): SpecView[][] =>
  suite.behaviours.map((behaviour) => behaviour.map((state) => graph.views[state] ?? {}));

/**
 * One implementation path in the spec's vocabulary: the start, then each step's action label and view.
 *
 * @public
 */
export type WalkPath = {
  readonly initial: SpecView;
  readonly steps: ReadonlyArray<{ readonly action: string; readonly view: SpecView }>;
};

/**
 * A walked implementation step the spec graph does not allow: the views it allows and the one it got.
 *
 * @public
 */
export type Rejection = {
  readonly path: number;
  readonly step: number;
  readonly action: string;
  readonly allowed: readonly SpecView[];
  readonly actual: SpecView;
};

/**
 * True when every field the implementation's view names equals the spec state's (the refinement mapping).
 *
 * @public
 */
export const agrees = (spec: SpecView, actual: SpecView): boolean =>
  Object.entries(actual).every(([field, value]) => canonicalJson(spec[field]) === canonicalJson(value));

/**
 * Backward walk (S6 bridge c): every implementation path must be a behaviour of the spec graph.
 * Paths come from shortest-path enumeration over the machine (W2's `pathTable`).
 *
 * @public
 */
export const walkPaths = (graph: SpecGraph, paths: readonly WalkPath[]): Rejection[] => {
  const successors = successorsOf(graph);
  return paths.flatMap((path, index): Rejection[] => {
    let frontier = graph.initial.filter((state) => agrees(graph.views[state] ?? {}, path.initial));
    if (frontier.length === 0) {
      return [
        {
          path: index,
          step: 0,
          action: 'Init',
          allowed: graph.initial.map((state) => graph.views[state] ?? {}),
          actual: path.initial,
        },
      ];
    }
    for (const [step, { action, view }] of path.steps.entries()) {
      const labelled = frontier.flatMap((state) =>
        (successors.get(state) ?? []).filter(([, label]) => label === action).map(([next]) => next),
      );
      const matching = [...new Set(labelled)].filter((state) => agrees(graph.views[state] ?? {}, view));
      if (matching.length === 0) {
        return [
          {
            path: index,
            step: step + 1,
            action,
            allowed: labelled.map((state) => graph.views[state] ?? {}),
            actual: view,
          },
        ];
      }
      frontier = matching;
    }
    return [];
  });
};
