; Moray UDO file generated by Rhinoceros

; Setting version to 3.5 for FACE preview support
Version 3.5
IncludeFile 'cube.inc'

[Default_node:Vertices]
8
1 1 2
-1 1 2
-1 -1 2
1 -1 2
1 1 0
1 -1 0
-1 1 0
-1 -1 0

[Default_node:Edges]
18
0 1
0 2
0 3
0 4
1 2
1 4
1 6
1 7
2 3
2 5
2 7
3 4
3 5
4 5
4 6
5 6
5 7
6 7

[Default_node:Faces]
12
2 0 1
3 0 2
3 4 0
5 4 3
5 6 4
7 6 5
7 1 6
2 1 7
4 1 0
6 1 4
3 2 5
5 2 7


