// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 24,
  "wire": 2,
  "pitch": 5,
  "turns": 6
};
export const parameterDomains = {
  "diameter": {
    "min": 20,
    "max": 28
  },
  "wire": {
    "min": 1.5,
    "max": 2.5
  },
  "pitch": {
    "min": 4,
    "max": 6
  },
  "turns": {
    "min": 4,
    "max": 8,
    "integer": true,
    "values": [
      4,
      5,
      6,
      7,
      8
    ]
  }
};
export const design = "compression-spring";
export const parameterCases = [
  {
    "name": "diameter 20",
    "parameters": {
      "diameter": 20
    },
    "expectations": {
      "bounds": {
        "x": 20,
        "y": 20,
        "z": 32
      },
      "solids": 1
    }
  },
  {
    "name": "diameter 28",
    "parameters": {
      "diameter": 28
    },
    "expectations": {
      "bounds": {
        "x": 28,
        "y": 28,
        "z": 32
      },
      "solids": 1
    }
  },
  {
    "name": "wire 1.5",
    "parameters": {
      "wire": 1.5
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 31.5
      },
      "solids": 1
    }
  },
  {
    "name": "wire 2.5",
    "parameters": {
      "wire": 2.5
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 32.5
      },
      "solids": 1
    }
  },
  {
    "name": "pitch 4",
    "parameters": {
      "pitch": 4
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 26
      },
      "solids": 1
    }
  },
  {
    "name": "pitch 6",
    "parameters": {
      "pitch": 6
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 38
      },
      "solids": 1
    }
  },
  {
    "name": "turns 4",
    "parameters": {
      "turns": 4
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 22
      },
      "solids": 1
    }
  },
  {
    "name": "turns 5",
    "parameters": {
      "turns": 5
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 27
      },
      "solids": 1
    }
  },
  {
    "name": "turns 6",
    "parameters": {
      "turns": 6
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 32
      },
      "solids": 1
    }
  },
  {
    "name": "turns 7",
    "parameters": {
      "turns": 7
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 37
      },
      "solids": 1
    }
  },
  {
    "name": "turns 8",
    "parameters": {
      "turns": 8
    },
    "expectations": {
      "bounds": {
        "x": 24,
        "y": 24,
        "z": 42
      },
      "solids": 1
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "diameter": 20,
      "wire": 1.5,
      "pitch": 4,
      "turns": 4
    },
    "expectations": {
      "bounds": {
        "x": 20,
        "y": 20,
        "z": 17.5
      },
      "solids": 1
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "diameter": 28,
      "wire": 2.5,
      "pitch": 6,
      "turns": 8
    },
    "expectations": {
      "bounds": {
        "x": 28,
        "y": 28,
        "z": 50.5
      },
      "solids": 1
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "diameter": 20,
      "wire": 2.5,
      "pitch": 4,
      "turns": 4
    },
    "expectations": {
      "bounds": {
        "x": 20,
        "y": 20,
        "z": 18.5
      },
      "solids": 1
    }
  }
];
