// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 6
};
export const parameterDomains = {
  "diameter": {
    "min": 3,
    "max": 10,
    "values": [
      3,
      4,
      5,
      6,
      8,
      10
    ]
  }
};
export const design = "hex-nut";
export const parameterCases = [
  {
    "name": "M3",
    "parameters": {
      "diameter": 3
    },
    "expectations": {
      "bounds": {
        "x": 6.3508529610858835,
        "y": 5.5,
        "z": 2.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 3,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M4",
    "parameters": {
      "diameter": 4
    },
    "expectations": {
      "bounds": {
        "x": 8.082903768654761,
        "y": 7,
        "z": 3.2
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 4,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M5",
    "parameters": {
      "diameter": 5
    },
    "expectations": {
      "bounds": {
        "x": 9.237604307034013,
        "y": 8,
        "z": 4.7
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M6",
    "parameters": {
      "diameter": 6
    },
    "expectations": {
      "bounds": {
        "x": 11.547005383792516,
        "y": 10,
        "z": 5.2
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M8",
    "parameters": {
      "diameter": 8
    },
    "expectations": {
      "bounds": {
        "x": 15.01110699893027,
        "y": 13,
        "z": 6.8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M10",
    "parameters": {
      "diameter": 10
    },
    "expectations": {
      "bounds": {
        "x": 18.475208614068027,
        "y": 16,
        "z": 8.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  }
];
