// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 30,
  "bore": 12,
  "length": 60
};
export const parameterDomains = {
  "diameter": {
    "min": 27,
    "max": 33
  },
  "bore": {
    "min": 10.8,
    "max": 13.200000000000001
  },
  "length": {
    "min": 54,
    "max": 66
  }
};
export const design = "pipe-nipple";
export const parameterCases = [
  {
    "name": "diameter 27",
    "parameters": {
      "diameter": 27
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 23.38268590217984,
        "z": 60
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 12,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "diameter 33",
    "parameters": {
      "diameter": 33
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 28.578838324886473,
        "z": 60
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 12,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore 10.8",
    "parameters": {
      "bore": 10.8
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 25.980762113533157,
        "z": 60
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 10.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore 13.200000000000001",
    "parameters": {
      "bore": 13.200000000000001
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 25.980762113533157,
        "z": 60
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 13.200000000000001,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "length 54",
    "parameters": {
      "length": 54
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 25.980762113533157,
        "z": 54
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 12,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "length 66",
    "parameters": {
      "length": 66
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 25.980762113533157,
        "z": 66
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 12,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "diameter": 27,
      "bore": 10.8,
      "length": 54
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 23.38268590217984,
        "z": 54
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 10.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "diameter": 33,
      "bore": 13.200000000000001,
      "length": 66
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 28.578838324886473,
        "z": 66
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 13.200000000000001,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "diameter": 27,
      "bore": 13.200000000000001,
      "length": 54
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 23.38268590217984,
        "z": 54
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 13.200000000000001,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  }
];
