// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Fan guard", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.1 });
});
it("width-minimum", async () => {
const parameters = {
  "width": 48
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 48,
  "y": 60,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -18,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -18,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 18,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 18,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 48,
  "y": 60,
  "z": 2
}, tolerance: 0.1 });
});
it("width-maximum", async () => {
const parameters = {
  "width": 72
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 72,
  "y": 60,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -30,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -30,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 30,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 30,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 72,
  "y": 60,
  "z": 2
}, tolerance: 0.1 });
});
it("depth-minimum", async () => {
const parameters = {
  "depth": 48
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 48,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": -18
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": 18
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": -18
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": 18
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 48,
  "z": 2
}, tolerance: 0.1 });
});
it("depth-maximum", async () => {
const parameters = {
  "depth": 72
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 72,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": -30
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": 30
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": -30
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": 30
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 72,
  "z": 2
}, tolerance: 0.1 });
});
it("thickness-minimum", async () => {
const parameters = {
  "thickness": 1.6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 1.6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 1.6
}, tolerance: 0.1 });
});
it("thickness-maximum", async () => {
const parameters = {
  "thickness": 2.4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2.4
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2.4
}, tolerance: 0.1 });
});
it("hole-minimum", async () => {
const parameters = {
  "hole": 3.2
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": -25.2,
    "y": -25.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": -25.2,
    "y": 25.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": 25.2,
    "y": -25.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": 25.2,
    "y": 25.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.1 });
});
it("hole-maximum", async () => {
const parameters = {
  "hole": 4.8
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": -22.8,
    "y": -22.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": -22.8,
    "y": 22.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": 22.8,
    "y": -22.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": 22.8,
    "y": 22.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.1 });
});
it("bore-minimum", async () => {
const parameters = {
  "bore": 35.2
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.1 });
});
it("bore-maximum", async () => {
const parameters = {
  "bore": 44
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": -24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": -24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 24,
    "y": 24
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 60,
  "y": 60,
  "z": 2
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "width": 48,
  "depth": 48,
  "thickness": 1.6,
  "hole": 3.2,
  "bore": 35.2
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 48,
  "y": 48,
  "z": 1.6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": -19.2,
    "y": -19.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": -19.2,
    "y": 19.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": 19.2,
    "y": -19.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.2,
  "center": {
    "x": 19.2,
    "y": 19.2
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 48,
  "y": 48,
  "z": 1.6
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "width": 72,
  "depth": 72,
  "thickness": 2.4,
  "hole": 4.8,
  "bore": 44
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 72,
  "y": 72,
  "z": 2.4
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": -28.8,
    "y": -28.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": -28.8,
    "y": 28.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": 28.8,
    "y": -28.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.8,
  "center": {
    "x": 28.8,
    "y": 28.8
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 72,
  "y": 72,
  "z": 2.4
}, tolerance: 0.1 });
});
});
