/**
 * Deterministic G-code for printer viewer tests, parsed by the real slicer
 * parser so every test runs against the toolpath contract as shipped.
 *
 * @module
 */

import { parseGcode } from '@taucad/slicer/toolpath';
import type { ToolpathProgram } from '@taucad/slicer/toolpath';

/** Shape of the fixture print: a square tube of `layers` layers on a 256 mm plate. */
export type FixtureOptions = Readonly<{
  layers?: number;
  layerHeight?: number;
  size?: number;
  nozzleTemperature?: number;
  bedTemperature?: number;
}>;

const fixed = (value: number): string => value.toFixed(3);

/** Bambu-style G-code: header, one purge line, then a perimeter, an inner wall and two infill lines per layer. */
export const fixtureGcode = ({
  layers = 40,
  layerHeight = 0.2,
  size = 40,
  nozzleTemperature = 220,
  bedTemperature = 60,
}: FixtureOptions = {}): string => {
  const lines = [
    '; generated by the printer viewer fixture',
    'G28',
    `M140 S${bedTemperature}`,
    `M104 S${nozzleTemperature}`,
    'G90',
    'M83',
    'M106 S128',
    ';TYPE:Purge',
    'G1 X20 Y5 Z0.2 F6000',
    'G1 X120 Y5 E8 F1200',
  ];
  const left = 108;
  const front = 108;
  for (let layer = 0; layer < layers; layer += 1) {
    const z = fixed((layer + 1) * layerHeight);
    lines.push(
      ';LAYER_CHANGE',
      `;Z:${z}`,
      `G1 Z${z} F600`,
      `G1 X${left} Y${front} F9000`,
      ';TYPE:Outer wall',
      `G1 X${left + size} Y${front} E1.5 F1800`,
      `G1 X${left + size} Y${front + size} E1.5`,
      `G1 X${left} Y${front + size} E1.5`,
      `G1 X${left} Y${front} E1.5`,
      ';TYPE:Inner wall',
      `G1 X${left + 1} Y${front + 1} F9000`,
      `G1 X${left + size - 1} Y${front + 1} E1.4 F2400`,
      `G1 X${left + size - 1} Y${front + size - 1} E1.4`,
      ';TYPE:Sparse infill',
      `G1 X${left + 4} Y${front + 4} F9000`,
      `G1 X${left + size - 4} Y${front + size - 4} E2 F3000`,
      `G1 X${left + size - 4} Y${front + 4} F9000`,
      `G1 X${left + 4} Y${front + size - 4} E2 F3000`,
    );
  }
  lines.push('M104 S0', 'M140 S0', 'G1 Z50 F600', 'M84', '');
  return lines.join('\n');
};

/** The parsed fixture program. */
export const fixtureProgram = (options?: FixtureOptions): ToolpathProgram => parseGcode(fixtureGcode(options));
