#!/usr/bin/env node

import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

/**
 * Bundle libcascade type declarations as raw `.d.ts` for Monaco's
 * `addExtraLib`.
 *
 * Reads the generated `opencascade_full.d.ts` (produced by the libcascade
 * build pipeline in `buildFromYaml.py`) and outputs a raw module `.d.ts`
 * (no `declare module` wrapper).
 *
 * The package's shared declaration file already distinguishes actual runtime
 * values from type-only aliases. Tau passes that surface through unchanged and
 * adds the default instance exposed by its authored-code virtual module.
 *
 * Monaco registers the output at `file:///node_modules/libcascade/index.d.ts`
 * and relies on standard TypeScript module resolution — `export declare` is
 * valid and correct in this context.
 */

// =============================================================================
// Configuration
// =============================================================================

const opencascadeDtsPath = join(
  import.meta.dirname,
  '../../../packages/runtime/src/kernels/opencascade/wasm/opencascade_full.d.ts',
);

// =============================================================================
// Transformation
// =============================================================================

/**
 * Read the raw `opencascade_full.d.ts` and return its trimmed content.
 *
 * @returns The type declarations as a raw module `.d.ts`.
 */
function buildMainContent(): string {
  const content = readFileSync(opencascadeDtsPath, 'utf8').trim();
  return `${content}\n\ndeclare const oc: OpenCascadeInstance;\nexport default oc;`;
}

// =============================================================================
// Output
// =============================================================================

/**
 * Build the bundled type declarations as a map of module path to raw `.d.ts`
 * content. Each entry is registered at its own virtual file path in Monaco.
 * Exported for testing.
 */
export function buildBundledTypes(): Record<string, string> {
  const mainPackage = 'libcascade';

  return {
    [mainPackage]: [
      '// Bundled type declarations for libcascade.',
      '// Auto-generated by extract-opencascade-types.ts - do not edit manually.',
      '',
      buildMainContent(),
      '',
    ].join('\n'),
  };
}

/**
 * Write the bundled declaration map and its exact filesystem projection.
 *
 * @param options - Generated output root and optional declaration map.
 */
export function writeBundledTypes({
  outputDirectory,
  bundledTypes = buildBundledTypes(),
}: {
  outputDirectory: string;
  bundledTypes?: Record<string, string>;
}): void {
  mkdirSync(outputDirectory, { recursive: true });
  writeFileSync(join(outputDirectory, 'opencascade.bundled.json'), JSON.stringify(bundledTypes));

  const modulesDirectory = join(outputDirectory, 'modules');
  rmSync(modulesDirectory, { recursive: true, force: true });
  for (const [modulePath, content] of Object.entries(bundledTypes)) {
    const targetDirectory = join(modulesDirectory, modulePath);
    mkdirSync(targetDirectory, { recursive: true });
    writeFileSync(join(targetDirectory, 'index.d.ts'), content);
  }
}

// =============================================================================
// Main
// =============================================================================

function main(): void {
  try {
    console.log('Extracting libcascade type declarations...\n');

    const outputDirectory = join(import.meta.dirname, 'generated/opencascade');
    console.log(`Output directory: ${outputDirectory}`);

    const bundledTypes = buildBundledTypes();
    const outputPath = join(outputDirectory, 'opencascade.bundled.json');
    writeBundledTypes({ outputDirectory, bundledTypes });
    console.log(`\nBundled type declarations written to ${outputPath}`);
    for (const [name, content] of Object.entries(bundledTypes)) {
      console.log(`  - ${name} (${(content.length / 1024 / 1024).toFixed(1)} MB)`);
    }
    console.log('\nlibcascade type extraction completed successfully!');
  } catch (error) {
    console.error('Error during libcascade type extraction:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
