#!/usr/bin/env node

import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

/**
 * Bundle @buerli.io/classcad type declarations as raw `.d.ts` content for
 * Monaco's `addExtraLib`.
 *
 * The original @buerli.io/classcad types have deep dependencies on `three`,
 * `@classcad/api-js`, and `@buerli.io/core`. For Monaco IntelliSense we
 * produce a simplified, self-contained declaration that covers the key
 * public API surface: BuerliCadFacade, WASMClient, init, and the primary
 * API types.
 */

// =============================================================================
// Bundled type content
// =============================================================================

/**
 * Build a self-contained `.d.ts` for the `@buerli.io/classcad` module.
 * Inlines the essential types so Monaco can provide IntelliSense without
 * resolving external dependencies.
 */
function buildClasscadModuleContent(): string {
  return `// Bundled type declarations for @buerli.io/classcad.
// Auto-generated by extract-buerli-types.ts - do not edit manually.
// Simplified self-contained declarations for Monaco IntelliSense.

export declare type DrawingID = number;
export declare type ObjectID = number;

export declare const NOID: number;

export declare type ServerResponse = {
  command: string;
  data: unknown;
};

export declare enum BooleanOperationType {
  UNION = 0,
  SUBTRACTION = 1,
  INTERSECTION = 2,
}

export declare enum ExtrusionType {
  UP = 0,
  DOWN = 1,
  SYMMETRIC = 2,
}

export declare type WASMClientConfig = {
  cclasses?: { type: 'classcadkey'; key: string };
  logToConsole?: boolean;
};

export declare class WASMClient {
  constructor(drawingId: DrawingID, config: { classcadKey: string; url?: string; logToConsole?: boolean });
  connect(): Promise<WASMClient>;
  disconnect(): Promise<unknown>;
  request(command: unknown): Promise<ServerResponse>;
  undo(options?: unknown): Promise<ServerResponse>;
  redo(options?: unknown): Promise<ServerResponse>;
}

export declare type PartApi = {
  create(options: { name: string }): Promise<ObjectID>;
  box(options: { id: ObjectID; width: number; depth: number; height: number }): Promise<ObjectID>;
  cylinder(options: { id: ObjectID; axes: unknown[]; radius: number; height: number }): Promise<ObjectID>;
  cone(options: { id: ObjectID; axes: unknown[]; topRadius: number; bottomRadius: number; height: number }): Promise<ObjectID>;
  sphere(options: { id: ObjectID; axes: unknown[]; radius: number }): Promise<ObjectID>;
  torus(options: { id: ObjectID; axes: unknown[]; majorRadius: number; minorRadius: number }): Promise<ObjectID>;
  extrude(options: { id: ObjectID; objectId: ObjectID; height: number; type?: ExtrusionType }): Promise<ObjectID>;
  revolve(options: { id: ObjectID; objectId: ObjectID; angle: number }): Promise<ObjectID>;
  fillet(options: { id: ObjectID; edges: ObjectID[]; radius: number }): Promise<ObjectID>;
  chamfer(options: { id: ObjectID; edges: ObjectID[]; distance: number }): Promise<ObjectID>;
  boolean(options: { id: ObjectID; type: BooleanOperationType; tools: ObjectID[] }): Promise<ObjectID>;
};

export declare type SolidApi = {
  createBox(width: number, depth: number, height: number): Promise<ObjectID>;
  createCylinder(radius: number, height: number, segments?: number): Promise<ObjectID>;
  createCone(bottomRadius: number, topRadius: number, height: number): Promise<ObjectID>;
  createSphere(radius: number): Promise<ObjectID>;
  createTorus(majorRadius: number, minorRadius: number): Promise<ObjectID>;
  extrude(shapeId: ObjectID, height: number): Promise<ObjectID>;
  revolve(shapeId: ObjectID, angle: number): Promise<ObjectID>;
  union(id1: ObjectID, id2: ObjectID): Promise<ObjectID>;
  subtract(id1: ObjectID, id2: ObjectID): Promise<ObjectID>;
  intersect(id1: ObjectID, id2: ObjectID): Promise<ObjectID>;
  fillet(solidId: ObjectID, edgeIds: ObjectID[], radius: number): Promise<ObjectID>;
  chamfer(solidId: ObjectID, edgeIds: ObjectID[], distance: number): Promise<ObjectID>;
  slice(solidId: ObjectID, planeOrigin: [number, number, number], planeNormal: [number, number, number]): Promise<ObjectID>;
};

export declare type AssemblyApi = {
  create(options: { name: string }): Promise<ObjectID>;
  addTemplate(options: { id: ObjectID; templateId: ObjectID }): Promise<ObjectID>;
  addInstance(options: { id: ObjectID; templateId: ObjectID }): Promise<ObjectID>;
  fasten(options: { id: ObjectID; mate1: ObjectID; mate2: ObjectID }): Promise<ObjectID>;
  revolute(options: { id: ObjectID; mate1: ObjectID; mate2: ObjectID }): Promise<ObjectID>;
  slider(options: { id: ObjectID; mate1: ObjectID; mate2: ObjectID }): Promise<ObjectID>;
};

export declare type SketchApi = {
  create(options: { id: ObjectID; planeId?: ObjectID }): Promise<ObjectID>;
  addLine(options: { id: ObjectID; start: [number, number]; end: [number, number] }): Promise<ObjectID>;
  addArc(options: { id: ObjectID; center: [number, number]; start: [number, number]; end: [number, number] }): Promise<ObjectID>;
  addCircle(options: { id: ObjectID; center: [number, number]; radius: number }): Promise<ObjectID>;
  addRectangle(options: { id: ObjectID; origin: [number, number]; width: number; height: number }): Promise<ObjectID>;
};

export declare type CurveApi = {
  createLine(start: [number, number, number], end: [number, number, number]): Promise<ObjectID>;
  createArc(center: [number, number, number], start: [number, number, number], end: [number, number, number]): Promise<ObjectID>;
  createCircle(center: [number, number, number], normal: [number, number, number], radius: number): Promise<ObjectID>;
};

export declare type CommonApi = {
  recalc(drawingId: DrawingID): Promise<void>;
  setColor(objectId: ObjectID, color: string): Promise<void>;
  getEntities(drawingId: DrawingID): Promise<ObjectID[]>;
  deleteObject(objectId: ObjectID): Promise<void>;
  transform(objectId: ObjectID, matrix: number[]): Promise<void>;
  tessellate(objectId: ObjectID, precision?: number): Promise<unknown>;
  exportBrep(objectId: ObjectID, format?: string): Promise<ArrayBuffer>;
};

export declare type ClassCADApiV1 = {
  part: PartApi;
  solid: SolidApi;
  assembly: AssemblyApi;
  sketch: SketchApi;
  curve: CurveApi;
  common: CommonApi;
};

export declare type ClassCADApi = ClassCADApiV1 & {
  v1: ClassCADApiV1;
};

export declare class BuerliCadFacade {
  static utils: {
    connect: (drawingName?: string) => Promise<DrawingID | null>;
    disconnect: (drawingId: DrawingID) => Promise<void>;
    reconnect: (drawingId: DrawingID) => Promise<void>;
    fetchTree: (drawingId: DrawingID) => Promise<void>;
    undo: (drawingId: DrawingID, state?: string) => Promise<void>;
    redo: (drawingId: DrawingID, state?: string) => Promise<void>;
  };

  get drawingId(): DrawingID;
  get api(): ClassCADApi;

  destroy(): Promise<void>;
  connect(drawingName?: string): Promise<DrawingID | null>;
  disconnect(): Promise<void>;
  reconnect(): Promise<void>;
  createBufferGeometry(objectId?: ObjectID | ObjectID[]): Promise<unknown[] | undefined>;
  createScene(objectId?: ObjectID | ObjectID[], options?: {
    meshPerGeometry?: boolean;
    structureOnly?: boolean;
  }): Promise<{
    scene: unknown;
    nodes: Record<string, unknown>;
    materials: Record<string, unknown>;
  }>;
}

export declare function createApi(drawingId: DrawingID, cached?: boolean): ClassCADApi;
export declare function createUnwrappedApi(drawingId: DrawingID, cached?: boolean): ClassCADApi;
export declare function getApiFacade(drawingId: DrawingID): unknown;

export declare type ClientFactory = (drawingId: DrawingID) => unknown;

export declare function init(source: ClientFactory, options?: Record<string, unknown>): void;
`;
}

// =============================================================================
// Output
// =============================================================================

/**
 * Build the bundled type declarations as a map of module path to raw `.d.ts`
 * content. Exported for testing.
 */
const buerliModulePath = '@buerli.io/classcad';

export function buildBundledTypes(): Record<string, string> {
  return {
    [buerliModulePath]: buildClasscadModuleContent(),
  };
}

// =============================================================================
// Main
// =============================================================================

function main(): void {
  try {
    console.log('Extracting @buerli.io/classcad type declarations...\n');

    const outputDirectory = join(import.meta.dirname, 'generated/buerli');
    mkdirSync(outputDirectory, { recursive: true });
    console.log(`Output directory: ${outputDirectory}`);

    const bundledTypes = buildBundledTypes();
    const outputPath = join(outputDirectory, 'buerli.bundled.json');
    writeFileSync(outputPath, JSON.stringify(bundledTypes));
    console.log(`\nBundled type declarations written to ${outputPath}`);
    for (const [name, content] of Object.entries(bundledTypes)) {
      console.log(`  - ${name} (${(content.length / 1024).toFixed(1)} KB)`);
    }

    const modulesDirectory = join(outputDirectory, 'modules');
    for (const [modulePath, content] of Object.entries(bundledTypes)) {
      const targetDirectory = join(modulesDirectory, modulePath);
      mkdirSync(targetDirectory, { recursive: true });
      writeFileSync(join(targetDirectory, 'index.d.ts'), content);
    }

    console.log('\n@buerli.io/classcad type extraction completed successfully!');
  } catch (error) {
    console.error('Error during @buerli.io/classcad type extraction:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
