import { createHash } from 'node:crypto';

import type { MachineArtifactReference, MachineConnectionRuntime } from '@taucad/runtime/machine';
import { unzipSync } from 'fflate';

import { BambuProtocolError } from '#bambu.protocol.js';

const maximumArchiveBytes = 256 * 1024 * 1024;
const maximumEntries = 512;
const maximumExpandedBytes = 512 * 1024 * 1024;
const maximumPlateBytes = 128 * 1024 * 1024;
const plateMember = 'Metadata/plate_1.gcode';
const sliceInfoMember = 'Metadata/slice_info.config';
const maximumSliceInfoBytes = 1024 * 1024;
const producerScanBytes = 16 * 1024;
const parser = Object.freeze({ id: 'tau.bambu.gcode-3mf', version: '1' } as const);
const bambuStudioLine = /^; BambuStudio(?: ([\w.-]{1,64}))?$/u;
const referenceEngineLine = '; generated by @taucad/slicer reference engine';
const clientType = /<header_item\s+key="X-BBL-Client-Type"\s+value="([^"<>]{0,64})"/u;
const clientVersion = /<header_item\s+key="X-BBL-Client-Version"\s+value="([\w.-]{1,64})"/u;

/** Who produced a Bambu container. @internal */
export type BambuArtifactProducer = Readonly<{ name: 'Bambu Studio' | '@taucad/slicer reference'; version?: string }>;

// ponytail: mirrors readBambuContainerProducer in @taucad/slicer/container so the provider takes no slicer
// dependency; bambu.archive.slicer.test.ts asserts both agree.
const readProducer = (
  plate: Uint8Array<ArrayBuffer>,
  sliceInfo: Uint8Array<ArrayBuffer> | undefined,
): BambuArtifactProducer | undefined => {
  const head = new TextDecoder().decode(plate.subarray(0, producerScanBytes));
  for (const line of head.split('\n', 64)) {
    const text = line.trimEnd();
    if (text === referenceEngineLine) {
      return { name: '@taucad/slicer reference' };
    }
    const studio = bambuStudioLine.exec(text);
    if (studio) {
      const config = sliceInfo === undefined ? '' : new TextDecoder().decode(sliceInfo);
      if (clientType.exec(config)?.[1] !== 'slicer') {
        return undefined;
      }
      const version = studio[1] ?? clientVersion.exec(config)?.[1];
      return version === undefined ? { name: 'Bambu Studio' } : { name: 'Bambu Studio', version };
    }
    if (text !== '' && !text.startsWith(';')) {
      return undefined;
    }
  }
  return undefined;
};

/** A verified immutable Bambu container retained only for the following transfer. @internal */
export type BambuPreparedArtifact = Readonly<{
  bytes: Uint8Array<ArrayBuffer>;
  digest: MachineArtifactReference['digest'];
  length: number;
  parser: Readonly<{ id: 'tau.bambu.gcode-3mf'; version: '1' }>;
  memberMd5: string;
  /** The inflated plate G-code, exactly as the printer runs it. */
  plate: Uint8Array<ArrayBuffer>;
  /** The slicer named by the plate header and slice metadata, when recognized. */
  producer?: BambuArtifactProducer;
}>;

const fail = (code: string): never => {
  throw new BambuProtocolError(code);
};

const safeMemberName = (name: string): string => {
  const directory = name.endsWith('/');
  const path = directory ? name.slice(0, -1) : name;
  if (
    path.length === 0 ||
    name.length > 512 ||
    !name.isWellFormed() ||
    name.includes('\\') ||
    name.startsWith('/') ||
    path.split('/').some((segment) => segment === '' || segment === '.' || segment === '..')
  ) {
    return fail('BAMBU_ARCHIVE_MEMBER_INVALID');
  }
  return `${path.normalize('NFC')}${directory ? '/' : ''}`;
};

/** Read and preflight one bounded immutable `.gcode.3mf` without inflating unrelated members.
 * @param input - Qualified artifact, host reader and cancellation.
 * @returns Verified bytes and digest for the immediately following transfer.
 */
export const prepareBambuArtifact = async (
  input: Readonly<{
    artifact: MachineArtifactReference;
    runtime: Pick<MachineConnectionRuntime, 'readArtifact'>;
    signal: AbortSignal;
  }>,
): Promise<BambuPreparedArtifact> => {
  const { artifact } = input;
  if (
    artifact.mediaType !== 'application/vnd.bambulab.gcode-3mf' ||
    artifact.contract.id !== 'manufacturing.toolpath.bambu-gcode-3mf' ||
    artifact.contract.version !== 1 ||
    artifact.selectedMember !== plateMember ||
    !artifact.path.toLowerCase().endsWith('.gcode.3mf') ||
    artifact.length === 0 ||
    artifact.length > maximumArchiveBytes
  ) {
    return fail('BAMBU_ARTIFACT_INCOMPATIBLE');
  }
  const chunks: Array<Uint8Array<ArrayBuffer>> = [];
  let length = 0;
  for await (const chunk of input.runtime.readArtifact({
    artifact,
    maximumBytes: maximumArchiveBytes,
    signal: input.signal,
  })) {
    input.signal.throwIfAborted();
    length += chunk.byteLength;
    if (length > artifact.length || length > maximumArchiveBytes) {
      return fail('BAMBU_ARTIFACT_LENGTH_MISMATCH');
    }
    chunks.push(Uint8Array.from(chunk));
  }
  if (length !== artifact.length) {
    return fail('BAMBU_ARTIFACT_LENGTH_MISMATCH');
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  const digest = `sha256:${createHash('sha256').update(bytes).digest('hex')}` as MachineArtifactReference['digest'];
  if (digest !== artifact.digest) {
    return fail('BAMBU_ARTIFACT_DIGEST_MISMATCH');
  }
  const names = new Set<string>();
  let count = 0;
  let expanded = 0;
  let extracted: ReturnType<typeof unzipSync>;
  try {
    extracted = unzipSync(bytes, {
      filter(file) {
        const name = safeMemberName(file.name);
        const collisionKey = name.toLowerCase();
        count += 1;
        expanded += file.originalSize;
        if (
          count > maximumEntries ||
          file.originalSize > maximumArchiveBytes ||
          expanded > maximumExpandedBytes ||
          names.has(collisionKey)
        ) {
          return fail('BAMBU_ARCHIVE_LIMIT');
        }
        names.add(collisionKey);
        if (name === plateMember) {
          if (file.originalSize === 0 || file.originalSize > maximumPlateBytes) {
            return fail('BAMBU_ARCHIVE_PLATE_INVALID');
          }
          return true;
        }
        return name === sliceInfoMember && file.originalSize <= maximumSliceInfoBytes;
      },
    });
  } catch (error) {
    if (error instanceof TypeError && error.message.startsWith('BAMBU_')) {
      throw error;
    }
    return fail('BAMBU_ARCHIVE_INVALID');
  }
  if (!Object.hasOwn(extracted, plateMember)) {
    return fail('BAMBU_ARCHIVE_PLATE_MISSING');
  }
  const plate = extracted[plateMember]!;
  const producer = readProducer(plate, extracted[sliceInfoMember]);
  return Object.freeze({
    bytes,
    digest,
    length,
    parser,
    memberMd5: createHash('md5').update(plate).digest('hex'),
    plate,
    ...(producer ? { producer: Object.freeze(producer) } : {}),
  });
};
