import { createHash } from 'node:crypto';

import type { MachineArtifactReference, MachineConnectionRuntime } from '@taucad/runtime/machine';
import { unzipSync } from 'fflate';

import { BambuProtocolError } from '#bambu.protocol.js';

const maximumArchiveBytes = 256 * 1024 * 1024;
const maximumEntries = 512;
const maximumExpandedBytes = 512 * 1024 * 1024;
const maximumPlateBytes = 128 * 1024 * 1024;
const plateMember = 'Metadata/plate_1.gcode';
const sliceInfoMember = 'Metadata/slice_info.config';
const maximumSliceInfoBytes = 1024 * 1024;
const producerScanBytes = 16 * 1024;
const parser = Object.freeze({ id: 'tau.bambu.gcode-3mf', version: '1' } as const);
const bambuStudioLine = /^; BambuStudio(?: ([\w.-]{1,64}))?$/u;
const referenceEngineLine = '; generated by @taucad/slicer reference engine';
const clientType = /<header_item\s+key="X-BBL-Client-Type"\s+value="([^"<>]{0,64})"/u;
const clientVersion = /<header_item\s+key="X-BBL-Client-Version"\s+value="([\w.-]{1,64})"/u;

/** Who produced a Bambu container. @internal */
export type BambuArtifactProducer = Readonly<{ name: 'Bambu Studio' | '@taucad/slicer reference'; version?: string }>;

// ponytail: mirrors readBambuContainerProducer in @taucad/slicer/container so the provider takes no slicer
// dependency; bambu.archive.slicer.test.ts asserts both agree.
const readProducer = (
  plate: Uint8Array<ArrayBuffer>,
  sliceInfo: Uint8Array<ArrayBuffer> | undefined,
): BambuArtifactProducer | undefined => {
  const head = new TextDecoder().decode(plate.subarray(0, producerScanBytes));
  for (const line of head.split('\n', 64)) {
    const text = line.trimEnd();
    if (text === referenceEngineLine) {
      return { name: '@taucad/slicer reference' };
    }
    const studio = bambuStudioLine.exec(text);
    if (studio) {
      const config = sliceInfo === undefined ? '' : new TextDecoder().decode(sliceInfo);
      if (clientType.exec(config)?.[1] !== 'slicer') {
        return undefined;
      }
      const version = studio[1] ?? clientVersion.exec(config)?.[1];
      return version === undefined ? { name: 'Bambu Studio' } : { name: 'Bambu Studio', version };
    }
    if (text !== '' && !text.startsWith(';')) {
      return undefined;
    }
  }
  return undefined;
};

/** One filament of the sliced project, in project order. @internal */
export type BambuSlicedFilament = Readonly<{
  /** `filament_type`, such as `PLA`. */
  type: string;
  /** `filament_colour` as `#RRGGBB`, upper case. */
  color?: string;
  /** `filament_diameter`, in millimetres. */
  diameter?: number;
  /** Whether this plate prints it: listed in `slice_info.config`, or every filament when that names none. */
  used: boolean;
}>;

/** What the slice itself says it was made for; a fact the file does not state is absent. @internal */
export type BambuSliceFacts = Readonly<{
  /** `printer_model`, such as `Bambu Lab X1 Carbon`. */
  printerModel?: string;
  /** `nozzle_diameter`, in millimetres. */
  nozzleDiameter?: number;
  /** `curr_bed_type`, such as `Textured PEI Plate`. */
  bedType?: string;
  filaments: readonly BambuSlicedFilament[];
}>;

const configScanBytes = 1024 * 1024;
const configStart = '; CONFIG_BLOCK_START';
const configEnd = '; CONFIG_BLOCK_END';
const colorEntry = /^#([\da-f]{6})(?:[\da-f]{2})?$/iu;
const usedFilament = /<filament\s+id="(\d{1,3})"/gu;

/**
 * Read the facts a check compares with the printer from the plate G-code's config block (Bambu Studio writes it after
 * the header; another slicer may write it at the end) and the plate's filament list in `slice_info.config`.
 * @param plate - The plate G-code.
 * @param sliceInfo - `Metadata/slice_info.config`, when present.
 * @returns The facts the slice states.
 * @internal
 */
export const readBambuSliceFacts = (
  plate: Uint8Array<ArrayBuffer>,
  sliceInfo: Uint8Array<ArrayBuffer> | undefined,
): BambuSliceFacts => {
  const decoder = new TextDecoder();
  const ends = [plate.subarray(0, configScanBytes), plate.subarray(-configScanBytes)].map((bytes) =>
    decoder.decode(bytes),
  );
  const block =
    ends
      .map((text) => {
        const start = text.indexOf(configStart);
        const end = start === -1 ? -1 : text.indexOf(configEnd, start);
        return end === -1 ? undefined : text.slice(start, end);
      })
      .find((text) => text !== undefined) ?? '';
  const setting = (name: string): string | undefined =>
    new RegExp(`^;\\s*${name}\\s*=\\s*(.+?)\\s*$`, 'mu').exec(block)?.[1];
  const list = (name: string): readonly string[] =>
    setting(name)
      ?.split(/[;,]/u)
      .map((entry) => entry.trim().replaceAll('"', '')) ?? [];
  const number = (text: string | undefined): number | undefined => {
    const value = Number(text);
    return text === undefined || text === '' || !Number.isFinite(value) ? undefined : value;
  };
  const colors = list('filament_colour');
  const diameters = list('filament_diameter');
  const listed = new Set(
    [...(sliceInfo === undefined ? '' : decoder.decode(sliceInfo)).matchAll(usedFilament)].map((match) =>
      Number(match[1]),
    ),
  );
  const printerModel = setting('printer_model');
  const bedType = setting('curr_bed_type');
  const nozzleDiameter = number(list('nozzle_diameter')[0]);
  return {
    ...(printerModel === undefined ? {} : { printerModel }),
    ...(nozzleDiameter === undefined ? {} : { nozzleDiameter }),
    ...(bedType === undefined ? {} : { bedType }),
    filaments: list('filament_type').map((type, index) => {
      const color = colorEntry.exec(colors[index] ?? '')?.[1];
      const diameter = number(diameters[index]);
      return {
        type,
        ...(color === undefined ? {} : { color: `#${color.toUpperCase()}` }),
        ...(diameter === undefined ? {} : { diameter }),
        used: listed.size === 0 || listed.has(index + 1),
      };
    }),
  };
};

/** A verified immutable Bambu container retained only for the following transfer. @internal */
export type BambuPreparedArtifact = Readonly<{
  bytes: Uint8Array<ArrayBuffer>;
  digest: MachineArtifactReference['digest'];
  length: number;
  parser: Readonly<{ id: 'tau.bambu.gcode-3mf'; version: '1' }>;
  memberMd5: string;
  /** The inflated plate G-code, exactly as the printer runs it. */
  plate: Uint8Array<ArrayBuffer>;
  /** The slicer named by the plate header and slice metadata, when recognized. */
  producer?: BambuArtifactProducer;
  /** What the slice says it was made for: printer, nozzle, plate and filaments. */
  slice: BambuSliceFacts;
}>;

const fail = (code: string): never => {
  throw new BambuProtocolError(code);
};

const safeMemberName = (name: string): string => {
  const directory = name.endsWith('/');
  const path = directory ? name.slice(0, -1) : name;
  if (
    path.length === 0 ||
    name.length > 512 ||
    !name.isWellFormed() ||
    name.includes('\\') ||
    name.startsWith('/') ||
    path.split('/').some((segment) => segment === '' || segment === '.' || segment === '..')
  ) {
    return fail('BAMBU_ARCHIVE_MEMBER_INVALID');
  }
  return `${path.normalize('NFC')}${directory ? '/' : ''}`;
};

/** Read and preflight one bounded immutable `.gcode.3mf` without inflating unrelated members.
 * @param input - Qualified artifact, host reader and cancellation.
 * @returns Verified bytes and digest for the immediately following transfer.
 */
export const prepareBambuArtifact = async (
  input: Readonly<{
    artifact: MachineArtifactReference;
    runtime: Pick<MachineConnectionRuntime, 'readArtifact'>;
    signal: AbortSignal;
  }>,
): Promise<BambuPreparedArtifact> => {
  const { artifact } = input;
  if (
    artifact.mediaType !== 'application/vnd.bambulab.gcode-3mf' ||
    artifact.contract.id !== 'manufacturing.toolpath.bambu-gcode-3mf' ||
    artifact.contract.version !== 1 ||
    artifact.selectedMember !== plateMember ||
    !artifact.path.toLowerCase().endsWith('.gcode.3mf') ||
    artifact.length === 0 ||
    artifact.length > maximumArchiveBytes
  ) {
    return fail('BAMBU_ARTIFACT_INCOMPATIBLE');
  }
  const chunks: Array<Uint8Array<ArrayBuffer>> = [];
  let length = 0;
  for await (const chunk of input.runtime.readArtifact({
    artifact,
    maximumBytes: maximumArchiveBytes,
    signal: input.signal,
  })) {
    input.signal.throwIfAborted();
    length += chunk.byteLength;
    if (length > artifact.length || length > maximumArchiveBytes) {
      return fail('BAMBU_ARTIFACT_LENGTH_MISMATCH');
    }
    chunks.push(Uint8Array.from(chunk));
  }
  if (length !== artifact.length) {
    return fail('BAMBU_ARTIFACT_LENGTH_MISMATCH');
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  const digest = `sha256:${createHash('sha256').update(bytes).digest('hex')}` as MachineArtifactReference['digest'];
  if (digest !== artifact.digest) {
    return fail('BAMBU_ARTIFACT_DIGEST_MISMATCH');
  }
  const names = new Set<string>();
  let count = 0;
  let expanded = 0;
  let extracted: ReturnType<typeof unzipSync>;
  try {
    extracted = unzipSync(bytes, {
      filter(file) {
        const name = safeMemberName(file.name);
        const collisionKey = name.toLowerCase();
        count += 1;
        expanded += file.originalSize;
        if (
          count > maximumEntries ||
          file.originalSize > maximumArchiveBytes ||
          expanded > maximumExpandedBytes ||
          names.has(collisionKey)
        ) {
          return fail('BAMBU_ARCHIVE_LIMIT');
        }
        names.add(collisionKey);
        if (name === plateMember) {
          if (file.originalSize === 0 || file.originalSize > maximumPlateBytes) {
            return fail('BAMBU_ARCHIVE_PLATE_INVALID');
          }
          return true;
        }
        return name === sliceInfoMember && file.originalSize <= maximumSliceInfoBytes;
      },
    });
  } catch (error) {
    if (error instanceof TypeError && error.message.startsWith('BAMBU_')) {
      throw error;
    }
    return fail('BAMBU_ARCHIVE_INVALID');
  }
  if (!Object.hasOwn(extracted, plateMember)) {
    return fail('BAMBU_ARCHIVE_PLATE_MISSING');
  }
  const plate = extracted[plateMember]!;
  const producer = readProducer(plate, extracted[sliceInfoMember]);
  const slice = readBambuSliceFacts(plate, extracted[sliceInfoMember]);
  return Object.freeze({
    bytes,
    digest,
    length,
    parser,
    memberMd5: createHash('md5').update(plate).digest('hex'),
    plate,
    ...(producer ? { producer: Object.freeze(producer) } : {}),
    slice,
  });
};
