import { createHash } from 'node:crypto';

import type { MachineArtifactReference } from '@taucad/runtime/machine';
import { bambuPlateMember, readBambuContainerProducer, writeBambuContainer } from '@taucad/slicer/container';
import { zipSync } from 'fflate';
import { describe, expect, it } from 'vitest';

import { prepareBambuArtifact } from '#bambu.archive.js';

/* The preflight admits what `@taucad/slicer` writes, and names its producer as the slicer does. */

const encoder = new TextEncoder();
const gcode = 'G28\nG90\nM83\nG1 X10 Y10 F3000\n';
const digest = (bytes: Uint8Array<ArrayBuffer>): MachineArtifactReference['digest'] =>
  `sha256:${createHash('sha256').update(bytes).digest('hex')}` as MachineArtifactReference['digest'];
const prepare = async (bytes: Uint8Array<ArrayBuffer>) =>
  prepareBambuArtifact({
    artifact: {
      projectId: 'proj_000000000000000000001',
      path: 'cube.gcode.3mf',
      digest: digest(bytes),
      length: bytes.byteLength,
      mediaType: 'application/vnd.bambulab.gcode-3mf',
      contract: { id: 'manufacturing.toolpath.bambu-gcode-3mf', version: 1 },
      selectedMember: bambuPlateMember,
    },
    runtime: {
      async *readArtifact() {
        yield Uint8Array.from(bytes);
      },
    },
    signal: new AbortController().signal,
  });

// Synthetic stand-in for a Bambu Studio archive: only the two provenance signals, made-up version.
const studioSliceInfo =
  '<?xml version="1.0" encoding="UTF-8"?>\n<config>\n  <header>\n' +
  '    <header_item key="X-BBL-Client-Type" value="slicer"/>\n' +
  '    <header_item key="X-BBL-Client-Version" value="99.0.0.0"/>\n' +
  '  </header>\n</config>\n';
const studioPlate = `; HEADER_BLOCK_START\n; BambuStudio 99.0.0.0\n; total layer number: 1\n; HEADER_BLOCK_END\n\n${'G1 X1 Y1 E0.1\n'.repeat(200_000)}`;
const studioContainer = (sliceInfo?: string): Uint8Array<ArrayBuffer> =>
  Uint8Array.from(
    zipSync({
      [bambuPlateMember]: encoder.encode(studioPlate),
      ...(sliceInfo === undefined ? {} : { 'Metadata/slice_info.config': encoder.encode(sliceInfo) }),
    }),
  );

describe('Bambu artifact preflight of @taucad/slicer containers', () => {
  it('should admit an immutable artifact', async () => {
    const bytes = writeBambuContainer({ gcode, modelName: 'cube' });
    const prepared = await prepare(bytes);
    expect(prepared).toMatchObject({
      digest: digest(bytes),
      length: bytes.byteLength,
      memberMd5: createHash('md5').update(gcode).digest('hex'),
      parser: { id: 'tau.bambu.gcode-3mf', version: '1' },
    });
  });

  it.each([
    ['a Bambu Studio archive', studioContainer(studioSliceInfo), { name: 'Bambu Studio', version: '99.0.0.0' }],
    [
      'a reference-engine archive',
      writeBambuContainer({ gcode: `; generated by @taucad/slicer reference engine\n${gcode}`, modelName: 'cube' }),
      { name: '@taucad/slicer reference' },
    ],
    ['an archive naming no producer', writeBambuContainer({ gcode, modelName: 'cube' }), undefined],
    ['a Bambu Studio header without slice metadata', studioContainer(), undefined],
    [
      'a Bambu Studio header whose metadata names another client',
      studioContainer(studioSliceInfo.replace('value="slicer"', 'value="other"')),
      undefined,
    ],
  ])('should identify %s the same way the slicer does', async (_name, bytes, producer) => {
    const prepared = await prepare(bytes);
    expect(readBambuContainerProducer(bytes)).toEqual(producer);
    expect(prepared.producer).toEqual(producer);
  });

  it('should keep naming the reference engine as the producer of a coloured plate', async () => {
    const bytes = writeBambuContainer({
      gcode: `; generated by @taucad/slicer reference engine\n${gcode}`,
      modelName: 'cube',
      filamentColors: ['#F5A623'],
    });

    const prepared = await prepare(bytes);

    expect(readBambuContainerProducer(bytes)).toEqual({ name: '@taucad/slicer reference' });
    expect(prepared.producer).toEqual({ name: '@taucad/slicer reference' });
  });
});
