// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 10,
  "bore": 6.5,
  "length": 16
};
export const parameterDomains = {
  "diameter": {
    "min": 8,
    "max": 12
  },
  "bore": {
    "min": 5.2,
    "max": 7.8
  },
  "length": {
    "min": 12.8,
    "max": 19.2
  }
};
export const design = "tubular-spacer";
