// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 10,
  "bore": 6.5,
  "length": 16
};
export const parameterDomains = {
  "diameter": {
    "min": 8,
    "max": 12
  },
  "bore": {
    "min": 5.2,
    "max": 7.8
  },
  "length": {
    "min": 12.8,
    "max": 19.2
  }
};
export const design = "tubular-spacer";
export const parameterCases = [
  {
    "name": "diameter-minimum",
    "parameters": {
      "diameter": 8
    },
    "expectations": {
      "bounds": {
        "x": 8,
        "y": 8,
        "z": 16
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6.5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 273.317560862312,
        "max": 273.31956086231196
      }
    }
  },
  {
    "name": "diameter-maximum",
    "parameters": {
      "diameter": 12
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 16
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6.5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 1278.627210011046,
        "max": 1278.6292100110459
      }
    }
  },
  {
    "name": "bore-minimum",
    "parameters": {
      "bore": 5.2
    },
    "expectations": {
      "bounds": {
        "x": 10,
        "y": 10,
        "z": 16
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5.2,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 916.8414000236452,
        "max": 916.8434000236451
      }
    }
  },
  {
    "name": "bore-maximum",
    "parameters": {
      "bore": 7.8
    },
    "expectations": {
      "bounds": {
        "x": 10,
        "y": 10,
        "z": 16
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 7.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 492.09807325830525,
        "max": 492.1000732583052
      }
    }
  },
  {
    "name": "length-minimum",
    "parameters": {
      "length": 12.8
    },
    "expectations": {
      "bounds": {
        "x": 10,
        "y": 10,
        "z": 12.8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6.5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 580.5653223833939,
        "max": 580.5673223833938
      }
    }
  },
  {
    "name": "length-maximum",
    "parameters": {
      "length": 19.2
    },
    "expectations": {
      "bounds": {
        "x": 10,
        "y": 10,
        "z": 19.2
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6.5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 870.8484835750907,
        "max": 870.8504835750906
      }
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "diameter": 8,
      "bore": 5.2,
      "length": 12.8
    },
    "expectations": {
      "bounds": {
        "x": 8,
        "y": 8,
        "z": 12.8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5.2,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 371.561446325372,
        "max": 371.56344632537196
      }
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "diameter": 12,
      "bore": 7.8,
      "length": 19.2
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 19.2
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 7.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 1254.0222563481304,
        "max": 1254.0242563481304
      }
    }
  },
  {
    "name": "thin-wall-corner",
    "parameters": {
      "diameter": 8,
      "bore": 7.8,
      "length": 16
    },
    "expectations": {
      "bounds": {
        "x": 8,
        "y": 8,
        "z": 16
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 7.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ],
      "volume": {
        "min": 39.70873114137503,
        "max": 39.71073114137503
      }
    }
  }
];
