// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 18,
  "bore": 10,
  "thickness": 0.2
};
export const parameterDomains = {
  "diameter": {
    "min": 14.4,
    "max": 21.599999999999998
  },
  "bore": {
    "min": 8,
    "max": 12
  },
  "thickness": {
    "min": 0.16000000000000003,
    "max": 0.24
  }
};
export const design = "slotted-shim";
