import { Injectable } from '@nestjs/common';
import type { NestMiddleware } from '@nestjs/common';
import type { FastifyRequest, FastifyReply } from 'fastify';
import { httpHeader } from '~/constants/http-header.constant.js';

/**
 * NestJS middleware to set `request-id` response header using the request ID generated by Fastify
 */
@Injectable()
export class RequestIdMiddleware implements NestMiddleware {
  public use(request: FastifyRequest['raw'], reply: FastifyReply['raw'], next: () => void): void {
    const requestHeaderId = request.headers[httpHeader.requestId] as string;
    if (requestHeaderId) {
      // If the request ID is already set, use it to support tracing across services.
      reply.setHeader(httpHeader.requestId, requestHeaderId);
    } else {
      // If the request ID is not set, generate a new one.
      reply.setHeader(httpHeader.requestId, request.id as string);
    }

    next();
  }
}
