import { Injectable } from '@nestjs/common';
import type { NestMiddleware } from '@nestjs/common';
import type { FastifyRequest, FastifyReply } from 'fastify';
import { httpHeader } from '#constants/http-header.constant.js';

/**
 * The shape an inbound `request-id` must have to be propagated. Covers the
 * generated `req_...` ids and the common UUID/ULID forms other services send,
 * and nothing else: no separators, no whitespace and a 64-character cap, so a
 * caller cannot place arbitrary text in response headers, logs and traces.
 */
const requestIdPattern = /^[\w-]{1,64}$/u;

/**
 * The request id to report for a request: the caller's own id when it is a
 * single value of the accepted shape (tracing across services), otherwise the
 * id Fastify generated.
 *
 * @param headerValue - The raw inbound `request-id` header (a repeated header arrives as an array).
 * @param generatedId - Fastify's generated request id.
 * @returns The id to echo and log.
 */
export function resolveRequestId<Generated extends string | undefined>(
  headerValue: unknown,
  generatedId: Generated,
): string | Generated {
  return typeof headerValue === 'string' && requestIdPattern.test(headerValue) ? headerValue : generatedId;
}

/**
 * NestJS middleware to set `request-id` response header using the request ID generated by Fastify
 */
@Injectable()
export class RequestIdMiddleware implements NestMiddleware {
  public use(request: FastifyRequest['raw'], reply: FastifyReply['raw'], next: () => void): void {
    reply.setHeader(
      httpHeader.requestId,
      resolveRequestId(request.headers[httpHeader.requestId], request.id as string),
    );

    next();
  }
}
