// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 60,
  "bore": 8,
  "length": 12
};
export const parameterDomains = {
  "diameter": {
    "min": 54,
    "max": 66
  },
  "bore": {
    "min": 7.2,
    "max": 8.8
  },
  "length": {
    "min": 10.8,
    "max": 13.200000000000001
  }
};
export const design = "star-knob";
export const parameterCases = [
  {
    "name": "diameter 54",
    "parameters": {
      "diameter": 54
    },
    "expectations": {
      "bounds": {
        "x": 54,
        "y": 48.50168257131336,
        "z": 12
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "diameter 66",
    "parameters": {
      "diameter": 66
    },
    "expectations": {
      "bounds": {
        "x": 66,
        "y": 59.27983425382744,
        "z": 12
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore 7.2",
    "parameters": {
      "bore": 7.2
    },
    "expectations": {
      "bounds": {
        "x": 60,
        "y": 53.8907584125704,
        "z": 12
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 7.2,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore 8.8",
    "parameters": {
      "bore": 8.8
    },
    "expectations": {
      "bounds": {
        "x": 60,
        "y": 53.8907584125704,
        "z": 12
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "length 10.8",
    "parameters": {
      "length": 10.8
    },
    "expectations": {
      "bounds": {
        "x": 60,
        "y": 53.8907584125704,
        "z": 10.8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "length 13.200000000000001",
    "parameters": {
      "length": 13.200000000000001
    },
    "expectations": {
      "bounds": {
        "x": 60,
        "y": 53.8907584125704,
        "z": 13.200000000000001
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "diameter": 54,
      "bore": 7.2,
      "length": 10.8
    },
    "expectations": {
      "bounds": {
        "x": 54,
        "y": 48.50168257131336,
        "z": 10.8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 7.2,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "diameter": 66,
      "bore": 8.8,
      "length": 13.200000000000001
    },
    "expectations": {
      "bounds": {
        "x": 66,
        "y": 59.27983425382744,
        "z": 13.200000000000001
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "diameter": 54,
      "bore": 8.8,
      "length": 10.8
    },
    "expectations": {
      "bounds": {
        "x": 54,
        "y": 48.50168257131336,
        "z": 10.8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 8.8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  }
];
