import { globSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import ts from 'typescript';
import { describe, expect, it } from 'vitest';

const root = resolve(import.meta.dirname, '../..');
const runtimeRoot = resolve(root, 'packages/runtime');
const runtimePackage = JSON.parse(readFileSync(resolve(runtimeRoot, 'package.json'), 'utf8')) as {
  readonly exports: Readonly<Record<string, string>>;
};
const sourcePaths = Object.entries(runtimePackage.exports)
  .filter(([subpath]) => subpath !== './package.json')
  .map(([subpath, target]) => {
    if (!target.endsWith('.ts')) {
      throw new Error(`unsupported runtime export target ${subpath}: ${target}`);
    }
    return resolve(runtimeRoot, target);
  });
const program = ts.createProgram(sourcePaths, {
  module: ts.ModuleKind.NodeNext,
  moduleResolution: ts.ModuleResolutionKind.NodeNext,
  target: ts.ScriptTarget.ESNext,
});
const checker = program.getTypeChecker();
const exported = [
  ...new Set(
    sourcePaths.flatMap((sourcePath) => {
      const file = program.getSourceFile(sourcePath);
      if (!file) {
        throw new Error(`missing public entrypoint: ${sourcePath}`);
      }
      const moduleSymbol = checker.getSymbolAtLocation(file);
      if (!moduleSymbol) {
        throw new Error(`public entrypoint has no module symbol: ${sourcePath}`);
      }
      return checker
        .getExportsOfModule(moduleSymbol)
        .map(({ name }) => name)
        .filter((name) => name !== 'default');
    }),
  ),
].toSorted();
const runtimeDocs = globSync('content/docs/runtime/**/*.mdx', { cwd: import.meta.dirname })
  .map((path) => readFileSync(resolve(import.meta.dirname, path), 'utf8'))
  .join('\n');
const hasWholeToken = (content: string, name: string): boolean => {
  const escaped = name.replaceAll(/[.*+?^${}()|[\]\\]/gu, String.raw`\$&`);
  return new RegExp(`(?:^|[^$\\p{ID_Continue}])${escaped}(?:$|[^$\\p{ID_Continue}])`, 'u').test(content);
};

// Static debt ledger: every entry needs public API prose during the rewrite wave.
// Remove a row as soon as its whole-token documentation lands.
const pendingApiReferenceMessage = 'TODO(rewrite wave): add this public export to the API reference.';

const pendingApiReference: ReadonlySet<string> = new Set([
  'AdmitHostOperationInput',
  'AdmittedHostManifestV2',
  'AdmittedHostOperation',
  'AnyKernelDefinition',
  'AnyPluginInstance',
  'BackendProvider',
  'BinaryContentDelivery',
  'BinaryFileContentMetadata',
  'BuildReuse',
  'BundlerRegistration',
  'BundlerRegistrations',
  'CloseComputeScopeInput',
  'CollectExportFormats',
  'CollectFormatMap',
  'CollectKernelIds',
  'CollectRenderOptions',
  'CollectTranscodeMap',
  'CollectTranscoderTargets',
  'CompiledWasmModuleHandle',
  'ComputeAnnounceResult',
  'ComputeAnnouncement',
  'ComputeBinding',
  'ComputeGeneration',
  'ComputeGetInput',
  'ComputeGetResult',
  'ComputePinInput',
  'ComputePinResult',
  'ComputePutInput',
  'ComputePutResult',
  'ComputeReleaseInput',
  'ComputeRetention',
  'ComputeReuseScope',
  'ComputeScopeReceipt',
  'ComputeScopeSettlement',
  'ComputeStore',
  'ComputeStoreControl',
  'ComputeStoreEngine',
  'ComputeStoreEntry',
  'ComputeStoreReport',
  'ComputeStoreSession',
  'ComputeWarmInput',
  'ComputeWarmResult',
  'ConfigurationAdmissionDiagnostic',
  'ConfigurationAdmissionResult',
  'ConfigurationDefinition',
  'ConfigurationIconId',
  'ConfigurationIssue',
  'ConfigurationManifestV1',
  'ConfigurationSource',
  'ContentDependency',
  'ContentHookInputFor',
  'ContentKeysOf',
  'ContentRequestFor',
  'CoordinateSystemOptions',
  'CreateGeometryOutput',
  'CreateHostAdmissionAuthorityInput',
  'ElectronRuntimeForkResolver',
  'ElectronRuntimeHostExit',
  'ElectronRuntimeMainConnectInput',
  'ElectronRuntimeMainConnection',
  'ElectronRuntimeUtilityExit',
  'ElectronUtilityMainClientOptions',
  'ExpandPluginBundlers',
  'ExpandPluginJobs',
  'ExpandPluginKernels',
  'ExpandPluginMachines',
  'ExpandPluginMiddleware',
  'ExpandPluginTranscoders',
  'ExportContentFor',
  'ExportDependency',
  'ExportFormatsFor',
  'ExportGeometryRequest',
  'ExportOptionsFor',
  'ExtractNameResult',
  'FileContentKind',
  'FileContentMetadata',
  'FileExtension',
  'FileInput',
  'FileSystemBackend',
  'FileSystemBackendConfig',
  'FileSystemItem',
  'FilesystemRuntimeSource',
  'FrameContext',
  'GeometryGltf',
  'GeometryGltfTransport',
  'GeometryPoolHandle',
  'GeometryResponseTransport',
  'GeometrySvg',
  'GeometryTransport',
  'GeometryWebRtc',
  'GetDependenciesInput',
  'GetDependenciesResult',
  'GetParametersHandler',
  'GltfContentDelivery',
  'HashedGeometryResultTransport',
  'HostActor',
  'HostAdmissionAuthority',
  'HostAdmissionOperation',
  'HostAdmissionRefusal',
  'HostAdmissionRefusalCode',
  'HostAdmissionRoute',
  'HostCapabilityDescriptor',
  'HostCapabilityEndpoint',
  'HostCapabilityMatch',
  'HostCapabilityRequirement',
  'HostCapabilityRole',
  'HostCapabilityValue',
  'HostManifestV2',
  'HostRouteGrant',
  'HostSessionHandle',
  'IndexedDbComputeEngine',
  'IndexedDbComputeEngineOptions',
  'InitializeInput',
  'InitializeMemoryHandle',
  'InlineResolvedSceneAssetTransport',
  'InlineRuntimeSource',
  'IssueHostSessionInput',
  'JSONArray',
  'JSONObject',
  'JSONSchema7Definition',
  'JSONSchema7Type',
  'JSONSchema7TypeName',
  'JSONValue',
  'JobAcceptedEvent',
  'JobArtifactDeclaration',
  'JobCheckpointPublication',
  'JobCommandDefinition',
  'JobCommandDescriptor',
  'JobCommandReplayPolicy',
  'JobConfigurationInput',
  'JobEffectiveConfiguration',
  'JobExtensionDescriptor',
  'JobInput',
  'JobLifecycleEvent',
  'JobLifecycleState',
  'JobLogEntry',
  'JobProgressUpdate',
  'JobProjectionEvent',
  'JobProviderAttemptServices',
  'JobProviderDefinition',
  'JobProviderDescriptor',
  'JobProviderExecuteInput',
  'JobProviderFactory',
  'JobProviderIdentity',
  'JobProviderRegistration',
  'JobProviderResumeContext',
  'JobPublishedArtifact',
  'JobQueryDefinition',
  'JobRecoveryDescriptor',
  'JobReference',
  'JobRevision',
  'JobSnapshot',
  'JobSubmitInput',
  'JobSubmitOutcome',
  'JobValidationIssue',
  'JsonSchema',
  'KERNEL_MODULES_KEY',
  'KernelComputeCapability',
  'KernelDependency',
  'KernelLibraryTraceHandle',
  'KernelLibraryTraceMode',
  'KernelModules',
  'KernelPluginFactory',
  'KernelProvider',
  'KernelProviderId',
  'KernelRegistration',
  'KernelSceneRuntime',
  'KnownKernelProvider',
  'KnownSourceFormats',
  'KnownTargetFormats',
  'KnownTranscoderIds',
  'ListSceneBookmarksInput',
  'LogOptions',
  'LruMap',
  'MachineAcceptedContainer',
  'MachineArtifactReadInput',
  'MachineArtifactReference',
  'MachineCandidate',
  'MachineCandidateEndpoint',
  'MachineCaptureStillInput',
  'MachineClaimedIdentity',
  'MachineClock',
  'MachineCommandReceipt',
  'MachineConnectInput',
  'MachineConnectionContext',
  'MachineConnectionRuntime',
  'MachineControlInput',
  'MachineDatagram',
  'MachineDatagramListenInput',
  'MachineDeclaredQuery',
  'MachineDescriptor',
  'MachineDiscoveryEvent',
  'MachineDiscoveryInput',
  'MachineDiscoveryRuntime',
  'MachineEnvelope',
  'MachineGetDescriptorInput',
  'MachineGetSnapshotInput',
  'MachineLogEntry',
  'MachineMaterialSystem',
  'MachineNetworkRequest',
  'MachineNetworkStream',
  'MachineObservation',
  'MachineObserveInput',
  'MachineObservedSetup',
  'MachineProvider',
  'MachineProviderDefinition',
  'MachineProviderFactory',
  'MachineQueryManifest',
  'MachineSession',
  'MachineSnapshot',
  'MachineStill',
  'MachineStillCaptureCapability',
  'MachineSubmissionReceipt',
  'MachineSubmitInput',
  'MachineToolCapability',
  'MachineTransportTrust',
  'MatchHostCapabilitiesInput',
  'MaterializedRender',
  'MemoryComputeEngine',
  'MergeExportMap',
  'MeshArtifactFinalizerInput',
  'MeshGeometryInput',
  'MeshGeometryOutput',
  'MeshGeometryRequest',
  'MeshGeometryResult',
  'MiddlewareRegistration',
  'MiddlewareRegistrations',
  'MimeType',
  'NativeBuildInput',
  'NativeBuildInputCarrier',
  'OnWorkerLog',
  'OpenComputeScopeInput',
  'PluginCapabilities',
  'PluginFactory',
  'PluginInstance',
  'PluginMeta',
  'ProgressiveSceneCapability',
  'ProgressiveSceneUpdate',
  'ProgressiveSceneUpdateTransport',
  'PublishSceneBookmarkInput',
  'PublishSceneComponentInput',
  'PublishSceneComponentRefinementInput',
  'PublishSceneGraphUpdateInput',
  'PublishSceneUpdateInput',
  'PublishSceneUpdateOutcome',
  'ReadSceneSnapshotInput',
  'ReadSceneSnapshotResult',
  'ReferencedResolvedSceneAssetTransport',
  'RenderArtifactFinalizationError',
  'RenderArtifactFinalizerInput',
  'RenderContentFor',
  'RenderId',
  'RenderOptionsDependency',
  'RenderOptionsFor',
  'ResidentCacheBinding',
  'ResidentCacheStats',
  'ResidentExportEntry',
  'ResolvedSceneAsset',
  'ResolvedSceneAssetTransport',
  'ResolvedSceneSnapshot',
  'ResolvedSceneSnapshotTransport',
  'RestrictedRjsfUiSchemaV1',
  'RestrictedUiNodeV1',
  'RestrictedUiWidgetV1',
  'RuntimeBinaryMaterialisedArgs',
  'RuntimeCapabilityRegistration',
  'RuntimeContentDeclaration',
  'RuntimeContentKey',
  'RuntimeContentUnsupportedError',
  'RuntimeErrorEventArgs',
  'RuntimeEvaluateInput',
  'RuntimeEvaluateModelArgs',
  'RuntimeExportArgs',
  'RuntimeExportFileTransport',
  'RuntimeExportModelArgs',
  'RuntimeExportResultTransport',
  'RuntimeGeometryComputedArgs',
  'RuntimeHelloPayload',
  'RuntimeHostDefinition',
  'RuntimeHostDefinitionInput',
  'RuntimeInitializeArgs',
  'RuntimeInitializeResult',
  'RuntimeKernelMessageArgs',
  'RuntimeListSceneBookmarksInput',
  'RuntimeLogOptions',
  'RuntimeLogger',
  'RuntimeModuleExports',
  'RuntimeOpenFileArgs',
  'RuntimeParametersResolvedArgs',
  'RuntimePluginDeclaration',
  'RuntimePluginPermissions',
  'RuntimePreviewIdentity',
  'RuntimeProgressArgs',
  'RuntimeReadSceneSnapshotInput',
  'RuntimeSetOptionsArgs',
  'RuntimeSourceContent',
  'RuntimeSourceSnapshotArgs',
  'RuntimeStageAndRenderArgs',
  'RuntimeStateChangedArgs',
  'RuntimeTerminatedDetail',
  'RuntimeTranscodeArgs',
  'RuntimeUpdateParametersArgs',
  'RuntimeWatchEvent',
  'RuntimeWatchRequest',
  'SceneAssetGeometry',
  'SceneAssetReference',
  'SceneAssetReplacement',
  'SceneBookmark',
  'SceneBookmarkReceipt',
  'SceneNodeId',
  'SceneTransform',
  'SignalBufferHandle',
  'SqliteComputeEngine',
  'SqliteComputeEngineOptions',
  'SqliteComputeWorker',
  'SqliteComputeWorkerConnect',
  'StandardSchemaV1',
  'StandardSchemaV1FailureResult',
  'StandardSchemaV1InferInput',
  'StandardSchemaV1InferOutput',
  'StandardSchemaV1Issue',
  'StandardSchemaV1PathSegment',
  'StandardSchemaV1Props',
  'StandardSchemaV1Result',
  'StandardSchemaV1SuccessResult',
  'StandardSchemaV1Types',
  'StringKeyedObject',
  'TauSceneManifest',
  'TauSceneNode',
  'TauSceneOperation',
  'TauScenePresentation',
  'TextFileContentMetadata',
  'Topic',
  'TopicOptions',
  'TopicSubscribeOptions',
  'TopicSubscription',
  'TranscodeInput',
  'TranscodeResult',
  'TranscoderDefinition',
  'TranscoderEdge',
  'TranscoderEdgeType',
  'TranscoderPlugin',
  'TranscoderPluginFactory',
  'TranscoderRuntime',
  'TransportCapabilities',
  'UnitOptions',
  'ValidateConfigurationInput',
  'ValidateConfigurationResult',
  'WebAssemblyException',
  'WireAbortReasonCode',
  'WorkerLog',
  'admitConfigurationManifest',
  'admitJsonSchema',
  'applyLibrarySourceMaps',
  'asBuffer',
  'assertRootedPath',
  'awaitElectronRelayedPort',
  'cadEdgeOverlayMaterialDefaults',
  'cadMaterialDefaults',
  'checkAbort',
  'classifyLibraryFrames',
  'compileWasmStreaming',
  'configurationIconIds',
  'connectComputeStoreChannel',
  'connectSqliteComputeStoreWorker',
  'contentDefault',
  'convertRawIssuesToKernelIssues',
  'coordinateSystemSchema',
  'createExportFile',
  'createFrameClassifier',
  'createHostAdmissionAuthority',
  'createIndexedDbComputeEngine',
  'createKernelLibraryTracer',
  'createKernelModuleRegistryExpression',
  'createKernelModuleShim',
  'createMemoryComputeEngine',
  'createSqliteComputeEngine',
  'defineConfiguration',
  'defineJobCommand',
  'defineJobProvider',
  'defineJobQuery',
  'defineLibraryTracePolicy',
  'defineMachine',
  'defineMachineQuery',
  'demangleStackFrames',
  'deriveLocationFromFrames',
  'electronUtilityMainClient',
  'electronUtilityMainTransport',
  'enrichIssueLocation',
  'exportFidelities',
  'exposeComputeStoreChannel',
  'extractDefaultParameters',
  'fileExtensionSet',
  'fileExtensions',
  'fileParameterEntrySchema',
  'finalizeMeshOutput',
  'fromIndexedDb',
  'fromSqlite',
  'getActiveGroupValues',
  'getIsolationStatus',
  'getModuleRegistry',
  'getParametersResultSchema',
  'getWebAssemblyExceptionConstructor',
  'gltfExportConventionSchema',
  'hashString',
  'isNode',
  'isPluginFactory',
  'isPluginInstance',
  'isRecordObject',
  'isSafeRelativePath',
  'isWebAssemblyException',
  'joinRelativePath',
  'jsonSchemaFromJson',
  'kittyCadBoundaryRepresentationExtension',
  'loadBinaryFile',
  'loadWasmBinary',
  'lookupExportFidelity',
  'lookupMimeType',
  'matchHostCapabilities',
  'mimeTypes',
  'nativeBuildInputSymbol',
  'normalizeRuntimeContent',
  'packageName',
  'packageVersion',
  'parametersDirectory',
  'parseHostManifest',
  'parseJobSubmitInput',
  'parseStackTrace',
  'preserveExportNames',
  'quantity',
  'reduceJobSnapshot',
  'registerKernelModule',
  'relayElectronPorts',
  'resolveFileUrl',
  'resolveRootedPath',
  'resolveSourcePath',
  'resolveWasmUrl',
  'runtimeContentDefaults',
  'runtimeContentProperties',
  'runtimeContentSchema',
  'runtimePluginAbiVersionOf',
  'runtimeProtocolCallNames',
  'runtimeProtocolClientNotifyNames',
  'runtimeProtocolListenNames',
  'runtimeProtocolNotifyNames',
  'runtimeProtocolWorkerNotifyNames',
  'serveSqliteComputeStoreWorker',
  'sha256Bytes',
  'sha256String',
  'signalSlot',
  'sourcePathMatchesExtensions',
  'sqliteComputeWorkerConnectType',
  'tauCadTopologyExtension',
  'toVmEntryPath',
  'unitSchema',
  'validateConfiguration',
  'validateRuntimeContentDeclarations',
  'withoutEmscriptenProcessListeners',
]);

describe('runtime API documentation coverage', () => {
  it('keeps exclusions limited to current public exports', () => {
    expect([...pendingApiReference].filter((name) => !exported.includes(name))).toEqual([]);
  });

  it.each(exported)('documents or explicitly excludes %s', (name) => {
    const documented = hasWholeToken(runtimeDocs, name);
    if (pendingApiReference.has(name)) {
      expect(documented, `${name}: ${pendingApiReferenceMessage} Remove the exclusion once documented.`).toBe(false);
      return;
    }

    expect(documented, `${name} is a public @taucad/runtime export but does not appear in the runtime MDX.`).toBe(true);
  });
});
