/* oxlint-disable eslint/no-await-in-loop -- Process one project at a time to bound native memory and preserve deterministic corpus ordering. */
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { readDefinitions, packageRoot } from '#scripts/definitions.js';
import type { PartDefinition, PartExpectations } from '#definition.js';
import { validateParameters } from '#validation.js';

const check = process.argv.includes('--check');
const generated = '// Generated by warehouse:generate. Edit definitions, then regenerate.\n';
const write = async (path: string, content: string) => {
  if (check) {
    if ((await readFile(path, 'utf8').catch(() => '')) !== content) {
      throw new Error(`Stale generated file: ${path}`);
    }
  } else {
    await mkdir(join(path, '..'), { recursive: true });
    await writeFile(path, content);
  }
};
const json = (value: unknown) => JSON.stringify(value, undefined, 2);
const assertDefinition = (part: PartDefinition) => {
  if (!/^[\da-z]+(?:-[\da-z]+)*$/.test(part.id)) {
    throw new Error(`Unsafe part id: ${part.id}`);
  }
  validateParameters(part.parameters, part.domains);
  const cases = [part.parameters, ...part.cases.map(({ parameters }) => ({ ...part.parameters, ...parameters }))];
  for (const parameters of cases) {
    validateParameters(parameters, part.domains);
  }
  for (const [name, domain] of Object.entries(part.domains)) {
    for (const value of domain.values ?? [domain.min, domain.max]) {
      if (!cases.some((parameters) => parameters[name] === value)) {
        throw new Error(`${part.id}: no qualified case for ${name}=${value}`);
      }
    }
  }
  if (new Set(part.cases.map(({ name }) => name)).size !== part.cases.length) {
    throw new Error(`Duplicate case name in ${part.id}`);
  }
};
const assertions = (expectations: PartExpectations) =>
  [
    `expectGeo(exact).toHaveBoundingBox({ size: ${json(expectations.bounds)}, tolerance: 0.05 });`,
    `expectGeo(exact).toHaveTopologyCounts({ solids: ${expectations.solids} });`,
    ...(expectations.volume
      ? [
          `expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: ${expectations.volume.min}, lessThanOrEqual: ${expectations.volume.max} } });`,
        ]
      : ['expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });']),
    ...(expectations.planes ?? []).map((plane) => `expectGeo(exact).toHavePlanarFace(${json(plane)});`),
    ...(expectations.voids ?? []).map((void_) => `expectGeo(exact).toHaveVoidContinuity(${json(void_)});`),
    ...(expectations.holes ?? []).map(
      (hole) => `expectGeo(exact).toHaveCircularHole(${json({ ...hole, through: true, tolerance: 0.05 })});`,
    ),
  ].join('\n');
const serializedNumbers =
  '/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */\n';
const spec = (part: PartDefinition) =>
  generated +
  serializedNumbers +
  `import { describe, it, expectGeo } from 'geospec';\nimport { loadModel } from 'geospec/model';\ndescribe(${JSON.stringify(part.name)}, () => {\n` +
  [{ name: 'default', parameters: {}, expectations: part.expectations }, ...part.cases]
    .map(
      (variant) =>
        `it(${JSON.stringify(variant.name)}, async () => {\nconst parameters = ${json(variant.parameters)};\nconst exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });\nexpectGeo(exact).toHaveNoDiagnostics();\nexpectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });\nexpectGeo(exact).toHaveStepUnits({ unit: 'mm' });\n${assertions(variant.expectations)}\nconst mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });\nexpectGeo(mesh).toHaveNoDiagnostics();\nexpectGeo(mesh).toBeWatertight();\nexpectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });\nexpectGeo(mesh).toHaveBoundingBox({ size: ${json(variant.expectations.bounds)}, tolerance: 0.1 });\n});`,
    )
    .join('\n') +
  '\n});\n';
const entries = await readDefinitions();
if (new Set(entries.map(({ part }) => part.id)).size !== entries.length) {
  throw new Error('Duplicate warehouse part ids.');
}
const validation = await readFile(join(packageRoot, 'src/validation.ts'), 'utf8');
const catalog: string[] = [];
for (const { part, directory } of entries) {
  assertDefinition(part);
  const root = join(packageRoot, 'parts', part.id);
  const projectId = 'proj_' + createHash('sha256').update(`warehouse.${part.id}`).digest('base64url').slice(0, 21);
  const manifest = {
    $schema: 'https://tau.new/schemas/tau-schema-v1.json',
    id: projectId,
    name: part.name,
    description: part.description,
    tags: [part.category, 'parametric', 'replicad', 'warehouse'],
    assets: { main: { entryPath: 'main.ts', thumbnail: 'thumbnail.webp' } },
  };
  const files: Record<string, string> = {
    'tau.json': json(manifest) + '\n',
    'parameters.ts':
      generated +
      serializedNumbers +
      `export const defaultParams = ${json(part.parameters)};\nexport const parameterDomains = ${json(part.domains)};\nexport const design = ${JSON.stringify(part.design)};\n`,
    'validation.ts': validation,
    'main.ts':
      generated +
      '/* oxlint-disable no-barrel-files/no-barrel-files -- Kernel parameter discovery requires the main module to expose its local parameter defaults. */\n' +
      `import type { Shape3D, ShapeConfig } from 'replicad';\nimport build from './model.js';\nimport { defaultParams, parameterDomains, design } from './parameters.js';\nimport { validateParameters } from './validation.js';\nexport { defaultParams } from './parameters.js';\nexport default function main(parameters = defaultParams): Shape3D | ShapeConfig[] {\nvalidateParameters(parameters, parameterDomains);\nreturn build(parameters, design);\n}\n`,
    'main.geospec.ts': spec(part),
    'README.md': `# ${part.name}\n\n${part.description}\n\n${part.fidelity}\n\nAll dimensions are millimetres. Edit main.ts and its local model.ts or use Tau parameters. Domains and qualified combinations are in parameters.ts. Defaults and every declared domain boundary/discrete value are tested by main.geospec.ts through STEP and GLB. These finite checks do not prove every intermediate real-valued combination.\n`,
  };
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (
      entry.isFile() &&
      entry.name.endsWith('.ts') &&
      entry.name !== 'catalog.ts' &&
      !/\.test(?:-d)?\.ts$/.test(entry.name)
    ) {
      files[entry.name] = await readFile(join(directory, entry.name), 'utf8');
    }
  }
  for (const [name, content] of Object.entries(files)) {
    await write(join(root, name), content);
  }
  const thumbnail = await readFile(join(root, 'thumbnail.webp')).catch(() => undefined);
  const module =
    generated +
    (part.id === 'i-beam'
      ? '/* oxlint-disable unicorn-js/prevent-abbreviations -- I-beam is the established engineering name. */\n'
      : '') +
    '/* oxlint-disable eslint/no-template-curly-in-string -- Serialized project source intentionally contains template placeholders. */\n' +
    `export const files: Readonly<Record<string, string>> = ${json(files)};\nexport const thumbnail = ${JSON.stringify(thumbnail?.toString('base64') ?? '')};\n`;
  await write(join(packageRoot, 'src/projects', `${part.id}.ts`), module);
  catalog.push(
    `{locator:${JSON.stringify('warehouse.' + part.id)},kernel:'replicad',manifest:${json(manifest)},${thumbnail ? `thumbnailUrl:new URL('../parts/${part.id}/thumbnail.webp', import.meta.url).href,` : ''}assets:[${Object.keys(
      files,
    )
      .map(
        (name) =>
          `{path:${JSON.stringify(name)},load:async()=>{const source=await import('./projects/${part.id}.js');return new TextEncoder().encode(source.files[${JSON.stringify(name)}]);}}`,
      )
      .join(
        ',',
      )}${thumbnail ? `,{path:'thumbnail.webp',load:async()=>{const source=await import('./projects/${part.id}.js');return Uint8Array.from(globalThis.atob(source.thumbnail),(character)=>character.codePointAt(0) ?? 0);}}` : ''}]}`,
  );
}
await write(
  join(packageRoot, 'src/builtin.ts'),
  generated +
    `import type { WarehousePart } from '#types.js';\n/** Editable parts; source bytes load only when requested. @public */\nexport const warehouseParts: readonly WarehousePart[] = [${catalog.join(',\n')}];\n/** Find a part by its stable warehouse locator.\n * @param locator - Stable identifier such as warehouse.hex-head-bolt.\n * @returns The matching part, or undefined when the locator is unknown.\n * @public\n */\nexport const findWarehousePart = (locator: string): WarehousePart | undefined => warehouseParts.find((part) => part.locator === locator);\n`,
);
console.log(`${check ? 'Checked' : 'Generated'} ${entries.length} warehouse projects.`);

/* oxlint-enable eslint/no-await-in-loop */
