// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 12,
  "bore": 6.5,
  "thickness": 1.5,
  "height": 2,
  "gap": 15
};
export const parameterDomains = {
  "diameter": {
    "min": 9.600000000000001,
    "max": 14.399999999999999
  },
  "bore": {
    "min": 5.2,
    "max": 7.8
  },
  "thickness": {
    "min": 1.2000000000000002,
    "max": 1.7999999999999998
  },
  "height": {
    "min": 1.6,
    "max": 2.4
  },
  "gap": {
    "min": 12,
    "max": 18
  }
};
export const design = "split-lock-washer";
export const parameterCases = [
  {
    "name": "diameter-minimum",
    "parameters": {
      "diameter": 9.600000000000001
    },
    "expectations": {
      "bounds": {
        "x": 9.600000000000001,
        "y": 9.600000000000001,
        "z": 3.5
      },
      "solids": 1
    }
  },
  {
    "name": "diameter-maximum",
    "parameters": {
      "diameter": 14.399999999999999
    },
    "expectations": {
      "bounds": {
        "x": 14.399999999999999,
        "y": 14.399999999999999,
        "z": 3.5
      },
      "solids": 1
    }
  },
  {
    "name": "bore-minimum",
    "parameters": {
      "bore": 5.2
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.5
      },
      "solids": 1
    }
  },
  {
    "name": "bore-maximum",
    "parameters": {
      "bore": 7.8
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.5
      },
      "solids": 1
    }
  },
  {
    "name": "thickness-minimum",
    "parameters": {
      "thickness": 1.2000000000000002
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.2
      },
      "solids": 1
    }
  },
  {
    "name": "thickness-maximum",
    "parameters": {
      "thickness": 1.7999999999999998
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.8
      },
      "solids": 1
    }
  },
  {
    "name": "height-minimum",
    "parameters": {
      "height": 1.6
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.1
      },
      "solids": 1
    }
  },
  {
    "name": "height-maximum",
    "parameters": {
      "height": 2.4
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.9
      },
      "solids": 1
    }
  },
  {
    "name": "gap-minimum",
    "parameters": {
      "gap": 12
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.5
      },
      "solids": 1
    }
  },
  {
    "name": "gap-maximum",
    "parameters": {
      "gap": 18
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 3.5
      },
      "solids": 1
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "diameter": 9.600000000000001,
      "bore": 5.2,
      "thickness": 1.2000000000000002,
      "height": 1.6,
      "gap": 12
    },
    "expectations": {
      "bounds": {
        "x": 9.600000000000001,
        "y": 9.600000000000001,
        "z": 2.8000000000000003
      },
      "solids": 1
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "diameter": 14.399999999999999,
      "bore": 7.8,
      "thickness": 1.7999999999999998,
      "height": 2.4,
      "gap": 18
    },
    "expectations": {
      "bounds": {
        "x": 14.399999999999999,
        "y": 14.399999999999999,
        "z": 4.199999999999999
      },
      "solids": 1
    }
  },
  {
    "name": "thin-wall-corner",
    "parameters": {
      "diameter": 9.600000000000001,
      "bore": 7.8,
      "thickness": 1.5,
      "height": 2,
      "gap": 15
    },
    "expectations": {
      "bounds": {
        "x": 9.600000000000001,
        "y": 9.600000000000001,
        "z": 3.5
      },
      "solids": 1
    }
  }
];
