// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 12,
  "bore": 6.5,
  "thickness": 1.5,
  "height": 2,
  "gap": 15
};
export const parameterDomains = {
  "diameter": {
    "min": 9.600000000000001,
    "max": 14.399999999999999
  },
  "bore": {
    "min": 5.2,
    "max": 7.8
  },
  "thickness": {
    "min": 1.2000000000000002,
    "max": 1.7999999999999998
  },
  "height": {
    "min": 1.6,
    "max": 2.4
  },
  "gap": {
    "min": 12,
    "max": 18
  }
};
export const design = "split-lock-washer";
