// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Swept pipe elbow", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 57,
  "y": 30,
  "z": 57
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 593.7610115284709,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 42,
  "area": 593.7610115284709,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.2
    ],
    [
      0,
      0,
      18
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      0.6
    ],
    "max": [
      3.5999999999999996,
      3.5999999999999996,
      21.6
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      18
    ],
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      14.4
    ],
    "max": [
      5.426891219729118,
      3.5999999999999996,
      30.784402376762152
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ],
    [
      7.029437251522858,
      0,
      34.970562748477136
    ]
  ],
  "bounds": {
    "min": [
      -1.7731087802708814,
      -3.5999999999999996,
      23.584402376762156
    ],
    "max": [
      10.629437251522859,
      3.5999999999999996,
      38.57056274847714
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      7.029437251522858,
      0,
      34.970562748477136
    ],
    [
      14.815597623237844,
      0,
      40.17310878027088
    ]
  ],
  "bounds": {
    "min": [
      3.4294372515228586,
      -3.5999999999999996,
      31.370562748477134
    ],
    "max": [
      18.415597623237844,
      3.5999999999999996,
      43.77310878027088
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      14.815597623237844,
      0,
      40.17310878027088
    ],
    [
      23.999999999999996,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      11.215597623237844,
      -3.5999999999999996,
      36.57310878027088
    ],
    "max": [
      27.599999999999994,
      3.5999999999999996,
      45.6
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      23.999999999999996,
      0,
      42
    ],
    [
      40.8,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      20.4,
      -3.5999999999999996,
      38.4
    ],
    "max": [
      41.4,
      3.5999999999999996,
      45.6
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 57,
  "y": 30,
  "z": 57
}, tolerance: 0.1 });
});
it("diameter 27", async () => {
const parameters = {
  "diameter": 27
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 55.5,
  "y": 27,
  "z": 55.5
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 459.45792558750725,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 42,
  "area": 459.45792558750725,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.2
    ],
    [
      0,
      0,
      18
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      0.6
    ],
    "max": [
      3.5999999999999996,
      3.5999999999999996,
      21.6
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      18
    ],
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      14.4
    ],
    "max": [
      5.426891219729118,
      3.5999999999999996,
      30.784402376762152
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ],
    [
      7.029437251522858,
      0,
      34.970562748477136
    ]
  ],
  "bounds": {
    "min": [
      -1.7731087802708814,
      -3.5999999999999996,
      23.584402376762156
    ],
    "max": [
      10.629437251522859,
      3.5999999999999996,
      38.57056274847714
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      7.029437251522858,
      0,
      34.970562748477136
    ],
    [
      14.815597623237844,
      0,
      40.17310878027088
    ]
  ],
  "bounds": {
    "min": [
      3.4294372515228586,
      -3.5999999999999996,
      31.370562748477134
    ],
    "max": [
      18.415597623237844,
      3.5999999999999996,
      43.77310878027088
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      14.815597623237844,
      0,
      40.17310878027088
    ],
    [
      23.999999999999996,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      11.215597623237844,
      -3.5999999999999996,
      36.57310878027088
    ],
    "max": [
      27.599999999999994,
      3.5999999999999996,
      45.6
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      23.999999999999996,
      0,
      42
    ],
    [
      40.8,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      20.4,
      -3.5999999999999996,
      38.4
    ],
    "max": [
      41.4,
      3.5999999999999996,
      45.6
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 55.5,
  "y": 27,
  "z": 55.5
}, tolerance: 0.1 });
});
it("diameter 33", async () => {
const parameters = {
  "diameter": 33
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 58.5,
  "y": 33,
  "z": 58.5
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 742.2012644105886,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 42,
  "area": 742.2012644105886,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.2
    ],
    [
      0,
      0,
      18
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      0.6
    ],
    "max": [
      3.5999999999999996,
      3.5999999999999996,
      21.6
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      18
    ],
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      14.4
    ],
    "max": [
      5.426891219729118,
      3.5999999999999996,
      30.784402376762152
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ],
    [
      7.029437251522858,
      0,
      34.970562748477136
    ]
  ],
  "bounds": {
    "min": [
      -1.7731087802708814,
      -3.5999999999999996,
      23.584402376762156
    ],
    "max": [
      10.629437251522859,
      3.5999999999999996,
      38.57056274847714
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      7.029437251522858,
      0,
      34.970562748477136
    ],
    [
      14.815597623237844,
      0,
      40.17310878027088
    ]
  ],
  "bounds": {
    "min": [
      3.4294372515228586,
      -3.5999999999999996,
      31.370562748477134
    ],
    "max": [
      18.415597623237844,
      3.5999999999999996,
      43.77310878027088
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      14.815597623237844,
      0,
      40.17310878027088
    ],
    [
      23.999999999999996,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      11.215597623237844,
      -3.5999999999999996,
      36.57310878027088
    ],
    "max": [
      27.599999999999994,
      3.5999999999999996,
      45.6
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      23.999999999999996,
      0,
      42
    ],
    [
      40.8,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      20.4,
      -3.5999999999999996,
      38.4
    ],
    "max": [
      41.4,
      3.5999999999999996,
      45.6
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 58.5,
  "y": 33,
  "z": 58.5
}, tolerance: 0.1 });
});
it("bore 10.8", async () => {
const parameters = {
  "bore": 10.8
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 57,
  "y": 30,
  "z": 57
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 615.2495052790251,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 42,
  "area": 615.2495052790251,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.2
    ],
    [
      0,
      0,
      18
    ]
  ],
  "bounds": {
    "min": [
      -3.24,
      -3.24,
      0.6
    ],
    "max": [
      3.24,
      3.24,
      21.240000000000002
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      18
    ],
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ]
  ],
  "bounds": {
    "min": [
      -3.24,
      -3.24,
      14.76
    ],
    "max": [
      5.0668912197291185,
      3.24,
      30.424402376762153
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ],
    [
      7.029437251522858,
      0,
      34.970562748477136
    ]
  ],
  "bounds": {
    "min": [
      -1.413108780270882,
      -3.24,
      23.944402376762156
    ],
    "max": [
      10.26943725152286,
      3.24,
      38.21056274847714
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      7.029437251522858,
      0,
      34.970562748477136
    ],
    [
      14.815597623237844,
      0,
      40.17310878027088
    ]
  ],
  "bounds": {
    "min": [
      3.789437251522858,
      -3.24,
      31.730562748477134
    ],
    "max": [
      18.055597623237844,
      3.24,
      43.41310878027088
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      14.815597623237844,
      0,
      40.17310878027088
    ],
    [
      23.999999999999996,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      11.575597623237844,
      -3.24,
      36.93310878027088
    ],
    "max": [
      27.239999999999995,
      3.24,
      45.24
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      23.999999999999996,
      0,
      42
    ],
    [
      40.8,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      20.759999999999998,
      -3.24,
      38.76
    ],
    "max": [
      41.4,
      3.24,
      45.24
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 57,
  "y": 30,
  "z": 57
}, tolerance: 0.1 });
});
it("bore 13.200000000000001", async () => {
const parameters = {
  "bore": 13.200000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 57,
  "y": 30,
  "z": 57
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 570.0105710673321,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 42,
  "area": 570.0105710673321,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.2
    ],
    [
      0,
      0,
      18
    ]
  ],
  "bounds": {
    "min": [
      -3.96,
      -3.96,
      0.6
    ],
    "max": [
      3.96,
      3.96,
      21.96
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      18
    ],
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ]
  ],
  "bounds": {
    "min": [
      -3.96,
      -3.96,
      14.04
    ],
    "max": [
      5.786891219729118,
      3.96,
      31.144402376762155
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.8268912197291183,
      0,
      27.184402376762154
    ],
    [
      7.029437251522858,
      0,
      34.970562748477136
    ]
  ],
  "bounds": {
    "min": [
      -2.1331087802708817,
      -3.96,
      23.224402376762153
    ],
    "max": [
      10.989437251522858,
      3.96,
      38.930562748477136
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      7.029437251522858,
      0,
      34.970562748477136
    ],
    [
      14.815597623237844,
      0,
      40.17310878027088
    ]
  ],
  "bounds": {
    "min": [
      3.0694372515228583,
      -3.96,
      31.010562748477135
    ],
    "max": [
      18.775597623237843,
      3.96,
      44.13310878027088
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      14.815597623237844,
      0,
      40.17310878027088
    ],
    [
      23.999999999999996,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      10.855597623237845,
      -3.96,
      36.21310878027088
    ],
    "max": [
      27.959999999999997,
      3.96,
      45.96
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      23.999999999999996,
      0,
      42
    ],
    [
      40.8,
      0,
      42
    ]
  ],
  "bounds": {
    "min": [
      20.039999999999996,
      -3.96,
      38.04
    ],
    "max": [
      41.4,
      3.96,
      45.96
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 57,
  "y": 30,
  "z": 57
}, tolerance: 0.1 });
});
it("length 54", async () => {
const parameters = {
  "length": 54
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 52.8,
  "y": 30,
  "z": 52.8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 593.7610115284709,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 37.8,
  "area": 593.7610115284709,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.08
    ],
    [
      0,
      0,
      16.2
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      0.54
    ],
    "max": [
      3.5999999999999996,
      3.5999999999999996,
      19.799999999999997
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      16.2
    ],
    [
      1.6442020977562066,
      0,
      24.46596213908594
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      12.6
    ],
    "max": [
      5.244202097756206,
      3.5999999999999996,
      28.06596213908594
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.6442020977562066,
      0,
      24.46596213908594
    ],
    [
      6.326493526370573,
      0,
      31.473506473629428
    ]
  ],
  "bounds": {
    "min": [
      -1.955797902243793,
      -3.5999999999999996,
      20.865962139085937
    ],
    "max": [
      9.926493526370573,
      3.5999999999999996,
      35.07350647362943
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      6.326493526370573,
      0,
      31.473506473629428
    ],
    [
      13.33403786091406,
      0,
      36.15579790224379
    ]
  ],
  "bounds": {
    "min": [
      2.7264935263705734,
      -3.5999999999999996,
      27.873506473629426
    ],
    "max": [
      16.93403786091406,
      3.5999999999999996,
      39.75579790224379
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      13.33403786091406,
      0,
      36.15579790224379
    ],
    [
      21.599999999999998,
      0,
      37.8
    ]
  ],
  "bounds": {
    "min": [
      9.73403786091406,
      -3.5999999999999996,
      32.55579790224379
    ],
    "max": [
      25.199999999999996,
      3.5999999999999996,
      41.4
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      21.599999999999998,
      0,
      37.8
    ],
    [
      36.72,
      0,
      37.8
    ]
  ],
  "bounds": {
    "min": [
      18,
      -3.5999999999999996,
      34.199999999999996
    ],
    "max": [
      37.26,
      3.5999999999999996,
      41.4
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 52.8,
  "y": 30,
  "z": 52.8
}, tolerance: 0.1 });
});
it("length 66", async () => {
const parameters = {
  "length": 66
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 61.199999999999996,
  "y": 30,
  "z": 61.199999999999996
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 593.7610115284709,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 46.199999999999996,
  "area": 593.7610115284709,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.32
    ],
    [
      0,
      0,
      19.8
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      0.66
    ],
    "max": [
      3.5999999999999996,
      3.5999999999999996,
      23.4
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      19.8
    ],
    [
      2.0095803417020304,
      0,
      29.90284261443837
    ]
  ],
  "bounds": {
    "min": [
      -3.5999999999999996,
      -3.5999999999999996,
      16.200000000000003
    ],
    "max": [
      5.60958034170203,
      3.5999999999999996,
      33.50284261443837
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      2.0095803417020304,
      0,
      29.90284261443837
    ],
    [
      7.732380976675144,
      0,
      38.46761902332486
    ]
  ],
  "bounds": {
    "min": [
      -1.5904196582979693,
      -3.5999999999999996,
      26.30284261443837
    ],
    "max": [
      11.332380976675143,
      3.5999999999999996,
      42.06761902332486
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      7.732380976675144,
      0,
      38.46761902332486
    ],
    [
      16.29715738556163,
      0,
      44.19041965829797
    ]
  ],
  "bounds": {
    "min": [
      4.132380976675145,
      -3.5999999999999996,
      34.867619023324856
    ],
    "max": [
      19.897157385561627,
      3.5999999999999996,
      47.79041965829797
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      16.29715738556163,
      0,
      44.19041965829797
    ],
    [
      26.4,
      0,
      46.2
    ]
  ],
  "bounds": {
    "min": [
      12.69715738556163,
      -3.5999999999999996,
      40.59041965829797
    ],
    "max": [
      30,
      3.5999999999999996,
      49.800000000000004
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      26.4,
      0,
      46.2
    ],
    [
      44.879999999999995,
      0,
      46.199999999999996
    ]
  ],
  "bounds": {
    "min": [
      22.799999999999997,
      -3.5999999999999996,
      42.599999999999994
    ],
    "max": [
      45.54,
      3.5999999999999996,
      49.800000000000004
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 61.199999999999996,
  "y": 30,
  "z": 61.199999999999996
}, tolerance: 0.1 });
});
it("combined min", async () => {
const parameters = {
  "diameter": 27,
  "bore": 10.8,
  "length": 54
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 51.3,
  "y": 27,
  "z": 51.3
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 480.94641933806145,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 37.8,
  "area": 480.94641933806145,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.08
    ],
    [
      0,
      0,
      16.2
    ]
  ],
  "bounds": {
    "min": [
      -3.24,
      -3.24,
      0.54
    ],
    "max": [
      3.24,
      3.24,
      19.439999999999998
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      16.2
    ],
    [
      1.6442020977562066,
      0,
      24.46596213908594
    ]
  ],
  "bounds": {
    "min": [
      -3.24,
      -3.24,
      12.959999999999999
    ],
    "max": [
      4.884202097756207,
      3.24,
      27.70596213908594
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.6442020977562066,
      0,
      24.46596213908594
    ],
    [
      6.326493526370573,
      0,
      31.473506473629428
    ]
  ],
  "bounds": {
    "min": [
      -1.5957979022437936,
      -3.24,
      21.225962139085937
    ],
    "max": [
      9.566493526370573,
      3.24,
      34.71350647362943
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      6.326493526370573,
      0,
      31.473506473629428
    ],
    [
      13.33403786091406,
      0,
      36.15579790224379
    ]
  ],
  "bounds": {
    "min": [
      3.086493526370573,
      -3.24,
      28.233506473629426
    ],
    "max": [
      16.57403786091406,
      3.24,
      39.39579790224379
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      13.33403786091406,
      0,
      36.15579790224379
    ],
    [
      21.599999999999998,
      0,
      37.8
    ]
  ],
  "bounds": {
    "min": [
      10.09403786091406,
      -3.24,
      32.91579790224379
    ],
    "max": [
      24.839999999999996,
      3.24,
      41.04
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      21.599999999999998,
      0,
      37.8
    ],
    [
      36.72,
      0,
      37.8
    ]
  ],
  "bounds": {
    "min": [
      18.36,
      -3.24,
      34.559999999999995
    ],
    "max": [
      37.26,
      3.24,
      41.04
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 51.3,
  "y": 27,
  "z": 51.3
}, tolerance: 0.1 });
});
it("combined max", async () => {
const parameters = {
  "diameter": 33,
  "bore": 13.200000000000001,
  "length": 66
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 62.699999999999996,
  "y": 33,
  "z": 62.699999999999996
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 718.4508239494497,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 46.199999999999996,
  "area": 718.4508239494497,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.32
    ],
    [
      0,
      0,
      19.8
    ]
  ],
  "bounds": {
    "min": [
      -3.96,
      -3.96,
      0.66
    ],
    "max": [
      3.96,
      3.96,
      23.76
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      19.8
    ],
    [
      2.0095803417020304,
      0,
      29.90284261443837
    ]
  ],
  "bounds": {
    "min": [
      -3.96,
      -3.96,
      15.84
    ],
    "max": [
      5.969580341702031,
      3.96,
      33.86284261443837
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      2.0095803417020304,
      0,
      29.90284261443837
    ],
    [
      7.732380976675144,
      0,
      38.46761902332486
    ]
  ],
  "bounds": {
    "min": [
      -1.9504196582979696,
      -3.96,
      25.94284261443837
    ],
    "max": [
      11.692380976675144,
      3.96,
      42.42761902332486
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      7.732380976675144,
      0,
      38.46761902332486
    ],
    [
      16.29715738556163,
      0,
      44.19041965829797
    ]
  ],
  "bounds": {
    "min": [
      3.7723809766751444,
      -3.96,
      34.50761902332486
    ],
    "max": [
      20.25715738556163,
      3.96,
      48.15041965829797
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      16.29715738556163,
      0,
      44.19041965829797
    ],
    [
      26.4,
      0,
      46.2
    ]
  ],
  "bounds": {
    "min": [
      12.337157385561628,
      -3.96,
      40.23041965829797
    ],
    "max": [
      30.36,
      3.96,
      50.160000000000004
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      26.4,
      0,
      46.2
    ],
    [
      44.879999999999995,
      0,
      46.199999999999996
    ]
  ],
  "bounds": {
    "min": [
      22.439999999999998,
      -3.96,
      42.239999999999995
    ],
    "max": [
      45.54,
      3.96,
      50.160000000000004
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 62.699999999999996,
  "y": 33,
  "z": 62.699999999999996
}, tolerance: 0.1 });
});
it("minimum envelope maximum openings", async () => {
const parameters = {
  "diameter": 27,
  "bore": 13.200000000000001,
  "length": 54
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 51.3,
  "y": 27,
  "z": 51.3
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHavePlanarFace({
  "normal": [
    0,
    0,
    1
  ],
  "offset": 0,
  "area": 435.7074851263684,
  "tolerance": 0.03
});
expectGeo(exact).toHavePlanarFace({
  "normal": [
    1,
    0,
    0
  ],
  "offset": 37.8,
  "area": 435.7074851263684,
  "tolerance": 0.03
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      1.08
    ],
    [
      0,
      0,
      16.2
    ]
  ],
  "bounds": {
    "min": [
      -3.96,
      -3.96,
      0.54
    ],
    "max": [
      3.96,
      3.96,
      20.16
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      0,
      0,
      16.2
    ],
    [
      1.6442020977562066,
      0,
      24.46596213908594
    ]
  ],
  "bounds": {
    "min": [
      -3.96,
      -3.96,
      12.239999999999998
    ],
    "max": [
      5.604202097756207,
      3.96,
      28.42596213908594
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      1.6442020977562066,
      0,
      24.46596213908594
    ],
    [
      6.326493526370573,
      0,
      31.473506473629428
    ]
  ],
  "bounds": {
    "min": [
      -2.3157979022437933,
      -3.96,
      20.505962139085938
    ],
    "max": [
      10.286493526370574,
      3.96,
      35.43350647362943
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      6.326493526370573,
      0,
      31.473506473629428
    ],
    [
      13.33403786091406,
      0,
      36.15579790224379
    ]
  ],
  "bounds": {
    "min": [
      2.366493526370573,
      -3.96,
      27.513506473629427
    ],
    "max": [
      17.29403786091406,
      3.96,
      40.11579790224379
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      13.33403786091406,
      0,
      36.15579790224379
    ],
    [
      21.599999999999998,
      0,
      37.8
    ]
  ],
  "bounds": {
    "min": [
      9.374037860914061,
      -3.96,
      32.19579790224379
    ],
    "max": [
      25.56,
      3.96,
      41.76
    ]
  }
});
expectGeo(exact).toHaveVoidContinuity({
  "path": [
    [
      21.599999999999998,
      0,
      37.8
    ],
    [
      36.72,
      0,
      37.8
    ]
  ],
  "bounds": {
    "min": [
      17.639999999999997,
      -3.96,
      33.839999999999996
    ],
    "max": [
      37.26,
      3.96,
      41.76
    ]
  }
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 51.3,
  "y": 27,
  "z": 51.3
}, tolerance: 0.1 });
});
});
