#!/usr/bin/env node
/**
 * Prepare reviewed manifest-only `0.0.0` npm package-name reservations plus the
 * operator's authenticated publish/trust/audit script.
 *
 * npm cannot configure a trusted publisher for a name that does not exist, so a
 * new package is reserved once with a placeholder carrying identity metadata and
 * nothing else (docs/policy/napi-architecture-policy.md §8).
 *
 * Usage: node prepare.mjs --spec <spec.json> --out <directory>
 * Spec:  [{ name, repository: "owner/repo", workflow: "ci.yml", license, author, description }]
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';

const arg = (flag) => {
  const index = process.argv.indexOf(flag);
  if (index === -1) throw new Error(`missing ${flag}`);
  return process.argv[index + 1];
};

const out = resolve(arg('--out'));
const packages = JSON.parse(readFileSync(resolve(arg('--spec')), 'utf8'));
const staging = join(out, '.staging');
rmSync(staging, { recursive: true, force: true });
mkdirSync(staging, { recursive: true });

const integrities = [];
for (const { name, repository, license, author, description } of packages) {
  const directory = join(staging, name.replaceAll('/', '__').replace('@', ''));
  mkdirSync(directory, { recursive: true });
  // Identity and ownership only: no entry point, files list, selectors, engines,
  // binaries or optional dependencies. A placeholder is not an installable release.
  writeFileSync(
    join(directory, 'package.json'),
    `${JSON.stringify({ name, version: '0.0.0', description, license, repository, author }, undefined, 2)}\n`,
  );
  execFileSync('npm', ['pack', '--ignore-scripts', '--pack-destination', out], { cwd: directory, stdio: 'pipe' });
}

for (const file of readdirSync(out)
  .filter((entry) => entry.endsWith('.tgz'))
  .sort()) {
  const bytes = readFileSync(join(out, file));
  // A placeholder ships exactly one file. Anything else is a review failure.
  const entries = execFileSync('tar', ['-tzf', join(out, file)], { encoding: 'utf8' })
    .trim()
    .split('\n');
  const unexpected = entries.filter((entry) => entry !== 'package/package.json');
  if (unexpected.length > 0) throw new Error(`${file} contains ${unexpected.join(', ')}`);
  integrities.push(`${file}  sha512-${createHash('sha512').update(bytes).digest('base64')}`);
}
writeFileSync(join(out, 'INTEGRITIES.txt'), `${integrities.join('\n')}\n`);
rmSync(staging, { recursive: true, force: true });

const shellArray = (values) => values.map((value) => `  "${value}"`).join('\n');
const tarballFor = (name) => `${name.replace('@', '').replaceAll('/', '-')}-0.0.0.tgz`;
const groups = [...new Set(packages.map(({ repository, workflow }) => `${repository} ${workflow}`))];

writeFileSync(
  join(out, 'bootstrap.sh'),
  `#!/usr/bin/env bash
# Generated by .agents/skills/bootstrap-package. Review before running.
# Reserves each name at 0.0.0 under the \`bootstrap\` tag, then binds its trusted
# publisher. Serial, idempotent, stops on the first error so it can be resumed.
set -uo pipefail
cd "$(dirname "\${BASH_SOURCE[0]}")"

need=11.15.0
have=$(npm --version)
if [ "$(printf '%s\\n%s\\n' "$need" "$have" | sort -V | head -n1)" != "$need" ]; then
  echo "npm $have is below $need — \\\`npm trust\\\` is unavailable. Run \\\`nvm use 26\\\` first." >&2
  exit 1
fi
who=$(npm whoami) || { echo "not logged in — run \\\`npm login\\\` (web login, no granular token) first." >&2; exit 1; }
echo "npm $have as $who"

echo "== preflight"
if ! (while read -r file _; do
        printf '%s  sha512-%s\\n' "$file" "$(openssl dgst -sha512 -binary "$file" | base64)"
      done < INTEGRITIES.txt) | diff -q - INTEGRITIES.txt >/dev/null; then
  echo "PREFLIGHT FAILED — tarballs do not match INTEGRITIES.txt. Do not publish." >&2
  exit 1
fi
echo "preflight OK ($(wc -l < INTEGRITIES.txt | tr -d ' ') tarballs)"

echo "== publish"
NAMES=(
${shellArray(packages.map(({ name }) => name))}
)
TARBALLS=(
${shellArray(packages.map(({ name }) => tarballFor(name)))}
)
for i in "\${!NAMES[@]}"; do
  n="\${NAMES[$i]}"
  if npm view "$n" version >/dev/null 2>&1; then echo "skip $n (exists)"; continue; fi
  npm publish "\${TARBALLS[$i]}" --tag bootstrap --access public --provenance=false || { echo "STOPPED at $n" >&2; exit 1; }
  sleep 2
done

echo "== trust"
${groups
  .map((group) => {
    const [repository, workflow] = group.split(' ');
    const names = packages.filter((entry) => `${entry.repository} ${entry.workflow}` === group).map(({ name }) => name);
    return `for n in ${names.map((name) => `"${name}"`).join(' ')}; do
  npm trust github "$n" --repository ${repository} --file ${workflow} --allow-publish --yes || { echo "STOPPED at $n" >&2; exit 1; }
  sleep 2
done`;
  })
  .join('\n')}

echo "== audit"
# npm scans packages at publish time, so a just-published name is invisible to
# \`npm view\` — and uninstallable — for minutes. The trust binding is readable
# immediately; poll the public read path with bounded backoff rather than
# reporting a 404 that only means "not scanned yet".
for n in "\${NAMES[@]}"; do
  echo "-- $n"
  npm trust list "$n" --json
  sleep 2
done

echo "== registry visibility (bounded backoff)"
for attempt in $(seq 1 20); do
  pending=()
  for n in "\${NAMES[@]}"; do
    npm view "$n" dist-tags --json >/dev/null 2>&1 || pending+=("$n")
  done
  [ "\${#pending[@]}" -eq 0 ] && break
  echo "attempt $attempt: \${#pending[@]} awaiting npm publish-time scanning"
  sleep 60
done
if [ "\${#pending[@]}" -ne 0 ]; then
  echo "still pending after 20 minutes: \${pending[*]} — re-run this section later; the publishes stand." >&2
else
  for n in "\${NAMES[@]}"; do
    printf '%-45s %s | %s\\n' "$n" "$(npm view "$n" dist-tags --json 2>/dev/null | tr -d '\\n ')" "$(npm view "$n@0.0.0" dist.integrity 2>/dev/null)"
  done
fi

echo
echo "Remaining manual step (npmjs.com only, the CLI cannot set it):"
echo "  Settings > Publishing access > Require two-factor authentication and disallow tokens"
echo "  for each of: \${NAMES[*]}"
`,
  { mode: 0o755 },
);

console.log(`${packages.length} placeholders + bootstrap.sh in ${out}`);
for (const line of integrities) console.log(`  ${line}`);
