import type { Project } from './project-grid';

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Parametric Gear Generator',
    description: 'A fully customizable gear system with automatic mesh generation and stress analysis',
    image:
      'https://makerworld.bblmw.com/makerworld/model/USce1b6106deb1fb/design/2025-01-28_c52ecae10189c.jpeg?x-oss-process=image/resize,w_1000/format,webp',
    stars: 245,
    forks: 72,
    author: {
      name: 'Sarah Chen',
      avatar: '/avatar-sample.png',
    },
    language: 'OpenSCAD',
    categories: ['Mechanical'],
    tags: ['gears', 'parametric', 'engineering'],
  },
  {
    id: '2',
    title: 'Modular Drone Frame',
    description: 'Open-source drone frame design with swappable components and printable parts',
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?q=80&w=640',
    stars: 189,
    forks: 45,
    author: {
      name: 'Alex Kumar',
      avatar: '/avatar-sample.png',
    },
    language: 'Replicad',
    categories: ['Mechanical', 'Electrical'],
    tags: ['drone', 'modular', '3D-printing'],
  },
  {
    id: '3',
    title: 'Smart Home Hub Enclosure',
    description: 'Customizable enclosure for DIY smart home controllers with cooling optimization',
    image: 'https://media.bunnings.com.au/api/public/content/f65b9387002740cabdab22149ea669c0?v=42a24028',
    stars: 156,
    forks: 38,
    author: {
      name: 'Maria Garcia',
      avatar: '/avatar-sample.png',
    },
    language: 'KCL',
    categories: ['Electrical', 'Firmware'],
    tags: ['smart-home', 'IoT', 'enclosure'],
  },
  {
    id: '4',
    title: 'Electric Skateboard Mount',
    description: 'Optimized motor mount design for DIY electric skateboards with built-in cooling',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=640',
    stars: 324,
    forks: 89,
    author: {
      name: 'Tom Wilson',
      avatar: '/avatar-sample.png',
    },
    language: 'Replicad',
    categories: ['Mechanical', 'Electrical'],
    tags: ['e-mobility', 'skateboard', 'motor-mount'],
  },
  {
    id: '5',
    title: 'Modular Building System',
    description: 'Architectural components for rapid prototyping of building designs',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=640',
    stars: 892,
    forks: 156,
    author: {
      name: 'Emma Smith',
      avatar: '/avatar-sample.png',
    },
    language: 'OpenSCAD',
    categories: ['Mechanical'],
    tags: ['architecture', 'modular', 'prototyping'],
  },
  {
    id: '6',
    title: 'PCB Enclosure Generator',
    description: 'Parametric electronics enclosure with custom PCB mounting options',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?q=80&w=640',
    stars: 467,
    forks: 92,
    author: {
      name: 'David Park',
      avatar: '/avatar-sample.png',
    },
    language: 'KCL',
    categories: ['Electrical'],
    tags: ['electronics', 'PCB', 'parametric'],
  },
  {
    id: '7',
    title: 'Robotic Arm Assembly',
    description: '6-axis robotic arm with inverse kinematics and servo mounts',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=640',
    stars: 1243,
    forks: 278,
    author: {
      name: 'Michael Chang',
      avatar: '/avatar-sample.png',
    },
    language: 'OpenSCAD',
    categories: ['Mechanical'],
    tags: ['robotics', 'kinematics', 'servo'],
  },
  {
    id: '8',
    title: 'Solar Panel Mount',
    description: 'Adjustable mounting system for solar panels with wind load analysis',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=640',
    stars: 534,
    forks: 112,
    author: {
      name: 'Lisa Johnson',
      avatar: '/avatar-sample.png',
    },
    language: 'Replicad',
    categories: ['Mechanical'],
    tags: ['solar', 'renewable-energy', 'mounting'],
  },
  {
    id: '9',
    title: 'Mechanical Keyboard Case',
    description: 'Custom keyboard case with integrated wrist rest and cable routing',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=640',
    stars: 678,
    forks: 145,
    author: {
      name: 'Ryan Martinez',
      avatar: '/avatar-sample.png',
    },
    language: 'KCL',
    categories: ['Mechanical'],
    tags: ['keyboard', 'mechanical-keyboard', 'case'],
  },
  {
    id: '10',
    title: '3D Printer Upgrades',
    description: 'Collection of enhancement parts for popular 3D printer models',
    image:
      'https://i.all3dp.com/workers/images/fit=scale-down,w=1920,h=1080,gravity=0.5x0.5,format=auto/wp-content/uploads/2022/05/20172502/PXL_20220114_183227051.PORTRAIT-scaled.jpg',
    stars: 892,
    forks: 234,
    author: {
      name: 'Chris Anderson',
      avatar: '/avatar-sample.png',
    },
    language: 'OpenSCAD',
    categories: ['Mechanical'],
    tags: ['3D-printing', 'upgrades', 'DIY'],
  },
  {
    id: '11',
    title: 'Hydroponics System',
    description: 'Modular hydroponics setup with nutrient flow optimization',
    image: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=640',
    stars: 445,
    forks: 89,
    author: {
      name: 'Sophie Turner',
      avatar: '/avatar-sample.png',
    },
    language: 'Replicad',
    categories: ['Mechanical'],
    tags: ['hydroponics', 'gardening', 'automation'],
  },
  {
    id: '12',
    title: 'Camera Gimbal Mount',
    description: '3-axis camera stabilizer with quick-release plate',
    image:
      'https://content.instructables.com/FIX/2WP3/I9QWHCF2/FIX2WP3I9QWHCF2.png?auto=webp&frame=1&crop=3:2&width=667&height=1024&fit=bounds&md=MjAxNS0wNS0xNiAxNDoyMToyNy4w',
    stars: 567,
    forks: 123,
    author: {
      name: 'James Lee',
      avatar: '/avatar-sample.png',
    },
    language: 'KCL',
    categories: ['Mechanical'],
    tags: ['camera', 'gimbal', 'stabilizer'],
  },
  {
    id: '13',
    title: 'Wind Turbine Blades',
    description: 'Optimized small-scale wind turbine blade design with CFD analysis',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=640',
    stars: 789,
    forks: 167,
    author: {
      name: 'Anna White',
      avatar: '/avatar-sample.png',
    },
    language: 'OpenSCAD',
    categories: ['Mechanical'],
    tags: ['wind-energy', 'turbine', 'CFD'],
  },
  {
    id: '14',
    title: 'Ergonomic Mouse',
    description: 'Vertical mouse design optimized for wrist comfort',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=640',
    stars: 234,
    forks: 45,
    author: {
      name: 'Peter Zhang',
      avatar: '/avatar-sample.png',
    },
    language: 'Replicad',
    categories: ['Mechanical'],
    tags: ['ergonomics', 'mouse', 'design'],
  },
  {
    id: '15',
    title: 'Micro RC Car Chassis',
    description: '1:24 scale RC car frame with suspension geometry',
    image: 'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=640',
    stars: 345,
    forks: 78,
    author: {
      name: 'Kevin Brown',
      avatar: '/avatar-sample.png',
    },
    language: 'KCL',
    categories: ['Mechanical'],
    tags: ['RC-car', 'chassis', 'suspension'],
  },
  {
    id: '16',
    title: 'Modular Shelf System',
    description: 'Customizable shelving with hidden bracket design',
    image:
      'https://media.printables.com/media/prints/230356/images/2136386_a71237f4-d2f3-4cba-a749-173a58bde021/thumbs/inside/1280x960/jpg/001.webp',
    stars: 567,
    forks: 89,
    author: {
      name: 'Rachel Green',
      avatar: '/avatar-sample.png',
    },
    language: 'OpenSCAD',
    categories: ['Mechanical'],
    tags: ['shelving', 'modular', 'furniture'],
  },
  {
    id: '17',
    title: 'Bike Light Mount',
    description: 'Universal bicycle light mounting system with quick release',
    image: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?q=80&w=640',
    stars: 234,
    forks: 56,
    author: {
      name: 'Daniel Kim',
      avatar: '/avatar-sample.png',
    },
    language: 'Replicad',
    categories: ['Mechanical'],
    tags: ['bicycle', 'light-mount', 'accessories'],
  },
  {
    id: '18',
    title: 'Server Rack Design',
    description: '4U rack mount case with advanced cooling system',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=640',
    stars: 678,
    forks: 145,
    author: {
      name: 'Eric Thompson',
      avatar: '/avatar-sample.png',
    },
    language: 'KCL',
    categories: ['Mechanical'],
    tags: ['server', 'rack-mount', 'cooling'],
  },
  {
    id: '19',
    title: 'Garden Irrigation',
    description: 'Smart irrigation system with pressure-compensating emitters',
    image: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?q=80&w=640',
    stars: 445,
    forks: 98,
    author: {
      name: 'Laura Martinez',
      avatar: '/avatar-sample.png',
    },
    language: 'OpenSCAD',
    categories: ['Mechanical'],
    tags: ['irrigation', 'gardening', 'automation'],
  },
  {
    id: '20',
    title: 'Desktop CNC Frame',
    description: 'Rigid desktop CNC machine frame with linear rail guides',
    image: 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?q=80&w=640',
    stars: 892,
    forks: 234,
    author: {
      name: 'Mark Wilson',
      avatar: '/avatar-sample.png',
    },
    language: 'KCL',
    categories: ['Mechanical', 'Electrical'],
    tags: ['CNC', 'desktop-manufacturing', 'DIY'],
  },
];
