// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "module": 2,
  "teeth": 24,
  "width": 12
};
export const parameterDomains = {
  "module": {
    "min": 1.5,
    "max": 2.5
  },
  "teeth": {
    "min": 20,
    "max": 32,
    "integer": true,
    "values": [
      20,
      24,
      32
    ]
  },
  "width": {
    "min": 8,
    "max": 16
  }
};
export const design = "ring-gear";
export const parameterCases = [
  {
    "name": "module 1.5",
    "parameters": {
      "module": 1.5
    },
    "expectations": {
      "bounds": {
        "x": 48,
        "y": 48,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 7517.173449078529,
        "max": 10756.88196823075
      }
    }
  },
  {
    "name": "module 2.5",
    "parameters": {
      "module": 2.5
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 80,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 20881.037358551468,
        "max": 29880.227689529856
      }
    }
  },
  {
    "name": "teeth 20",
    "parameters": {
      "teeth": 20
    },
    "expectations": {
      "bounds": {
        "x": 56,
        "y": 56,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 11501.527784424912,
        "max": 16310.991977805526
      }
    }
  },
  {
    "name": "teeth 24",
    "parameters": {
      "teeth": 24
    },
    "expectations": {
      "bounds": {
        "x": 64,
        "y": 64,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 13363.863909472942,
        "max": 19123.345721299112
      }
    }
  },
  {
    "name": "teeth 32",
    "parameters": {
      "teeth": 32
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 80,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 17088.536159569,
        "max": 24748.053208286274
      }
    }
  },
  {
    "name": "width 8",
    "parameters": {
      "width": 8
    },
    "expectations": {
      "bounds": {
        "x": 64,
        "y": 64,
        "z": 8
      },
      "solids": 1,
      "volume": {
        "min": 8909.242606315294,
        "max": 12748.89714753274
      }
    }
  },
  {
    "name": "width 16",
    "parameters": {
      "width": 16
    },
    "expectations": {
      "bounds": {
        "x": 64,
        "y": 64,
        "z": 16
      },
      "solids": 1,
      "volume": {
        "min": 17818.48521263059,
        "max": 25497.79429506548
      }
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "module": 1.5,
      "teeth": 20,
      "width": 8
    },
    "expectations": {
      "bounds": {
        "x": 42,
        "y": 42,
        "z": 8
      },
      "solids": 1,
      "volume": {
        "min": 4313.072919159342,
        "max": 6116.621991677072
      }
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "module": 2.5,
      "teeth": 32,
      "width": 16
    },
    "expectations": {
      "bounds": {
        "x": 100,
        "y": 100,
        "z": 16
      },
      "solids": 1,
      "volume": {
        "min": 35601.11699910208,
        "max": 51558.444183929736
      }
    }
  }
];
