packages:
  - .
@@CREATE_REPO_docs-workspace-entry@@
@@CREATE_REPO_native-workspace-entry@@

allowBuilds:
  '@biomejs/biome': true
  '@swc/core': true
  esbuild: true
  nx: true

linkWorkspacePackages: true
