// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 6
};
export const parameterDomains = {
  "diameter": {
    "min": 3,
    "max": 10,
    "values": [
      3,
      4,
      5,
      6,
      8,
      10
    ]
  }
};
export const design = "flat-washer";
