// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 6
};
export const parameterDomains = {
  "diameter": {
    "min": 3,
    "max": 10,
    "values": [
      3,
      4,
      5,
      6,
      8,
      10
    ]
  }
};
export const design = "flat-washer";
export const parameterCases = [
  {
    "name": "M3",
    "parameters": {
      "diameter": 3
    },
    "expectations": {
      "bounds": {
        "x": 7,
        "y": 7,
        "z": 0.5
      },
      "solids": 1,
      "volume": {
        "min": 15.220016406642548,
        "max": 15.222016406642547
      },
      "holes": [
        {
          "diameter": 3.2,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M4",
    "parameters": {
      "diameter": 4
    },
    "expectations": {
      "bounds": {
        "x": 9,
        "y": 9,
        "z": 0.8
      },
      "solids": 1,
      "volume": {
        "min": 39.2751913551796,
        "max": 39.277191355179596
      },
      "holes": [
        {
          "diameter": 4.3,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M5",
    "parameters": {
      "diameter": 5
    },
    "expectations": {
      "bounds": {
        "x": 10,
        "y": 10,
        "z": 1
      },
      "solids": 1,
      "volume": {
        "min": 56.47698192991051,
        "max": 56.4789819299105
      },
      "holes": [
        {
          "diameter": 5.3,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M6",
    "parameters": {
      "diameter": 6
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 1.6
      },
      "solids": 1,
      "volume": {
        "min": 129.4828828103569,
        "max": 129.4848828103569
      },
      "holes": [
        {
          "diameter": 6.4,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M8",
    "parameters": {
      "diameter": 8
    },
    "expectations": {
      "bounds": {
        "x": 16,
        "y": 16,
        "z": 1.6
      },
      "solids": 1,
      "volume": {
        "min": 233.0297766726765,
        "max": 233.0317766726765
      },
      "holes": [
        {
          "diameter": 8.4,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "M10",
    "parameters": {
      "diameter": 10
    },
    "expectations": {
      "bounds": {
        "x": 20,
        "y": 20,
        "z": 2
      },
      "solids": 1,
      "volume": {
        "min": 455.1372356888213,
        "max": 455.13923568882126
      },
      "holes": [
        {
          "diameter": 10.5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  }
];
