{
 "title": "Redis",
 "tags": [
  "tau",
  "redis"
 ],
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(up, service_name)" },
   {
    "name": "instance",
    "query": "label_values(up{service_name=~\"$service\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "server", "type": "command" }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "command": "info", "section": "clients", "type": "command" }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "command": "info", "section": "keyspace", "type": "command" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "memory", "type": "command" }
   ]
  },
  {
   "title": "Operations/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "stats", "type": "command" }
   ]
  },
  {
   "title": "Keyspace Hit Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(redis_keyspace_hits_total[5m])) / clamp_min(sum(rate(redis_keyspace_hits_total[5m])) + sum(rate(redis_keyspace_misses_total[5m])), 1e-10)"
    }
   ]
  },
  {
   "title": "Redis Connection State",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "redis_connection_state{service_name=~\"$service\"}",
     "legendFormat": "{{redis_role}}"
    }
   ]
  },
  {
   "title": "Slow Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "command": "slowlogGet", "type": "command" }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service_name=~\"$service\"} | detected_level=~\"error|fatal|critical\""
    }
   ]
  },
  {
   "title": "Recent Traces",
   "type": "traces",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "{resource.service.name=~\"$service\"}"
    }
   ]
  }
 ]
}