// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 16,
  "height": 8,
  "flangeDiameter": 22,
  "thickness": 1.5
};
export const parameterDomains = {
  "diameter": {
    "min": 12.8,
    "max": 19.2
  },
  "height": {
    "min": 6.4,
    "max": 9.6
  },
  "flangeDiameter": {
    "min": 17.6,
    "max": 26.4
  },
  "thickness": {
    "min": 1.2000000000000002,
    "max": 1.7999999999999998
  }
};
export const design = "panel-blanking-plug";
