// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 40,
  "height": 30,
  "length": 80,
  "wall": 3
};
export const parameterDomains = {
  "width": {
    "min": 36,
    "max": 44
  },
  "height": {
    "min": 27,
    "max": 33
  },
  "length": {
    "min": 72,
    "max": 88
  },
  "wall": {
    "min": 2.7,
    "max": 3.3000000000000003
  }
};
export const design = "rectangular-tube";
export const parameterCases = [
  {
    "name": "width 36",
    "parameters": {
      "width": 36
    },
    "expectations": {
      "bounds": {
        "x": 36,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 28222.36867899917,
        "max": 28278.869917595763
      }
    }
  },
  {
    "name": "width 44",
    "parameters": {
      "width": 44
    },
    "expectations": {
      "bounds": {
        "x": 44,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 32058.52867899917,
        "max": 32122.709917595763
      }
    }
  },
  {
    "name": "height 27",
    "parameters": {
      "height": 27
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 27,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 28701.88867899917,
        "max": 28759.349917595762
      }
    }
  },
  {
    "name": "height 33",
    "parameters": {
      "height": 33
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 33,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 31579.00867899917,
        "max": 31642.229917595763
      }
    }
  },
  {
    "name": "length 72",
    "parameters": {
      "length": 72
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 72
      },
      "solids": 1,
      "volume": {
        "min": 27126.403811099255,
        "max": 27180.710925836185
      }
    }
  },
  {
    "name": "length 88",
    "parameters": {
      "length": 88
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 88
      },
      "solids": 1,
      "volume": {
        "min": 33154.49354689909,
        "max": 33220.86890935534
      }
    }
  },
  {
    "name": "wall 2.7",
    "parameters": {
      "wall": 2.7
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 27434.73942998932,
        "max": 27489.663833252558
      }
    }
  },
  {
    "name": "wall 3.3000000000000003",
    "parameters": {
      "wall": 3.3000000000000003
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 32777.638901589,
        "max": 32843.25980029088
      }
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "width": 36,
      "height": 27,
      "length": 72,
      "wall": 2.7
    },
    "expectations": {
      "bounds": {
        "x": 36,
        "y": 27,
        "z": 72
      },
      "solids": 1,
      "volume": {
        "min": 21972.38708699039,
        "max": 22016.375849927306
      }
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "width": 44,
      "height": 33,
      "length": 88,
      "wall": 3.3000000000000003
    },
    "expectations": {
      "bounds": {
        "x": 44,
        "y": 33,
        "z": 88
      },
      "solids": 1,
      "volume": {
        "min": 40116.9371917479,
        "max": 40197.25138031996
      }
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "width": 36,
      "height": 27,
      "length": 72,
      "wall": 3.3000000000000003
    },
    "expectations": {
      "bounds": {
        "x": 36,
        "y": 27,
        "z": 72
      },
      "solids": 1,
      "volume": {
        "min": 26176.801411430104,
        "max": 26229.20742026179
      }
    }
  }
];
