// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Nylon-insert locknut", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 7
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 7
}, tolerance: 0.1 });
});
it("width-minimum", async () => {
const parameters = {
  "width": 8
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 7
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 7
}, tolerance: 0.1 });
});
it("width-maximum", async () => {
const parameters = {
  "width": 12
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 13.85640646055102,
  "y": 12,
  "z": 7
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 13.85640646055102,
  "y": 12,
  "z": 7
}, tolerance: 0.1 });
});
it("height-minimum", async () => {
const parameters = {
  "height": 5.6000000000000005
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 5.6000000000000005
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 5.6000000000000005
}, tolerance: 0.1 });
});
it("height-maximum", async () => {
const parameters = {
  "height": 8.4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 8.4
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 8.4
}, tolerance: 0.1 });
});
it("bore-minimum", async () => {
const parameters = {
  "bore": 4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 7
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 7
}, tolerance: 0.1 });
});
it("bore-maximum", async () => {
const parameters = {
  "bore": 6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 7
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 6,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.547005383792516,
  "y": 10,
  "z": 7
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "width": 8,
  "height": 5.6000000000000005,
  "bore": 4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 5.6000000000000005
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 5.6000000000000005
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "width": 12,
  "height": 8.4,
  "bore": 6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 13.85640646055102,
  "y": 12,
  "z": 8.4
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 6,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 13.85640646055102,
  "y": 12,
  "z": 8.4
}, tolerance: 0.1 });
});
it("thin-wall-corner", async () => {
const parameters = {
  "width": 8,
  "height": 7,
  "bore": 6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 7
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 6,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 7
}, tolerance: 0.1 });
});
});
