// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 10,
  "height": 7,
  "bore": 5
};
export const parameterDomains = {
  "width": {
    "min": 8,
    "max": 12
  },
  "height": {
    "min": 5.6000000000000005,
    "max": 8.4
  },
  "bore": {
    "min": 4,
    "max": 6
  }
};
export const design = "nylon-insert-locknut";
export const parameterCases = [
  {
    "name": "width-minimum",
    "parameters": {
      "width": 8
    },
    "expectations": {
      "bounds": {
        "x": 9.237604307034013,
        "y": 8,
        "z": 7
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "width-maximum",
    "parameters": {
      "width": 12
    },
    "expectations": {
      "bounds": {
        "x": 13.85640646055102,
        "y": 12,
        "z": 7
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "height-minimum",
    "parameters": {
      "height": 5.6000000000000005
    },
    "expectations": {
      "bounds": {
        "x": 11.547005383792516,
        "y": 10,
        "z": 5.6000000000000005
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "height-maximum",
    "parameters": {
      "height": 8.4
    },
    "expectations": {
      "bounds": {
        "x": 11.547005383792516,
        "y": 10,
        "z": 8.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore-minimum",
    "parameters": {
      "bore": 4
    },
    "expectations": {
      "bounds": {
        "x": 11.547005383792516,
        "y": 10,
        "z": 7
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 4,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore-maximum",
    "parameters": {
      "bore": 6
    },
    "expectations": {
      "bounds": {
        "x": 11.547005383792516,
        "y": 10,
        "z": 7
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "width": 8,
      "height": 5.6000000000000005,
      "bore": 4
    },
    "expectations": {
      "bounds": {
        "x": 9.237604307034013,
        "y": 8,
        "z": 5.6000000000000005
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 4,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "width": 12,
      "height": 8.4,
      "bore": 6
    },
    "expectations": {
      "bounds": {
        "x": 13.85640646055102,
        "y": 12,
        "z": 8.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "thin-wall-corner",
    "parameters": {
      "width": 8,
      "height": 7,
      "bore": 6
    },
    "expectations": {
      "bounds": {
        "x": 9.237604307034013,
        "y": 8,
        "z": 7
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  }
];
