// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 10,
  "height": 7,
  "bore": 5
};
export const parameterDomains = {
  "width": {
    "min": 8,
    "max": 12
  },
  "height": {
    "min": 5.6000000000000005,
    "max": 8.4
  },
  "bore": {
    "min": 4,
    "max": 6
  }
};
export const design = "nylon-insert-locknut";
