// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 6,
  "length": 20,
  "headDiameter": 10.5,
  "headHeight": 3.5,
  "socket": 3
};
export const parameterDomains = {
  "diameter": {
    "min": 4.800000000000001,
    "max": 7.199999999999999
  },
  "length": {
    "min": 16,
    "max": 24
  },
  "headDiameter": {
    "min": 8.4,
    "max": 12.6
  },
  "headHeight": {
    "min": 2.8000000000000003,
    "max": 4.2
  },
  "socket": {
    "min": 2.4000000000000004,
    "max": 3.5999999999999996
  }
};
export const design = "button-head-socket-screw";
export const parameterCases = [
  {
    "name": "diameter-minimum",
    "parameters": {
      "diameter": 4.800000000000001
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 23.5
      },
      "solids": 1
    }
  },
  {
    "name": "diameter-maximum",
    "parameters": {
      "diameter": 7.199999999999999
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 23.5
      },
      "solids": 1
    }
  },
  {
    "name": "length-minimum",
    "parameters": {
      "length": 16
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 19.5
      },
      "solids": 1
    }
  },
  {
    "name": "length-maximum",
    "parameters": {
      "length": 24
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 27.5
      },
      "solids": 1
    }
  },
  {
    "name": "headDiameter-minimum",
    "parameters": {
      "headDiameter": 8.4
    },
    "expectations": {
      "bounds": {
        "x": 8.4,
        "y": 8.4,
        "z": 23.5
      },
      "solids": 1
    }
  },
  {
    "name": "headDiameter-maximum",
    "parameters": {
      "headDiameter": 12.6
    },
    "expectations": {
      "bounds": {
        "x": 12.6,
        "y": 12.6,
        "z": 23.5
      },
      "solids": 1
    }
  },
  {
    "name": "headHeight-minimum",
    "parameters": {
      "headHeight": 2.8000000000000003
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 22.8
      },
      "solids": 1
    }
  },
  {
    "name": "headHeight-maximum",
    "parameters": {
      "headHeight": 4.2
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 24.2
      },
      "solids": 1
    }
  },
  {
    "name": "socket-minimum",
    "parameters": {
      "socket": 2.4000000000000004
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 23.5
      },
      "solids": 1
    }
  },
  {
    "name": "socket-maximum",
    "parameters": {
      "socket": 3.5999999999999996
    },
    "expectations": {
      "bounds": {
        "x": 10.5,
        "y": 10.5,
        "z": 23.5
      },
      "solids": 1
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "diameter": 4.800000000000001,
      "length": 16,
      "headDiameter": 8.4,
      "headHeight": 2.8000000000000003,
      "socket": 2.4000000000000004
    },
    "expectations": {
      "bounds": {
        "x": 8.4,
        "y": 8.4,
        "z": 18.8
      },
      "solids": 1
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "diameter": 7.199999999999999,
      "length": 24,
      "headDiameter": 12.6,
      "headHeight": 4.2,
      "socket": 3.5999999999999996
    },
    "expectations": {
      "bounds": {
        "x": 12.6,
        "y": 12.6,
        "z": 28.2
      },
      "solids": 1
    }
  }
];
