// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 10,
  "height": 8,
  "bore": 5
};
export const parameterDomains = {
  "width": {
    "min": 8,
    "max": 12
  },
  "height": {
    "min": 6.4,
    "max": 9.6
  },
  "bore": {
    "min": 4,
    "max": 6
  }
};
export const design = "wing-nut";
export const parameterCases = [
  {
    "name": "width-minimum",
    "parameters": {
      "width": 8
    },
    "expectations": {
      "bounds": {
        "x": 20.8,
        "y": 8,
        "z": 8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "width-maximum",
    "parameters": {
      "width": 12
    },
    "expectations": {
      "bounds": {
        "x": 31.200000000000003,
        "y": 12,
        "z": 8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "height-minimum",
    "parameters": {
      "height": 6.4
    },
    "expectations": {
      "bounds": {
        "x": 26,
        "y": 10,
        "z": 6.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "height-maximum",
    "parameters": {
      "height": 9.6
    },
    "expectations": {
      "bounds": {
        "x": 26,
        "y": 10,
        "z": 9.6
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore-minimum",
    "parameters": {
      "bore": 4
    },
    "expectations": {
      "bounds": {
        "x": 26,
        "y": 10,
        "z": 8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 4,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore-maximum",
    "parameters": {
      "bore": 6
    },
    "expectations": {
      "bounds": {
        "x": 26,
        "y": 10,
        "z": 8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "width": 8,
      "height": 6.4,
      "bore": 4
    },
    "expectations": {
      "bounds": {
        "x": 20.8,
        "y": 8,
        "z": 6.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 4,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "width": 12,
      "height": 9.6,
      "bore": 6
    },
    "expectations": {
      "bounds": {
        "x": 31.200000000000003,
        "y": 12,
        "z": 9.6
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "thin-wall-corner",
    "parameters": {
      "width": 8,
      "height": 8,
      "bore": 6
    },
    "expectations": {
      "bounds": {
        "x": 20.8,
        "y": 8,
        "z": 8
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 6,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  }
];
