// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 40,
  "height": 30,
  "length": 80,
  "radius": 1
};
export const parameterDomains = {
  "width": {
    "min": 36,
    "max": 44
  },
  "height": {
    "min": 27,
    "max": 33
  },
  "length": {
    "min": 72,
    "max": 88
  },
  "radius": {
    "min": 0.9,
    "max": 1.1
  }
};
export const design = "square-bar";
export const parameterCases = [
  {
    "name": "width 36",
    "parameters": {
      "width": 36
    },
    "expectations": {
      "bounds": {
        "x": 36,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 86244.9960848749,
        "max": 86417.65873969947
      }
    }
  },
  {
    "name": "width 44",
    "parameters": {
      "width": 44
    },
    "expectations": {
      "bounds": {
        "x": 44,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 105425.7960848749,
        "max": 105636.85873969947
      }
    }
  },
  {
    "name": "height 27",
    "parameters": {
      "height": 27
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 27,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 86244.9960848749,
        "max": 86417.65873969947
      }
    }
  },
  {
    "name": "height 33",
    "parameters": {
      "height": 33
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 33,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 105425.7960848749,
        "max": 105636.85873969947
      }
    }
  },
  {
    "name": "length 72",
    "parameters": {
      "length": 72
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 72
      },
      "solids": 1,
      "volume": {
        "min": 86251.85647638742,
        "max": 86424.53286572952
      }
    }
  },
  {
    "name": "length 88",
    "parameters": {
      "length": 88
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 88
      },
      "solids": 1,
      "volume": {
        "min": 105418.9356933624,
        "max": 105629.98461366943
      }
    }
  },
  {
    "name": "radius 0.9",
    "parameters": {
      "radius": 0.9
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 95848.43082874868,
        "max": 96040.31957915657
      }
    }
  },
  {
    "name": "radius 1.1",
    "parameters": {
      "radius": 1.1
    },
    "expectations": {
      "bounds": {
        "x": 40,
        "y": 30,
        "z": 80
      },
      "solids": 1,
      "volume": {
        "min": 95820.98926269863,
        "max": 96012.82307503636
      }
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "width": 36,
      "height": 27,
      "length": 72,
      "radius": 0.9
    },
    "expectations": {
      "bounds": {
        "x": 36,
        "y": 27,
        "z": 72
      },
      "solids": 1,
      "volume": {
        "min": 69864.00374587381,
        "max": 70003.87162124092
      }
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "width": 44,
      "height": 33,
      "length": 88,
      "radius": 1.1
    },
    "expectations": {
      "bounds": {
        "x": 44,
        "y": 33,
        "z": 88
      },
      "solids": 1,
      "volume": {
        "min": 127556.9121889685,
        "max": 127812.28138254
      }
    }
  }
];
