// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 80,
  "depth": 50,
  "height": 25,
  "wall": 2
};
export const parameterDomains = {
  "width": {
    "min": 64,
    "max": 96
  },
  "depth": {
    "min": 40,
    "max": 60
  },
  "height": {
    "min": 20,
    "max": 30
  },
  "wall": {
    "min": 1.6,
    "max": 2.4
  }
};
export const design = "enclosure-base";
