// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 80,
  "depth": 60,
  "height": 4,
  "hole": 5
};
export const parameterDomains = {
  "width": {
    "min": 72,
    "max": 88
  },
  "depth": {
    "min": 54,
    "max": 66
  },
  "height": {
    "min": 3.6,
    "max": 4.4
  },
  "hole": {
    "min": 4.5,
    "max": 5.5
  }
};
export const design = "gusset-plate";
export const parameterCases = [
  {
    "name": "width 72",
    "parameters": {
      "width": 72
    },
    "expectations": {
      "bounds": {
        "x": 69.65060008642489,
        "y": 58.486611183131856,
        "z": 4
      },
      "solids": 1
    }
  },
  {
    "name": "width 88",
    "parameters": {
      "width": 88
    },
    "expectations": {
      "bounds": {
        "x": 85.01092854120989,
        "y": 58.81048158112796,
        "z": 4
      },
      "solids": 1
    }
  },
  {
    "name": "depth 54",
    "parameters": {
      "depth": 54
    },
    "expectations": {
      "bounds": {
        "x": 76.97482893589854,
        "y": 52.82467619839818,
        "z": 4
      },
      "solids": 1
    }
  },
  {
    "name": "depth 66",
    "parameters": {
      "depth": 66
    },
    "expectations": {
      "bounds": {
        "x": 77.62199722626842,
        "y": 64.50481437833811,
        "z": 4
      },
      "solids": 1
    }
  },
  {
    "name": "height 3.6",
    "parameters": {
      "height": 3.6
    },
    "expectations": {
      "bounds": {
        "x": 77.6,
        "y": 58.8,
        "z": 3.6
      },
      "solids": 1
    }
  },
  {
    "name": "height 4.4",
    "parameters": {
      "height": 4.4
    },
    "expectations": {
      "bounds": {
        "x": 77.06666666666666,
        "y": 58.53333333333333,
        "z": 4.4
      },
      "solids": 1
    }
  },
  {
    "name": "hole 4.5",
    "parameters": {
      "hole": 4.5
    },
    "expectations": {
      "bounds": {
        "x": 77.33333333333333,
        "y": 58.666666666666664,
        "z": 4
      },
      "solids": 1
    }
  },
  {
    "name": "hole 5.5",
    "parameters": {
      "hole": 5.5
    },
    "expectations": {
      "bounds": {
        "x": 77.33333333333333,
        "y": 58.666666666666664,
        "z": 4
      },
      "solids": 1
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "width": 72,
      "depth": 54,
      "height": 3.6,
      "hole": 4.5
    },
    "expectations": {
      "bounds": {
        "x": 69.6,
        "y": 52.8,
        "z": 3.6
      },
      "solids": 1
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "width": 88,
      "depth": 66,
      "height": 4.4,
      "hole": 5.5
    },
    "expectations": {
      "bounds": {
        "x": 85.06666666666666,
        "y": 64.53333333333333,
        "z": 4.4
      },
      "solids": 1
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "width": 72,
      "depth": 54,
      "height": 3.6,
      "hole": 5.5
    },
    "expectations": {
      "bounds": {
        "x": 69.6,
        "y": 52.8,
        "z": 3.6
      },
      "solids": 1
    }
  }
];
