// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Eye bolt", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 43.2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 14,
  "center": {
    "x": 0,
    "y": 0,
    "z": 31.2
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 43.2
}, tolerance: 0.1 });
});
it("diameter-minimum", async () => {
const parameters = {
  "diameter": 4.800000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 4.800000000000001,
  "z": 43.2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 14,
  "center": {
    "x": 0,
    "y": 0,
    "z": 31.2
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 4.800000000000001,
  "z": 43.2
}, tolerance: 0.1 });
});
it("diameter-maximum", async () => {
const parameters = {
  "diameter": 7.199999999999999
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 7.199999999999999,
  "z": 43.2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 14,
  "center": {
    "x": 0,
    "y": 0,
    "z": 31.2
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 7.199999999999999,
  "z": 43.2
}, tolerance: 0.1 });
});
it("length-minimum", async () => {
const parameters = {
  "length": 19.200000000000003
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 38.400000000000006
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 14,
  "center": {
    "x": 0,
    "y": 0,
    "z": 26.400000000000002
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 38.400000000000006
}, tolerance: 0.1 });
});
it("length-maximum", async () => {
const parameters = {
  "length": 28.799999999999997
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 48
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 14,
  "center": {
    "x": 0,
    "y": 0,
    "z": 36
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 48
}, tolerance: 0.1 });
});
it("headDiameter-minimum", async () => {
const parameters = {
  "headDiameter": 19.200000000000003
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 19.200000000000003,
  "y": 6,
  "z": 39.36
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 14,
  "center": {
    "x": 0,
    "y": 0,
    "z": 29.76
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 19.200000000000003,
  "y": 6,
  "z": 39.36
}, tolerance: 0.1 });
});
it("headDiameter-maximum", async () => {
const parameters = {
  "headDiameter": 28.799999999999997
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 28.799999999999997,
  "y": 6,
  "z": 47.04
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 14,
  "center": {
    "x": 0,
    "y": 0,
    "z": 32.64
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 28.799999999999997,
  "y": 6,
  "z": 47.04
}, tolerance: 0.1 });
});
it("bore-minimum", async () => {
const parameters = {
  "bore": 11.200000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 43.2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 11.200000000000001,
  "center": {
    "x": 0,
    "y": 0,
    "z": 31.2
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 43.2
}, tolerance: 0.1 });
});
it("bore-maximum", async () => {
const parameters = {
  "bore": 16.8
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 43.2
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 16.8,
  "center": {
    "x": 0,
    "y": 0,
    "z": 31.2
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 24,
  "y": 6,
  "z": 43.2
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "diameter": 4.800000000000001,
  "length": 19.200000000000003,
  "headDiameter": 19.200000000000003,
  "bore": 11.200000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 19.200000000000003,
  "y": 4.800000000000001,
  "z": 34.56
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 11.200000000000001,
  "center": {
    "x": 0,
    "y": 0,
    "z": 24.960000000000004
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 19.200000000000003,
  "y": 4.800000000000001,
  "z": 34.56
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "diameter": 7.199999999999999,
  "length": 28.799999999999997,
  "headDiameter": 28.799999999999997,
  "bore": 16.8
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 28.799999999999997,
  "y": 7.199999999999999,
  "z": 51.839999999999996
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 16.8,
  "center": {
    "x": 0,
    "y": 0,
    "z": 37.44
  },
  "axis": "y",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 28.799999999999997,
  "y": 7.199999999999999,
  "z": 51.839999999999996
}, tolerance: 0.1 });
});
});
