// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("DIN-rail style mounting clip", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 8
}, tolerance: 0.1 });
});
it("width-minimum", async () => {
const parameters = {
  "width": 28
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 28,
  "y": 20,
  "z": 8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 28,
  "y": 20,
  "z": 8
}, tolerance: 0.1 });
});
it("width-maximum", async () => {
const parameters = {
  "width": 42
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 42,
  "y": 20,
  "z": 8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 42,
  "y": 20,
  "z": 8
}, tolerance: 0.1 });
});
it("depth-minimum", async () => {
const parameters = {
  "depth": 16
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 16,
  "z": 8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 16,
  "z": 8
}, tolerance: 0.1 });
});
it("depth-maximum", async () => {
const parameters = {
  "depth": 24
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 24,
  "z": 8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 24,
  "z": 8
}, tolerance: 0.1 });
});
it("height-minimum", async () => {
const parameters = {
  "height": 6.4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 6.4
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 6.4
}, tolerance: 0.1 });
});
it("height-maximum", async () => {
const parameters = {
  "height": 9.6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 9.6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 9.6
}, tolerance: 0.1 });
});
it("wall-minimum", async () => {
const parameters = {
  "wall": 1.6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 8
}, tolerance: 0.1 });
});
it("wall-maximum", async () => {
const parameters = {
  "wall": 2.4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 35,
  "y": 20,
  "z": 8
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "width": 28,
  "depth": 16,
  "height": 6.4,
  "wall": 1.6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 28,
  "y": 16,
  "z": 6.4
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 28,
  "y": 16,
  "z": 6.4
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "width": 42,
  "depth": 24,
  "height": 9.6,
  "wall": 2.4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 42,
  "y": 24,
  "z": 9.6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 42,
  "y": 24,
  "z": 9.6
}, tolerance: 0.1 });
});
});
