// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 35,
  "depth": 20,
  "height": 8,
  "wall": 2
};
export const parameterDomains = {
  "width": {
    "min": 28,
    "max": 42
  },
  "depth": {
    "min": 16,
    "max": 24
  },
  "height": {
    "min": 6.4,
    "max": 9.6
  },
  "wall": {
    "min": 1.6,
    "max": 2.4
  }
};
export const design = "din-rail-clip";
export const parameterCases = [
  {
    "name": "width-minimum",
    "parameters": {
      "width": 28
    },
    "expectations": {
      "bounds": {
        "x": 28,
        "y": 20,
        "z": 8
      },
      "solids": 1
    }
  },
  {
    "name": "width-maximum",
    "parameters": {
      "width": 42
    },
    "expectations": {
      "bounds": {
        "x": 42,
        "y": 20,
        "z": 8
      },
      "solids": 1
    }
  },
  {
    "name": "depth-minimum",
    "parameters": {
      "depth": 16
    },
    "expectations": {
      "bounds": {
        "x": 35,
        "y": 16,
        "z": 8
      },
      "solids": 1
    }
  },
  {
    "name": "depth-maximum",
    "parameters": {
      "depth": 24
    },
    "expectations": {
      "bounds": {
        "x": 35,
        "y": 24,
        "z": 8
      },
      "solids": 1
    }
  },
  {
    "name": "height-minimum",
    "parameters": {
      "height": 6.4
    },
    "expectations": {
      "bounds": {
        "x": 35,
        "y": 20,
        "z": 6.4
      },
      "solids": 1
    }
  },
  {
    "name": "height-maximum",
    "parameters": {
      "height": 9.6
    },
    "expectations": {
      "bounds": {
        "x": 35,
        "y": 20,
        "z": 9.6
      },
      "solids": 1
    }
  },
  {
    "name": "wall-minimum",
    "parameters": {
      "wall": 1.6
    },
    "expectations": {
      "bounds": {
        "x": 35,
        "y": 20,
        "z": 8
      },
      "solids": 1
    }
  },
  {
    "name": "wall-maximum",
    "parameters": {
      "wall": 2.4
    },
    "expectations": {
      "bounds": {
        "x": 35,
        "y": 20,
        "z": 8
      },
      "solids": 1
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "width": 28,
      "depth": 16,
      "height": 6.4,
      "wall": 1.6
    },
    "expectations": {
      "bounds": {
        "x": 28,
        "y": 16,
        "z": 6.4
      },
      "solids": 1
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "width": 42,
      "depth": 24,
      "height": 9.6,
      "wall": 2.4
    },
    "expectations": {
      "bounds": {
        "x": 42,
        "y": 24,
        "z": 9.6
      },
      "solids": 1
    }
  }
];
