// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 35,
  "depth": 20,
  "height": 8,
  "wall": 2
};
export const parameterDomains = {
  "width": {
    "min": 28,
    "max": 42
  },
  "depth": {
    "min": 16,
    "max": 24
  },
  "height": {
    "min": 6.4,
    "max": 9.6
  },
  "wall": {
    "min": 1.6,
    "max": 2.4
  }
};
export const design = "din-rail-clip";
