// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 30,
  "length": 80,
  "wall": 3
};
export const parameterDomains = {
  "width": {
    "min": 27,
    "max": 33
  },
  "length": {
    "min": 72,
    "max": 88
  },
  "wall": {
    "min": 2.7,
    "max": 3.3000000000000003
  }
};
export const design = "t-slot-extrusion";
export const parameterCases = [
  {
    "name": "width 27",
    "parameters": {
      "width": 27
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 27,
        "z": 80
      },
      "solids": 1
    }
  },
  {
    "name": "width 33",
    "parameters": {
      "width": 33
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 33,
        "z": 80
      },
      "solids": 1
    }
  },
  {
    "name": "length 72",
    "parameters": {
      "length": 72
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 30,
        "z": 72
      },
      "solids": 1
    }
  },
  {
    "name": "length 88",
    "parameters": {
      "length": 88
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 30,
        "z": 88
      },
      "solids": 1
    }
  },
  {
    "name": "wall 2.7",
    "parameters": {
      "wall": 2.7
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 30,
        "z": 80
      },
      "solids": 1
    }
  },
  {
    "name": "wall 3.3000000000000003",
    "parameters": {
      "wall": 3.3000000000000003
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 30,
        "z": 80
      },
      "solids": 1
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "width": 27,
      "length": 72,
      "wall": 2.7
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 27,
        "z": 72
      },
      "solids": 1
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "width": 33,
      "length": 88,
      "wall": 3.3000000000000003
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 33,
        "z": 88
      },
      "solids": 1
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "width": 27,
      "length": 72,
      "wall": 3.3000000000000003
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 27,
        "z": 72
      },
      "solids": 1
    }
  }
];
