// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 16,
  "bore": 6,
  "thickness": 1
};
export const parameterDomains = {
  "diameter": {
    "min": 12.8,
    "max": 19.2
  },
  "bore": {
    "min": 4.800000000000001,
    "max": 7.199999999999999
  },
  "thickness": {
    "min": 0.8,
    "max": 1.2
  }
};
export const design = "internal-tooth-lock-washer";
export const parameterCases = [
  {
    "name": "diameter-minimum",
    "parameters": {
      "diameter": 12.8
    },
    "expectations": {
      "bounds": {
        "x": 12.8,
        "y": 12.8,
        "z": 1
      },
      "solids": 1
    }
  },
  {
    "name": "diameter-maximum",
    "parameters": {
      "diameter": 19.2
    },
    "expectations": {
      "bounds": {
        "x": 19.2,
        "y": 19.2,
        "z": 1
      },
      "solids": 1
    }
  },
  {
    "name": "bore-minimum",
    "parameters": {
      "bore": 4.800000000000001
    },
    "expectations": {
      "bounds": {
        "x": 16,
        "y": 16,
        "z": 1
      },
      "solids": 1
    }
  },
  {
    "name": "bore-maximum",
    "parameters": {
      "bore": 7.199999999999999
    },
    "expectations": {
      "bounds": {
        "x": 16,
        "y": 16,
        "z": 1
      },
      "solids": 1
    }
  },
  {
    "name": "thickness-minimum",
    "parameters": {
      "thickness": 0.8
    },
    "expectations": {
      "bounds": {
        "x": 16,
        "y": 16,
        "z": 0.8
      },
      "solids": 1
    }
  },
  {
    "name": "thickness-maximum",
    "parameters": {
      "thickness": 1.2
    },
    "expectations": {
      "bounds": {
        "x": 16,
        "y": 16,
        "z": 1.2
      },
      "solids": 1
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "diameter": 12.8,
      "bore": 4.800000000000001,
      "thickness": 0.8
    },
    "expectations": {
      "bounds": {
        "x": 12.8,
        "y": 12.8,
        "z": 0.8
      },
      "solids": 1
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "diameter": 19.2,
      "bore": 7.199999999999999,
      "thickness": 1.2
    },
    "expectations": {
      "bounds": {
        "x": 19.2,
        "y": 19.2,
        "z": 1.2
      },
      "solids": 1
    }
  },
  {
    "name": "thin-wall-corner",
    "parameters": {
      "diameter": 12.8,
      "bore": 7.199999999999999,
      "thickness": 1
    },
    "expectations": {
      "bounds": {
        "x": 12.8,
        "y": 12.8,
        "z": 1
      },
      "solids": 1
    }
  }
];
