// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 6,
  "length": 24,
  "headDiameter": 12,
  "headHeight": 3,
  "socket": 4
};
export const parameterDomains = {
  "diameter": {
    "min": 4.800000000000001,
    "max": 7.199999999999999
  },
  "length": {
    "min": 19.200000000000003,
    "max": 28.799999999999997
  },
  "headDiameter": {
    "min": 9.600000000000001,
    "max": 14.399999999999999
  },
  "headHeight": {
    "min": 2.4000000000000004,
    "max": 3.5999999999999996
  },
  "socket": {
    "min": 3.2,
    "max": 4.8
  }
};
export const design = "countersunk-socket-screw";
export const parameterCases = [
  {
    "name": "diameter-minimum",
    "parameters": {
      "diameter": 4.800000000000001
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "diameter-maximum",
    "parameters": {
      "diameter": 7.199999999999999
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "length-minimum",
    "parameters": {
      "length": 19.200000000000003
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 19.200000000000003
      },
      "solids": 1
    }
  },
  {
    "name": "length-maximum",
    "parameters": {
      "length": 28.799999999999997
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 28.799999999999997
      },
      "solids": 1
    }
  },
  {
    "name": "headDiameter-minimum",
    "parameters": {
      "headDiameter": 9.600000000000001
    },
    "expectations": {
      "bounds": {
        "x": 9.600000000000001,
        "y": 9.600000000000001,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "headDiameter-maximum",
    "parameters": {
      "headDiameter": 14.399999999999999
    },
    "expectations": {
      "bounds": {
        "x": 14.399999999999999,
        "y": 14.399999999999999,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "headHeight-minimum",
    "parameters": {
      "headHeight": 2.4000000000000004
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "headHeight-maximum",
    "parameters": {
      "headHeight": 3.5999999999999996
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "socket-minimum",
    "parameters": {
      "socket": 3.2
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "socket-maximum",
    "parameters": {
      "socket": 4.8
    },
    "expectations": {
      "bounds": {
        "x": 12,
        "y": 12,
        "z": 24
      },
      "solids": 1
    }
  },
  {
    "name": "combined-min",
    "parameters": {
      "diameter": 4.800000000000001,
      "length": 19.200000000000003,
      "headDiameter": 9.600000000000001,
      "headHeight": 2.4000000000000004,
      "socket": 3.2
    },
    "expectations": {
      "bounds": {
        "x": 9.600000000000001,
        "y": 9.600000000000001,
        "z": 19.200000000000003
      },
      "solids": 1
    }
  },
  {
    "name": "combined-max",
    "parameters": {
      "diameter": 7.199999999999999,
      "length": 28.799999999999997,
      "headDiameter": 14.399999999999999,
      "headHeight": 3.5999999999999996,
      "socket": 4.8
    },
    "expectations": {
      "bounds": {
        "x": 14.399999999999999,
        "y": 14.399999999999999,
        "z": 28.799999999999997
      },
      "solids": 1
    }
  }
];
