import { defineConfig } from 'tsdown';
import type { Options } from 'tsdown';

const baseConfig: Options = {
  entry: [
    'src/index.ts',
    'src/client/index.ts',
    'src/types/index.ts',
    'src/plugins/presets.ts',
    'src/plugins/kernel-plugin-entry.ts',
    'src/plugins/kernels-entry.ts',
    'src/plugins/middleware-entry.ts',
    'src/plugins/bundler-entry.ts',
    'src/plugins/transcoder-entry.ts',
    'src/runner/index.ts',
    'src/transport/index.ts',
    'src/transport/in-process.ts',
    'src/transport/web.ts',
    'src/transport/node.ts',
    'src/electron/main.ts',
    'src/electron/preload.ts',
    'src/electron/renderer.ts',
    'src/electron/utility.ts',
    'src/host/index.ts',
    'src/node.ts',
    'src/filesystem/index.ts',
    'src/filesystem/from-node-fs.ts',
    'src/filesystem/from-browser-fs.ts',
    'src/testing/index.ts',
    'src/framework/kernel-runtime-worker.ts',
    'src/worker/index.ts',
    'src/worker/web.ts',
    'src/worker/node.ts',
    'src/worker-internals.ts',
    'src/transport-internals.ts',
    'src/kernels/replicad/replicad.kernel.ts',
    'src/kernels/replicad/replicad-wasm-single-loader.ts',
    'src/kernels/replicad/replicad-wasm-multi-loader.ts',
    'src/kernels/jscad/jscad.kernel.ts',
    'src/kernels/manifold/manifold.kernel.ts',
    'src/kernels/opencascade/opencascade.kernel.ts',
    'src/kernels/zoo/zoo.kernel.ts',
    'src/kernels/zoo/engine-connection.ts',
    'src/kernels/tau/tau.kernel.ts',
    'src/bundler/esbuild.bundler.ts',
    'src/middleware/runtime-middleware.ts',
    'src/middleware/parameter-cache.middleware.ts',
    'src/middleware/geometry-cache.middleware.ts',
    'src/middleware/gltf-coordinate-transform.middleware.ts',
    'src/middleware/gltf-edge-detection.middleware.ts',
    'src/cross-origin-isolation/index.ts',
    'src/cross-origin-isolation/express.ts',
    'src/react-router/index.ts',
    'src/vite/index.ts',
    'src/rolldown/index.ts',
    'src/nextjs/index.ts',
    'src/nextjs/config.ts',
    'src/utils/package-info.ts',
  ],
  sourcemap: false,
  clean: ['dist'],
  dts: true,
  minify: true,
  copy: (options) => [
    {
      from: 'src/kernels/replicad/fonts',
      to: `${options.outDir}/kernels/replicad/fonts`,
    },
    {
      from: 'src/kernels/replicad/wasm',
      to: `${options.outDir}/kernels/replicad/wasm`,
    },
    {
      from: 'src/kernels/zoo/wasm',
      to: `${options.outDir}/kernels/zoo/wasm`,
    },
    {
      from: 'src/kernels/manifold/wasm',
      to: `${options.outDir}/kernels/manifold/wasm`,
    },
    {
      from: 'src/kernels/opencascade/wasm',
      to: `${options.outDir}/kernels/opencascade/wasm`,
    },
  ],
  tsconfig: 'tsconfig.build.json',
  unbundle: true,
};

const esmConfig: Options = {
  ...baseConfig,
  format: 'esm',
  outDir: 'dist/esm',
};

export default defineConfig(esmConfig);
