// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Slotted threaded stud", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 8,
  "y": 8,
  "z": 40
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 8,
  "y": 8,
  "z": 40
}, tolerance: 0.1 });
});
it("diameter-minimum", async () => {
const parameters = {
  "diameter": 6.4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 6.4,
  "y": 6.4,
  "z": 40
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 6.4,
  "y": 6.4,
  "z": 40
}, tolerance: 0.1 });
});
it("diameter-maximum", async () => {
const parameters = {
  "diameter": 9.6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.6,
  "y": 9.6,
  "z": 40
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.6,
  "y": 9.6,
  "z": 40
}, tolerance: 0.1 });
});
it("length-minimum", async () => {
const parameters = {
  "length": 32
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 8,
  "y": 8,
  "z": 32
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 8,
  "y": 8,
  "z": 32
}, tolerance: 0.1 });
});
it("length-maximum", async () => {
const parameters = {
  "length": 48
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 8,
  "y": 8,
  "z": 48
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 8,
  "y": 8,
  "z": 48
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "diameter": 6.4,
  "length": 32
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 6.4,
  "y": 6.4,
  "z": 32
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 6.4,
  "y": 6.4,
  "z": 32
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "diameter": 9.6,
  "length": 48
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.6,
  "y": 9.6,
  "z": 48
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.6,
  "y": 9.6,
  "z": 48
}, tolerance: 0.1 });
});
});
