// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 30,
  "bore": 12,
  "length": 60
};
export const parameterDomains = {
  "diameter": {
    "min": 27,
    "max": 33
  },
  "bore": {
    "min": 10.8,
    "max": 13.200000000000001
  },
  "length": {
    "min": 54,
    "max": 66
  }
};
export const design = "concentric-reducer";
