/* oxlint-disable prettier/prettier, eslint/no-restricted-imports -- Auto-generated Vite asset imports. */
/* eslint-disable @typescript-eslint/naming-convention -- Generated keys are fixture paths. */
// AUTO-GENERATED by scripts/generate-thumbnails.mts — DO NOT EDIT.
// Run `pnpm nx generate-thumbnails tau-examples` to regenerate.

import thumbnail0 from './kernels/jscad/cube/thumbnail.webp?url';
import thumbnail1 from './kernels/jscad/cube-cylinder-section-fixture/thumbnail.webp?url';
import thumbnail2 from './kernels/jscad/cylinder/thumbnail.webp?url';
import thumbnail3 from './kernels/jscad/edge-occlusion-fixture/thumbnail.webp?url';
import thumbnail4 from './kernels/jscad/gear/thumbnail.webp?url';
import thumbnail5 from './kernels/jscad/non-manifold-section-fixture/thumbnail.webp?url';
import thumbnail6 from './kernels/jscad/section-cap-fixture/thumbnail.webp?url';
import thumbnail7 from './kernels/jscad/section-overlap-fixture/thumbnail.webp?url';
import thumbnail8 from './kernels/jscad/section-overlap-heavy-planetary-fixture/thumbnail.webp?url';
import thumbnail9 from './kernels/jscad/section-overlap-heavy-v8-fixture/thumbnail.webp?url';
import thumbnail10 from './kernels/jscad/section-picking-fixture/thumbnail.webp?url';
import thumbnail11 from './kernels/manifold/manifold-logo/thumbnail.webp?url';
import thumbnail12 from './kernels/opencascade/v8-engine-brep/thumbnail.webp?url';
import thumbnail13 from './kernels/openscad/kitchen-sink/thumbnail.webp?url';
import thumbnail14 from './kernels/replicad/bambu-plate/thumbnail.webp?url';
import thumbnail15 from './kernels/replicad/birdhouse/thumbnail.webp?url';
import thumbnail16 from './kernels/replicad/bottle/thumbnail.webp?url';
import thumbnail17 from './kernels/replicad/bundler-feature-matrix/thumbnail.webp?url';
import thumbnail18 from './kernels/replicad/card-holder/thumbnail.webp?url';
import thumbnail19 from './kernels/replicad/chair/thumbnail.webp?url';
import thumbnail20 from './kernels/replicad/copper-lampshade/thumbnail.webp?url';
import thumbnail21 from './kernels/replicad/cycloidal-gear/thumbnail.webp?url';
import thumbnail22 from './kernels/replicad/decorated-box/thumbnail.webp?url';
import thumbnail23 from './kernels/replicad/drinking-glass/thumbnail.webp?url';
import thumbnail24 from './kernels/replicad/flower-attachment-section-outline-fixture/thumbnail.webp?url';
import thumbnail25 from './kernels/replicad/gridfinity-box/thumbnail.webp?url';
import thumbnail26 from './kernels/replicad/helical-gear/thumbnail.webp?url';
import thumbnail27 from './kernels/replicad/hex-screwdriver/thumbnail.webp?url';
import thumbnail28 from './kernels/replicad/hollow-box/thumbnail.webp?url';
import thumbnail29 from './kernels/replicad/ibeam/thumbnail.webp?url';
import thumbnail30 from './kernels/replicad/jscad-logo/thumbnail.webp?url';
import thumbnail31 from './kernels/replicad/lego/thumbnail.webp?url';
import thumbnail32 from './kernels/replicad/libassimp-format-prism/thumbnail.webp?url';
import thumbnail33 from './kernels/replicad/logo/thumbnail.webp?url';
import thumbnail34 from './kernels/replicad/logo-keychain/thumbnail.webp?url';
import thumbnail35 from './kernels/replicad/nanoraster-logo/thumbnail.webp?url';
import thumbnail36 from './kernels/replicad/picovoxel-logo/thumbnail.webp?url';
import thumbnail37 from './kernels/replicad/planetary-gear-system/thumbnail.webp?url';
import thumbnail38 from './kernels/replicad/pot-plant/thumbnail.webp?url';
import thumbnail39 from './kernels/replicad/projection-test/thumbnail.webp?url';
import thumbnail40 from './kernels/replicad/rao-nozzle/thumbnail.webp?url';
import thumbnail41 from './kernels/replicad/replicad-logo/thumbnail.webp?url';
import thumbnail42 from './kernels/replicad/simple-tray/thumbnail.webp?url';
import thumbnail43 from './kernels/replicad/six-axis-arm/thumbnail.webp?url';
import thumbnail44 from './kernels/replicad/staircase/thumbnail.webp?url';
import thumbnail45 from './kernels/replicad/stress-test/thumbnail.webp?url';
import thumbnail46 from './kernels/replicad/t-slot-rail/thumbnail.webp?url';
import thumbnail47 from './kernels/replicad/table/thumbnail.webp?url';
import thumbnail48 from './kernels/replicad/tau-wordmark/thumbnail.webp?url';
import thumbnail49 from './kernels/replicad/tray/thumbnail.webp?url';
import thumbnail50 from './kernels/replicad/turbofan/thumbnail.webp?url';
import thumbnail51 from './kernels/replicad/v8-engine/thumbnail.webp?url';
import thumbnail52 from './kernels/replicad/vase/thumbnail.webp?url';
import thumbnail53 from './kernels/replicad/wavy-vase/thumbnail.webp?url';
import thumbnail54 from './kernels/replicad/wedge-door-stopper/thumbnail.webp?url';
import thumbnail55 from './kernels/replicad/worm-gear-system/thumbnail.webp?url';

/** Static thumbnail URLs keyed by `<kernel>/<example>`. @public */
export const thumbnailAssets = {
  'jscad/cube': thumbnail0,
  'jscad/cube-cylinder-section-fixture': thumbnail1,
  'jscad/cylinder': thumbnail2,
  'jscad/edge-occlusion-fixture': thumbnail3,
  'jscad/gear': thumbnail4,
  'jscad/non-manifold-section-fixture': thumbnail5,
  'jscad/section-cap-fixture': thumbnail6,
  'jscad/section-overlap-fixture': thumbnail7,
  'jscad/section-overlap-heavy-planetary-fixture': thumbnail8,
  'jscad/section-overlap-heavy-v8-fixture': thumbnail9,
  'jscad/section-picking-fixture': thumbnail10,
  'manifold/manifold-logo': thumbnail11,
  'opencascade/v8-engine-brep': thumbnail12,
  'openscad/kitchen-sink': thumbnail13,
  'replicad/bambu-plate': thumbnail14,
  'replicad/birdhouse': thumbnail15,
  'replicad/bottle': thumbnail16,
  'replicad/bundler-feature-matrix': thumbnail17,
  'replicad/card-holder': thumbnail18,
  'replicad/chair': thumbnail19,
  'replicad/copper-lampshade': thumbnail20,
  'replicad/cycloidal-gear': thumbnail21,
  'replicad/decorated-box': thumbnail22,
  'replicad/drinking-glass': thumbnail23,
  'replicad/flower-attachment-section-outline-fixture': thumbnail24,
  'replicad/gridfinity-box': thumbnail25,
  'replicad/helical-gear': thumbnail26,
  'replicad/hex-screwdriver': thumbnail27,
  'replicad/hollow-box': thumbnail28,
  'replicad/ibeam': thumbnail29,
  'replicad/jscad-logo': thumbnail30,
  'replicad/lego': thumbnail31,
  'replicad/libassimp-format-prism': thumbnail32,
  'replicad/logo': thumbnail33,
  'replicad/logo-keychain': thumbnail34,
  'replicad/nanoraster-logo': thumbnail35,
  'replicad/picovoxel-logo': thumbnail36,
  'replicad/planetary-gear-system': thumbnail37,
  'replicad/pot-plant': thumbnail38,
  'replicad/projection-test': thumbnail39,
  'replicad/rao-nozzle': thumbnail40,
  'replicad/replicad-logo': thumbnail41,
  'replicad/simple-tray': thumbnail42,
  'replicad/six-axis-arm': thumbnail43,
  'replicad/staircase': thumbnail44,
  'replicad/stress-test': thumbnail45,
  'replicad/t-slot-rail': thumbnail46,
  'replicad/table': thumbnail47,
  'replicad/tau-wordmark': thumbnail48,
  'replicad/tray': thumbnail49,
  'replicad/turbofan': thumbnail50,
  'replicad/v8-engine': thumbnail51,
  'replicad/vase': thumbnail52,
  'replicad/wavy-vase': thumbnail53,
  'replicad/wedge-door-stopper': thumbnail54,
  'replicad/worm-gear-system': thumbnail55,
} as const;

/** Key of a generated example thumbnail asset. @public */
export type ThumbnailAssetKey = keyof typeof thumbnailAssets;
