export const MOCK_CHAT_MESSAGES = [
  { content: 'Render gltf in React', role: 'user', status: 'success' },
  {
    role: 'assistant',
    content:
      "To render GLTF (GL Transmission Format) models in a React application, you can use the `@react-three/fiber` library along with `@react-three/drei`, which provides useful abstractions for working with 3D models. Below are the steps to set up a simple React component that renders a GLTF model.\n\n### Step 1: Install Required Packages\n\nFirst, you need to install the necessary packages. You can do this using npm or yarn:\n\n```bash\nnpm install three @react-three/fiber @react-three/drei\n```\n\nor\n\n```bash\nyarn add three @react-three/fiber @react-three/drei\n```\n\n### Step 2: Create a React Component\n\nNow, you can create a React component to load and render the GLTF model. Here's an example:\n\n```jsx\nimport React from 'react';\nimport { Canvas } from '@react-three/fiber';\nimport { OrbitControls, useGLTF } from '@react-three/drei';\n\nconst Model = ({ url }) => {\n  const { scene } = useGLTF(url);\n  return <primitive object={scene} />;\n};\n\nconst App = () => {\n  return (\n    <Canvas>\n      <ambientLight />\n      <pointLight position={[10, 10, 10]} />\n      <Model url=\"/path/to/your/model.gltf\" />\n      <OrbitControls />\n    </Canvas>\n  );\n};\n\nexport default App;\n```\n\n### Step 3: Add Your GLTF Model\n\nMake sure to replace `\"/path/to/your/model.gltf\"` with the actual path to your GLTF model file. You can place the model in the `public` directory of your React app for easy access.\n\n### Step 4: Run Your Application\n\nNow you can run your React application, and it should render the GLTF model in a 3D scene. You can use the mouse to rotate, zoom, and pan around the model thanks to the `OrbitControls`.\n\n### Additional Notes\n\n- Ensure that your GLTF model is properly formatted and accessible from the specified URL.\n- You can customize the lighting and camera settings in the `Canvas` component to better suit your model.\n- The `@react-three/drei` library provides many other useful components and hooks for working with 3D scenes, so feel free to explore its documentation for more features.\n\nThis setup should get you started with rendering GLTF models in a React application!",
    status: 'success',
  },
] as const;
