/**
 * Unified PBR defaults for all CAD conversion pipelines.
 *
 * @public
 */
export const cadMaterialDefaults = {
  roughnessFactor: 0.35,
  metalnessFactor: 0,
  baseColorFactor: [0.7, 0.7, 0.7, 1] as readonly [number, number, number, number],
} as const;

/**
 * Core glTF material defaults for auxiliary edge overlays generated by Tau.
 *
 * The base color is linear. Serializers must also encode
 * `KHR_materials_unlit` through their native writer API. Authored and imported
 * line materials do not use these defaults.
 *
 * @public
 */
export const cadEdgeOverlayMaterialDefaults = {
  baseColorFactor: [0, 0, 0, 1] as readonly [number, number, number, number],
  metallicFactor: 0,
  roughnessFactor: 1,
  doubleSided: true,
  alphaMode: 'OPAQUE',
} as const;
