// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 10,
  "height": 12,
  "bore": 5
};
export const parameterDomains = {
  "width": {
    "min": 8,
    "max": 12
  },
  "height": {
    "min": 9.600000000000001,
    "max": 14.399999999999999
  },
  "bore": {
    "min": 4,
    "max": 6
  }
};
export const design = "cap-nut";
