// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 20,
  "length": 60
};
export const parameterDomains = {
  "diameter": {
    "min": 18,
    "max": 22
  },
  "length": {
    "min": 54,
    "max": 66
  }
};
export const design = "d-shaft";
export const parameterCases = [
  {
    "name": "diameter 18",
    "parameters": {
      "diameter": 18
    },
    "expectations": {
      "bounds": {
        "x": 18,
        "y": 18,
        "z": 60
      },
      "solids": 1,
      "planes": [
        {
          "normal": [
            0,
            1,
            0
          ],
          "offset": 6.3,
          "area": {
            "greaterThan": 540
          },
          "tolerance": 0.03
        }
      ]
    }
  },
  {
    "name": "diameter 22",
    "parameters": {
      "diameter": 22
    },
    "expectations": {
      "bounds": {
        "x": 22,
        "y": 22,
        "z": 60
      },
      "solids": 1,
      "planes": [
        {
          "normal": [
            0,
            1,
            0
          ],
          "offset": 7.699999999999999,
          "area": {
            "greaterThan": 660
          },
          "tolerance": 0.03
        }
      ]
    }
  },
  {
    "name": "length 54",
    "parameters": {
      "length": 54
    },
    "expectations": {
      "bounds": {
        "x": 20,
        "y": 20,
        "z": 54
      },
      "solids": 1,
      "planes": [
        {
          "normal": [
            0,
            1,
            0
          ],
          "offset": 7,
          "area": {
            "greaterThan": 540
          },
          "tolerance": 0.03
        }
      ]
    }
  },
  {
    "name": "length 66",
    "parameters": {
      "length": 66
    },
    "expectations": {
      "bounds": {
        "x": 20,
        "y": 20,
        "z": 66
      },
      "solids": 1,
      "planes": [
        {
          "normal": [
            0,
            1,
            0
          ],
          "offset": 7,
          "area": {
            "greaterThan": 660
          },
          "tolerance": 0.03
        }
      ]
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "diameter": 18,
      "length": 54
    },
    "expectations": {
      "bounds": {
        "x": 18,
        "y": 18,
        "z": 54
      },
      "solids": 1,
      "planes": [
        {
          "normal": [
            0,
            1,
            0
          ],
          "offset": 6.3,
          "area": {
            "greaterThan": 486
          },
          "tolerance": 0.03
        }
      ]
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "diameter": 22,
      "length": 66
    },
    "expectations": {
      "bounds": {
        "x": 22,
        "y": 22,
        "z": 66
      },
      "solids": 1,
      "planes": [
        {
          "normal": [
            0,
            1,
            0
          ],
          "offset": 7.699999999999999,
          "area": {
            "greaterThan": 726
          },
          "tolerance": 0.03
        }
      ]
    }
  }
];
