// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 60,
  "length": 20
};
export const parameterDomains = {
  "diameter": {
    "min": 54,
    "max": 66
  },
  "length": {
    "min": 18,
    "max": 22
  }
};
export const design = "pull-handle";
export const parameterCases = [
  {
    "name": "diameter 54",
    "parameters": {
      "diameter": 54
    },
    "expectations": {
      "bounds": {
        "x": 54,
        "y": 20,
        "z": 10
      },
      "solids": 1
    }
  },
  {
    "name": "diameter 66",
    "parameters": {
      "diameter": 66
    },
    "expectations": {
      "bounds": {
        "x": 66,
        "y": 20,
        "z": 10
      },
      "solids": 1
    }
  },
  {
    "name": "length 18",
    "parameters": {
      "length": 18
    },
    "expectations": {
      "bounds": {
        "x": 60,
        "y": 18,
        "z": 9
      },
      "solids": 1
    }
  },
  {
    "name": "length 22",
    "parameters": {
      "length": 22
    },
    "expectations": {
      "bounds": {
        "x": 60,
        "y": 22,
        "z": 11
      },
      "solids": 1
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "diameter": 54,
      "length": 18
    },
    "expectations": {
      "bounds": {
        "x": 54,
        "y": 18,
        "z": 9
      },
      "solids": 1
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "diameter": 66,
      "length": 22
    },
    "expectations": {
      "bounds": {
        "x": 66,
        "y": 22,
        "z": 11
      },
      "solids": 1
    }
  }
];
