import { useCallback, useEffect } from 'react';
import type { JSX } from 'react';
import { FileExplorerContext } from '~/routes/builds_.$id/graphics-actor.js';
import { Tree, Folder, File } from '~/components/magicui/file-tree.js';
import type { TreeViewElement } from '~/components/magicui/file-tree.js';
import type { FileItem } from '~/machines/file-explorer.js';
import { cn } from '~/utils/ui.js';

// Mock file system structure - in real app this would come from server
const mockFileSystem: FileItem[] = [
  {
    id: 'models',
    name: 'models',
    path: 'models',
    content: '',
    isDirectory: true,
    children: [
      {
        id: 'chassis.step',
        name: 'chassis.step',
        path: 'models/chassis.step',
        content: `ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('STEP AP214'),'1');
FILE_NAME('chassis.step','2024-01-15T10:30:00',('CAD Designer'),('Engineering Dept'),'CAD System','CAD System','');
FILE_SCHEMA(('CONFIG_CONTROL_DESIGN'));
ENDSEC;

DATA;
#1 = CARTESIAN_POINT('Origin',(0.,0.,0.));
#2 = DIRECTION('Z-Axis',(0.,0.,1.));
#3 = DIRECTION('X-Axis',(1.,0.,0.));
#4 = AXIS2_PLACEMENT_3D('Origin',#1,#2,#3);
/* Chassis body geometry */
ENDSEC;
END-ISO-10303-21;`,
        language: 'step',
        isDirectory: false,
      },
      {
        id: 'wheel.stl',
        name: 'wheel.stl',
        path: 'models/wheel.stl',
        content: `solid wheel
  facet normal 0.0 0.0 1.0
    outer loop
      vertex 0.0 0.0 0.0
      vertex 1.0 0.0 0.0
      vertex 0.0 1.0 0.0
    endloop
  endfacet
  facet normal 0.0 0.0 1.0
    outer loop
      vertex 1.0 0.0 0.0
      vertex 1.0 1.0 0.0
      vertex 0.0 1.0 0.0
    endloop
  endfacet
endsolid wheel`,
        language: 'stl',
        isDirectory: false,
      },
    ],
  },
  {
    id: 'assemblies',
    name: 'assemblies',
    path: 'assemblies',
    content: '',
    isDirectory: true,
    children: [
      {
        id: 'main-assembly.asm',
        name: 'main-assembly.asm',
        path: 'assemblies/main-assembly.asm',
        content: `; Main Assembly Configuration
; Generated by CAD System

ASSEMBLY main-assembly
  PART chassis FROM models/chassis.step
    POSITION 0,0,0
    ROTATION 0,0,0
  END_PART
  
  PART wheel-fl FROM models/wheel.stl
    POSITION 50,100,10
    ROTATION 0,0,0
  END_PART
  
  PART wheel-fr FROM models/wheel.stl
    POSITION -50,100,10
    ROTATION 0,0,0
  END_PART
  
  ; Constraints
  CONSTRAINT MATE wheel-fl.surface1 TO chassis.mount-point-1
  CONSTRAINT MATE wheel-fr.surface1 TO chassis.mount-point-2
END_ASSEMBLY`,
        language: 'assembly',
        isDirectory: false,
      },
    ],
  },
  {
    id: 'scripts',
    name: 'scripts',
    path: 'scripts',
    content: '',
    isDirectory: true,
    children: [
      {
        id: 'parametric-model.scad',
        name: 'parametric-model.scad',
        path: 'scripts/parametric-model.scad',
        content: `// Parametric CAD Model
// OpenSCAD Script

// Parameters
wheel_diameter = 50;
wheel_width = 20;
hub_diameter = 15;
spoke_count = 5;

module wheel(diameter, width, hub_dia, spokes) {
    difference() {
        cylinder(h=width, d=diameter, center=true);
        cylinder(h=width+2, d=hub_dia, center=true);
        
        for (i = [0:spokes-1]) {
            rotate([0,0,i*360/spokes]) {
                translate([diameter/4,0,0]) {
                    cylinder(h=width+2, d=5, center=true);
                }
            }
        }
    }
}

// Generate wheel
wheel(wheel_diameter, wheel_width, hub_diameter, spoke_count);`,
        language: 'openscad',
        isDirectory: false,
      },
      {
        id: 'automation.py',
        name: 'automation.py',
        path: 'scripts/automation.py',
        content: `#!/usr/bin/env python3
"""
CAD Automation Script
Batch processes CAD files and generates reports
"""

import os
import json
from pathlib import Path

def process_step_files(input_dir: str, output_dir: str) -> dict:
    """Process STEP files and extract metadata"""
    results = {}
    
    for step_file in Path(input_dir).glob("*.step"):
        print(f"Processing {step_file.name}...")
        
        # Extract basic info (simplified)
        with open(step_file, 'r') as f:
            content = f.read()
            
        results[step_file.name] = {
            'file_size': step_file.stat().st_size,
            'entities': content.count('#'),
            'format': 'STEP AP214' if 'AP214' in content else 'STEP',
        }
    
    return results

def generate_report(data: dict, output_path: str):
    """Generate processing report"""
    with open(output_path, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"Report saved to {output_path}")

if __name__ == "__main__":
    results = process_step_files("models", "reports")
    generate_report(results, "reports/processing_report.json")`,
        language: 'python',
        isDirectory: false,
      },
    ],
  },
  {
    id: 'drawings',
    name: 'drawings',
    path: 'drawings',
    content: '',
    isDirectory: true,
    children: [
      {
        id: 'chassis-drawing.dwg',
        name: 'chassis-drawing.dwg',
        path: 'drawings/chassis-drawing.dwg',
        content: `; AutoCAD Drawing File
; Technical drawing for chassis component

SECTION
  HEADER
    $ACADVER 1 AC1027
    $DWGCODEPAGE 1 ANSI_1252
  ENDSEC
  
SECTION
  TABLES
    TABLE LAYER
      0 LAYER
      5 10
      330 0
      100 AcDbSymbolTableRecord
      100 AcDbLayerTableRecord
      2 DIMENSIONS
      70 0
      6 CONTINUOUS
    ENDTAB
  ENDSEC
  
SECTION
  ENTITIES
    0 LINE
    5 100
    330 1F
    100 AcDbEntity
    8 DIMENSIONS
    100 AcDbLine
    10 0.0
    20 0.0
    30 0.0
    11 100.0
    21 0.0
    31 0.0
  ENDSEC
ENDSECTION`,
        language: 'autocad',
        isDirectory: false,
      },
    ],
  },
  {
    id: 'config.json',
    name: 'config.json',
    path: 'config.json',
    content: `{
  "project": {
    "name": "Vehicle Chassis Design",
    "version": "1.2.0",
    "description": "Complete chassis assembly with parametric components",
    "author": "CAD Engineering Team"
  },
  "cad_settings": {
    "units": "millimeters",
    "precision": 0.01,
    "default_material": "steel",
    "render_quality": "high"
  },
  "build_parameters": {
    "chassis_length": 2000,
    "chassis_width": 800,
    "chassis_height": 150,
    "wheel_diameter": 500,
    "wheelbase": 1400
  },
  "export_formats": [
    "step",
    "stl",
    "obj",
    "dwg"
  ],
  "simulation_settings": {
    "mesh_size": "auto",
    "solver": "fem",
    "analysis_type": "static"
  }
}`,
    language: 'json',
    isDirectory: false,
  },
  {
    id: 'README.md',
    name: 'README.md',
    path: 'README.md',
    content: `# Vehicle Chassis CAD Project

This project contains the complete CAD files and documentation for a vehicle chassis design.

## Project Structure

- **models/**: 3D CAD models in various formats (STEP, STL)
- **assemblies/**: Assembly files defining how parts fit together
- **scripts/**: Automation scripts and parametric model definitions
- **drawings/**: 2D technical drawings and documentation

## Getting Started

1. Open the main assembly: \`assemblies/main-assembly.asm\`
2. Load dependent models from the \`models/\` directory
3. Adjust parameters in \`config.json\` as needed
4. Run automation scripts for batch processing

## CAD Software Compatibility

- **STEP files**: Universal format, compatible with most CAD systems
- **STL files**: For 3D printing and mesh-based operations
- **OpenSCAD scripts**: Parametric modeling with code
- **AutoCAD drawings**: 2D technical documentation

## Parameters

Key design parameters can be modified in \`config.json\`:
- Chassis dimensions
- Wheel specifications  
- Material properties
- Export settings
`,
    language: 'markdown',
    isDirectory: false,
  },
];

function convertFileItemToTreeElement(items: FileItem[]): TreeViewElement[] {
  return items.map((item) => ({
    id: item.id,
    name: item.name,
    isSelectable: !item.isDirectory,
    children: item.children ? convertFileItemToTreeElement(item.children) : undefined,
  }));
}

function findFileById(items: FileItem[], id: string): FileItem | undefined {
  for (const item of items) {
    if (item.id === id) {
      return item;
    }

    if (item.children) {
      const found = findFileById(item.children, id);
      if (found) {
        return found;
      }
    }
  }

  return undefined;
}

export function ChatEditorFileTree(): JSX.Element {
  const activeFileId = FileExplorerContext.useSelector((state) => state.context.activeFileId);
  const actorRef = FileExplorerContext.useActorRef();

  // Initialize file tree on mount
  useEffect(() => {
    actorRef.send({ type: 'setFileTree', tree: mockFileSystem });
  }, [actorRef]);

  const handleFileSelect = useCallback(
    (fileId: string) => {
      const file = findFileById(mockFileSystem, fileId);
      if (file && !file.isDirectory) {
        actorRef.send({ type: 'openFile', file });
      }
    },
    [actorRef],
  );

  const treeElements = convertFileItemToTreeElement(mockFileSystem);

  return (
    <div className={cn('flex h-full w-full flex-col bg-sidebar select-none')}>
      <h3 className="flex h-12 shrink-0 items-center border-b border-sidebar-border px-4 py-3 text-base font-medium text-sidebar-foreground/70">
        Files
      </h3>
      <div className="flex-1 overflow-hidden">
        <Tree
          className="my-1 h-full"
          elements={treeElements}
          initialExpandedItems={['models', 'assemblies', 'scripts']}
        >
          {treeElements.map((element) => (
            <TreeItem key={element.id} element={element} activeFileId={activeFileId} onSelect={handleFileSelect} />
          ))}
        </Tree>
      </div>
    </div>
  );
}

type TreeItemProps = {
  readonly element: TreeViewElement;
  readonly onSelect: (id: string) => void;
  readonly activeFileId: string | undefined;
};

function TreeItem({ element, onSelect, activeFileId }: TreeItemProps): JSX.Element {
  if (element.children && element.children.length > 0) {
    return (
      <Folder
        value={element.id}
        element={element.name}
        className="rounded-md px-2 py-1.5 text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
      >
        {element.children.map((child) => (
          <TreeItem key={child.id} element={child} activeFileId={activeFileId} onSelect={onSelect} />
        ))}
      </Folder>
    );
  }

  const isActive = activeFileId === element.id;

  return (
    <File
      value={element.id}
      className={cn(
        'w-full justify-start rounded-md px-2 py-1.5 text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground',
        isActive && 'bg-sidebar-accent text-sidebar-accent-foreground',
      )}
      onClick={() => {
        onSelect(element.id);
      }}
    >
      <span className="truncate">{element.name}</span>
    </File>
  );
}
