// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 10,
  "height": 6,
  "bore": 4.5,
  "flangeDiameter": 16
};
export const parameterDomains = {
  "width": {
    "min": 8,
    "max": 12
  },
  "height": {
    "min": 4.800000000000001,
    "max": 7.199999999999999
  },
  "bore": {
    "min": 3.6,
    "max": 5.3999999999999995
  },
  "flangeDiameter": {
    "min": 12.8,
    "max": 19.2
  }
};
export const design = "t-slot-nut";
