// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 30,
  "length": 40
};
export const parameterDomains = {
  "diameter": {
    "min": 27,
    "max": 33
  },
  "length": {
    "min": 36,
    "max": 44
  }
};
export const design = "socket-plug";
export const parameterCases = [
  {
    "name": "diameter 27",
    "parameters": {
      "diameter": 27
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 27,
        "z": 40
      },
      "solids": 1
    }
  },
  {
    "name": "diameter 33",
    "parameters": {
      "diameter": 33
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 33,
        "z": 40
      },
      "solids": 1
    }
  },
  {
    "name": "length 36",
    "parameters": {
      "length": 36
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 30,
        "z": 36
      },
      "solids": 1
    }
  },
  {
    "name": "length 44",
    "parameters": {
      "length": 44
    },
    "expectations": {
      "bounds": {
        "x": 30,
        "y": 30,
        "z": 44
      },
      "solids": 1
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "diameter": 27,
      "length": 36
    },
    "expectations": {
      "bounds": {
        "x": 27,
        "y": 27,
        "z": 36
      },
      "solids": 1
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "diameter": 33,
      "length": 44
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 33,
        "z": 44
      },
      "solids": 1
    }
  }
];
