// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Carriage bolt", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 29
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 29
}, tolerance: 0.1 });
});
it("diameter-minimum", async () => {
const parameters = {
  "diameter": 4.800000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 29
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 29
}, tolerance: 0.1 });
});
it("diameter-maximum", async () => {
const parameters = {
  "diameter": 7.199999999999999
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 29
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 29
}, tolerance: 0.1 });
});
it("length-minimum", async () => {
const parameters = {
  "length": 19.200000000000003
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 24.200000000000003
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 24.200000000000003
}, tolerance: 0.1 });
});
it("length-maximum", async () => {
const parameters = {
  "length": 28.799999999999997
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 33.8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 33.8
}, tolerance: 0.1 });
});
it("headDiameter-minimum", async () => {
const parameters = {
  "headDiameter": 11.200000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.200000000000001,
  "y": 11.200000000000001,
  "z": 29
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.200000000000001,
  "y": 11.200000000000001,
  "z": 29
}, tolerance: 0.1 });
});
it("headDiameter-maximum", async () => {
const parameters = {
  "headDiameter": 16.8
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 16.8,
  "y": 16.8,
  "z": 29
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 16.8,
  "y": 16.8,
  "z": 29
}, tolerance: 0.1 });
});
it("headHeight-minimum", async () => {
const parameters = {
  "headHeight": 4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 28
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 28
}, tolerance: 0.1 });
});
it("headHeight-maximum", async () => {
const parameters = {
  "headHeight": 6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 30
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 14,
  "y": 14,
  "z": 30
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "diameter": 4.800000000000001,
  "length": 19.200000000000003,
  "headDiameter": 11.200000000000001,
  "headHeight": 4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.200000000000001,
  "y": 11.200000000000001,
  "z": 23.200000000000003
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.200000000000001,
  "y": 11.200000000000001,
  "z": 23.200000000000003
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "diameter": 7.199999999999999,
  "length": 28.799999999999997,
  "headDiameter": 16.8,
  "headHeight": 6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 16.8,
  "y": 16.8,
  "z": 34.8
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThan: 0 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 16.8,
  "y": 16.8,
  "z": 34.8
}, tolerance: 0.1 });
});
});
