import ChatLedgerProofs

/-! Axiom audit: every result uses only Lean's standard axioms (propext, Quot.sound, Classical.choice); none uses sorryAx. -/
#print axioms ChatLedger.lookup_upsert
#print axioms ChatLedger.lookup_append_single
#print axioms ChatLedger.replay_seq
#print axioms ChatLedger.replayLog_seq
#print axioms ChatLedger.replayLog_append
#print axioms ChatLedger.verdict_found
#print axioms ChatLedger.find_none_of_verdict
#print axioms ChatLedger.keyed_commit
#print axioms ChatLedger.keyed_replay
#print axioms ChatLedger.keyed_seqOf
#print axioms ChatLedger.key_held_of_verdict
#print axioms ChatLedger.key_mem_replay
#print axioms ChatLedger.key_mem_seqOf
#print axioms ChatLedger.eq_of_key_eq
#print axioms ChatLedger.t1_duplicate
#print axioms ChatLedger.t1_mutated
#print axioms ChatLedger.verdict_held
#print axioms ChatLedger.rowsOf_append
#print axioms ChatLedger.rows_write_row
#print axioms ChatLedger.rows_write_junk
#print axioms ChatLedger.rows_tear
#print axioms ChatLedger.X_seq
#print axioms ChatLedger.prepare_ok
#print axioms ChatLedger.append_cases
#print axioms ChatLedger.t9_refused_writes_nothing
#print axioms ChatLedger.t9_stale_writes_nothing
#print axioms ChatLedger.good_open
#print axioms ChatLedger.good_write
#print axioms ChatLedger.good_tear
#print axioms ChatLedger.X_append_row
#print axioms ChatLedger.good_append_other
#print axioms ChatLedger.good_append_self
#print axioms ChatLedger.reach_good
#print axioms ChatLedger.t1_held_key_never_writes
#print axioms ChatLedger.snoc_induction
#print axioms ChatLedger.commitAll_snoc
#print axioms ChatLedger.strict_append
#print axioms ChatLedger.strict_replay
#print axioms ChatLedger.commitAll_rows
#print axioms ChatLedger.commitAll_max
#print axioms ChatLedger.commitAll_epochs_isSome
#print axioms ChatLedger.verdict_fresh
#print axioms ChatLedger.strict_epoch
#print axioms ChatLedger.t2_new_term
#print axioms ChatLedger.t2_contiguous
#print axioms ChatLedger.clean_empty
#print axioms ChatLedger.clean_append
#print axioms ChatLedger.reach_clean
#print axioms ChatLedger.t9_log_stays_clean
#print axioms ChatLedger.t2_appender_enforced
#print axioms ChatLedger.t1_identical_is_noop
#print axioms ChatLedger.entry_put
#print axioms ChatLedger.grows_of_same
#print axioms ChatLedger.grows_trans
#print axioms ChatLedger.same_trans
#print axioms ChatLedger.same_put
#print axioms ChatLedger.same_note
#print axioms ChatLedger.same_ite
#print axioms ChatLedger.same_closeInv
#print axioms ChatLedger.same_markShown
#print axioms ChatLedger.same_lifecycle
#print axioms ChatLedger.grows_settle
#print axioms ChatLedger.grows_known
#print axioms ChatLedger.same_book
#print axioms ChatLedger.same_markOpaque
#print axioms ChatLedger.grows_stepD
#print axioms ChatLedger.grows_fold
#print axioms ChatLedger.t3_never_discarded
#print axioms ChatLedger.t3_one_per_attempt
#print axioms ChatLedger.stamp_S
#print axioms ChatLedger.attemptOf_self
#print axioms ChatLedger.t3_host
#print axioms ChatLedger.reopens_def
#print axioms ChatLedger.t4_reopenable_reopens
#print axioms ChatLedger.t4_paused_cancels
#print axioms ChatLedger.t4_failed_cancel_refused
#print axioms ChatLedger.t4_reopens_legal
#print axioms ChatLedger.t4_running_legal
#print axioms ChatLedger.t4_fold_attempt
#print axioms ChatLedger.reopens_stamped
#print axioms ChatLedger.t4_stamp_fold_agree
#print axioms ChatLedger.t4_paused_continues
#print axioms ChatLedger.t4_paused_reopens
#print axioms ChatLedger.t4_user_stop_reopens
#print axioms ChatLedger.t4_uncommitted_stop_ended
#print axioms ChatLedger.t4_cancel_ended
#print axioms ChatLedger.t4_external_prompted_stop_reopens
#print axioms ChatLedger.t4_external_unprompted_stop_ended
#print axioms ChatLedger.t4_abandoned_reopens
#print axioms ChatLedger.t4_failure_kind_refused
#print axioms ChatLedger.t4_external_pause_open
#print axioms ChatLedger.t5_refusal_resets
#print axioms ChatLedger.t5_folded_aligned
#print axioms ChatLedger.t5_clamp_detected
#print axioms ChatLedger.t5_ahead_refused
#print axioms ChatLedger.t5_mismatch_refused
#print axioms ChatLedger.getElem_of_prefix
#print axioms ChatLedger.t5_append_only
#print axioms ChatLedger.t5_folds_aligned
#print axioms ChatLedger.t6_chunk_invariant
#print axioms ChatLedger.terms_closeInv
#print axioms ChatLedger.terms_markShown
#print axioms ChatLedger.terms_lifecycle
#print axioms ChatLedger.terms_settle
#print axioms ChatLedger.terms_known
#print axioms ChatLedger.terms_markOpaque
#print axioms ChatLedger.terms_advance
#print axioms ChatLedger.covers_stepD
#print axioms ChatLedger.covers_fold
#print axioms ChatLedger.stepD_covered
#print axioms ChatLedger.t6_redelivered_noop
#print axioms ChatLedger.t6_redelivery_idempotent
#print axioms ChatLedger.t8_lifecycle_registry
#print axioms ChatLedger.t8_operation_registry
#print axioms ChatLedger.t8_settlement_registry
#print axioms ChatLedger.t8_gate_registry
#print axioms ChatLedger.t8_gate_is_table
#print axioms ChatLedger.t8_prepare_gate_later
#print axioms ChatLedger.t8_prepare_gate_first
#print axioms ChatLedger.insertBy_perm
#print axioms ChatLedger.isort_perm
#print axioms ChatLedger.inj_of_nodup_map
#print axioms ChatLedger.upsert_keys
#print axioms ChatLedger.upsert_nodup
#print axioms ChatLedger.mem_upsert
#print axioms ChatLedger.lookup_eq_some
#print axioms ChatLedger.add_copies
#print axioms ChatLedger.add_term
#print axioms ChatLedger.add_wf
#print axioms ChatLedger.add_holds
#print axioms ChatLedger.empty_wf
#print axioms ChatLedger.addRow_spec
#print axioms ChatLedger.segment_spec
#print axioms ChatLedger.segments_spec
#print axioms ChatLedger.mergedTerms_spec
#print axioms ChatLedger.keySort_perm
#print axioms ChatLedger.keptCopy_mem
#print axioms ChatLedger.keptCopy_own
#print axioms ChatLedger.dropScan_sub
#print axioms ChatLedger.dropScan_ne
#print axioms ChatLedger.dropped_sound
#print axioms ChatLedger.dropped_complete
#print axioms ChatLedger.mergeFull_eq
#print axioms ChatLedger.mem_mergeKeys
#print axioms ChatLedger.perm_flatMap_left
#print axioms ChatLedger.mergeKey_key
#print axioms ChatLedger.merge_keys_perm
#print axioms ChatLedger.nodup_map_of_inj
#print axioms ChatLedger.allKeys_nodup
#print axioms ChatLedger.t7_no_duplicates
#print axioms ChatLedger.t7_exact_union
#print axioms ChatLedger.t7_rows_are_read
#print axioms ChatLedger.t7_conflicts_sound
#print axioms ChatLedger.t7_conflicts_complete
#print axioms ChatLedger.StrictTotal.asymm
#print axioms ChatLedger.lexBy_st
#print axioms ChatLedger.lexLt_st
#print axioms ChatLedger.keyLt_st
#print axioms ChatLedger.ofD_snoc
#print axioms ChatLedger.digitsAux_spec
#print axioms ChatLedger.ofD_digits
#print axioms ChatLedger.digits_inj
#print axioms ChatLedger.ofD_zeros
#print axioms ChatLedger.ofD_termId
#print axioms ChatLedger.termId_inj
#print axioms ChatLedger.Kind.ix_inj
#print axioms ChatLedger.canonKey_inj
#print axioms ChatLedger.copyKey_inj
#print axioms ChatLedger.insertBy_sorted
#print axioms ChatLedger.isort_sorted
#print axioms ChatLedger.keySort_sorted
#print axioms ChatLedger.sorted_strict
#print axioms ChatLedger.eq_of_sorted
#print axioms ChatLedger.eq_of_sorted_perm
#print axioms ChatLedger.keySort_head_min
#print axioms ChatLedger.keySort_head_key
#print axioms ChatLedger.minOpt_congr
#print axioms ChatLedger.maxOpt_congr
#print axioms ChatLedger.minOpt_snoc
#print axioms ChatLedger.isEmpty_congr
#print axioms ChatLedger.keptCopy_det
#print axioms ChatLedger.dropped_eq
#print axioms ChatLedger.dropScan_spec
#print axioms ChatLedger.dropped_pairs
#print axioms ChatLedger.dropped_det
#print axioms ChatLedger.introduced_snoc
#print axioms ChatLedger.mem_introduced
#print axioms ChatLedger.ordsOf_seg
#print axioms ChatLedger.msOf_seg
#print axioms ChatLedger.ordsOf_step_other
#print axioms ChatLedger.ordsOf_step_new
#print axioms ChatLedger.msOf_step
#print axioms ChatLedger.rows_step
#print axioms ChatLedger.minOpt_step
#print axioms ChatLedger.addRow_char
#print axioms ChatLedger.segment_char
#print axioms ChatLedger.char_empty_seg
#print axioms ChatLedger.mergedTerms_char
#print axioms ChatLedger.lookup_isSome
#print axioms ChatLedger.deviceOf_eq
#print axioms ChatLedger.ordsOf_congr
#print axioms ChatLedger.msOf_congr
#print axioms ChatLedger.holds_congr
#print axioms ChatLedger.match_term
#print axioms ChatLedger.term_copies
#print axioms ChatLedger.key_copies
#print axioms ChatLedger.term_data
#print axioms ChatLedger.place_data
#print axioms ChatLedger.key_data
#print axioms ChatLedger.clampStarts_eq
#print axioms ChatLedger.clampDevices_mem_aux
#print axioms ChatLedger.clampDevices_mem
#print axioms ChatLedger.crun_spec
#print axioms ChatLedger.crun_mem
#print axioms ChatLedger.lookup_of_all
#print axioms ChatLedger.clamp_lookup
#print axioms ChatLedger.SameSegs.symm
#print axioms ChatLedger.placed_nodup
#print axioms ChatLedger.keyObs_eq
#print axioms ChatLedger.keys_obs_eq
#print axioms ChatLedger.clampSet_congr
#print axioms ChatLedger.termObs_eq
#print axioms ChatLedger.mergeFull_obs
#print axioms ChatLedger.obs_eq
#print axioms ChatLedger.t7_same_segments
#print axioms ChatLedger.t7_segment_order
#print axioms ChatLedger.t7_duplicate_segment
#print axioms ChatLedger.t7_file_order
#print axioms ChatLedger.placed_sorted
#print axioms ChatLedger.t7_device_file_order
#print axioms ChatLedger.t8_interrupt_resolved_once
#print axioms ChatLedger.t8_duplicate_interrupt_resolution
#print axioms ChatLedger.t4_d2_second_running_keeps_attempt
#print axioms ChatLedger.t3_d3_settlement_survives
#print axioms ChatLedger.t6_d7_redelivery_keeps_settled
#print axioms ChatLedger.t5_d6_clamp_resets
#print axioms ChatLedger.t7_d5_segment_order
#print axioms ChatLedger.t7_d5_duplicate_segment
#print axioms ChatLedger.t7_d5_conflict_kept_and_reported
#print axioms ChatLedger.t7_merge_not_prefix_stable
#print axioms ChatLedger.d26_duplicate_boundary_keeps_semantic_term
