import ChatLedgerProofs

/-! Axiom audit: every result uses only Lean's standard axioms (propext, Quot.sound, Classical.choice); none uses sorryAx. -/
#print axioms ChatLedger.inv_init
#print axioms ChatLedger.sameKey_self
#print axioms ChatLedger.check_ok_false
#print axioms ChatLedger.inv_commit
#print axioms ChatLedger.inv_append
#print axioms ChatLedger.reach_inv
#print axioms ChatLedger.t1_reappend_noop
#print axioms ChatLedger.t1_mutated
#print axioms ChatLedger.t2_contig
#print axioms ChatLedger.t2_key_unique
#print axioms ChatLedger.t2_keys_nodup
#print axioms ChatLedger.t2_closed_frozen
#print axioms ChatLedger.step_entry_other
#print axioms ChatLedger.settle_isSome_iff
#print axioms ChatLedger.settleLegal_none
#print axioms ChatLedger.settleLegal_of_some
#print axioms ChatLedger.t3_at_most_one
#print axioms ChatLedger.sinceRunning_append_ge
#print axioms ChatLedger.SettleLegalLog.suffix
#print axioms ChatLedger.t3_no_two_per_attempt
#print axioms ChatLedger.t3_host
#print axioms ChatLedger.t4_closed_until_running
#print axioms ChatLedger.t4_running_reopens
#print axioms ChatLedger.t4_reopen_broader_than_legality
#print axioms ChatLedger.reopenable_paused_is_dead
#print axioms ChatLedger.t3_bypass_settlement_discarded
#print axioms ChatLedger.paused_after_settled_terminal_refused
#print axioms ChatLedger.entry_life
#print axioms ChatLedger.admittedCount_zero
#print axioms ChatLedger.admitted_at_most_once
#print axioms ChatLedger.appender_any_start
#print axioms ChatLedger.ledger_eq_foldr
#print axioms ChatLedger.t6_physical
#print axioms ChatLedger.t6_incremental
#print axioms ChatLedger.put_self
#print axioms ChatLedger.t6_step_idem
#print axioms ChatLedger.t6_redelivery_breaks
#print axioms ChatLedger.t6_applied_redelivery
#print axioms ChatLedger.t6_applied_faithful
#print axioms ChatLedger.t6_applied_matches_log
#print axioms ChatLedger.ledgerLe_refl
#print axioms ChatLedger.ledgerLe_trans
#print axioms ChatLedger.ledgerLe_step
#print axioms ChatLedger.t6_monotone
#print axioms ChatLedger.t6_settled_not_monotone
#print axioms ChatLedger.replayed_settled_iff
#print axioms ChatLedger.replayed_settled_is_not_ledger_settled
#print axioms ChatLedger.byteBounded_prefix
#print axioms ChatLedger.take_length_take
#print axioms ChatLedger.t5_readBatch_honest
#print axioms ChatLedger.honest_len
#print axioms ChatLedger.t5_sound
#print axioms ChatLedger.t5_complete
#print axioms ChatLedger.t5_clamp_iff
#print axioms ChatLedger.t5_ts_readers_blind
#print axioms ChatLedger.t5_seq_gaps_incomplete
#print axioms ChatLedger.t7_segment_order_matters
#print axioms ChatLedger.t7_duplicate_segment_breaks_file_order
#print axioms ChatLedger.t7_merge_not_prefix_stable
#print axioms ChatLedger.t7_conflicting_copy_first_wins
#print axioms ChatLedger.insertBy_perm
#print axioms ChatLedger.isort_perm
#print axioms ChatLedger.perm_flatMap_left
#print axioms ChatLedger.mem_allKeys
#print axioms ChatLedger.addRow_spec
#print axioms ChatLedger.clamp_proj
#print axioms ChatLedger.proj_keys
#print axioms ChatLedger.mergeSegment_spec
#print axioms ChatLedger.segments_spec
#print axioms ChatLedger.t7_keys_exact
#print axioms ChatLedger.nodup_of_map
#print axioms ChatLedger.addRow_distinct
#print axioms ChatLedger.proj_distinct
#print axioms ChatLedger.segments_distinct
#print axioms ChatLedger.allKeys_nodup
#print axioms ChatLedger.t7_no_duplicates
