// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 16,
  "height": 24,
  "flangeDiameter": 22,
  "thickness": 2,
  "bore": 8
};
export const parameterDomains = {
  "diameter": {
    "min": 12.8,
    "max": 19.2
  },
  "height": {
    "min": 19.200000000000003,
    "max": 28.799999999999997
  },
  "flangeDiameter": {
    "min": 17.6,
    "max": 26.4
  },
  "thickness": {
    "min": 1.6,
    "max": 2.4
  },
  "bore": {
    "min": 6.4,
    "max": 9.6
  }
};
export const design = "cable-gland";
