import { defineConfig } from 'tsdown';
import type { UserConfig } from 'tsdown';

const baseConfig: UserConfig = {
  entry: [
    'src/index.ts',
    'src/components/accordion.tsx',
    'src/components/alert-dialog.tsx',
    'src/components/avatar.tsx',
    'src/components/badge.tsx',
    'src/components/breadcrumb.tsx',
    'src/components/button-group.tsx',
    'src/components/button.tsx',
    'src/components/calendar.tsx',
    'src/components/card.tsx',
    'src/components/carousel.tsx',
    'src/components/chart.tsx',
    'src/components/checkbox.tsx',
    'src/components/collapsible.tsx',
    'src/components/command.tsx',
    'src/components/context-menu.tsx',
    'src/components/dialog.tsx',
    'src/components/drawer.tsx',
    'src/components/dropdown-menu.tsx',
    'src/components/field.tsx',
    'src/components/hover-card.tsx',
    'src/components/input-group.tsx',
    'src/components/input.tsx',
    'src/components/label.tsx',
    'src/components/menu.variants.ts',
    'src/components/navigation-menu.tsx',
    'src/components/popover.variants.ts',
    'src/components/popover.tsx',
    'src/components/progress.tsx',
    'src/components/radio-group.tsx',
    'src/components/resizable.tsx',
    'src/components/scroll-area.tsx',
    'src/components/select.tsx',
    'src/components/separator.tsx',
    'src/components/sheet.tsx',
    'src/components/sidebar.tsx',
    'src/components/skeleton.tsx',
    'src/components/slider.tsx',
    'src/components/sonner.tsx',
    'src/components/switch.tsx',
    'src/components/table.tsx',
    'src/components/tabs.tsx',
    'src/components/textarea.tsx',
    'src/components/toggle-group.tsx',
    'src/components/toggle.tsx',
    'src/components/tooltip.tsx',
    'src/hooks/use-mobile.ts',
    'src/utils/cn.ts',
  ],
  sourcemap: false,
  clean: ['dist'],
  copy: ({ outDir }) => [
    { from: 'src/styles/tokens.css', to: `${outDir}/styles` },
    { from: 'src/styles/tokens.css.d.ts', to: `${outDir}/styles` },
  ],
  dts: true,
  minify: true,
  tsconfig: 'tsconfig.build.json',
  unbundle: true,
};

const packageConfig: UserConfig = {
  ...baseConfig,
  format: 'esm',
  outDir: 'dist',
};

export default defineConfig(packageConfig);
