// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Hex standoff", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 20
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 916.0889668117065, lessThanOrEqual: 916.0909668117065 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 20
}, tolerance: 0.1 });
});
it("width-minimum", async () => {
const parameters = {
  "width": 6.4
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 7.39008344562721,
  "y": 6.4,
  "z": 20
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 517.0244607478375, lessThanOrEqual: 517.0264607478374 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 7.39008344562721,
  "y": 6.4,
  "z": 20
}, tolerance: 0.1 });
});
it("width-maximum", async () => {
const parameters = {
  "width": 9.6
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.085125168440815,
  "y": 9.6,
  "z": 20
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 1403.8344742231022, lessThanOrEqual: 1403.8364742231022 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.085125168440815,
  "y": 9.6,
  "z": 20
}, tolerance: 0.1 });
});
it("bore-minimum", async () => {
const parameters = {
  "bore": 2.8000000000000003
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 20
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 985.3610848233616, lessThanOrEqual: 985.3630848233615 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 2.8000000000000003,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 20
}, tolerance: 0.1 });
});
it("bore-maximum", async () => {
const parameters = {
  "bore": 4.2
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 20
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 831.4230447974617, lessThanOrEqual: 831.4250447974616 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.2,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 20
}, tolerance: 0.1 });
});
it("length-minimum", async () => {
const parameters = {
  "length": 16
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 16
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 732.8709734493652, lessThanOrEqual: 732.8729734493652 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 16
}, tolerance: 0.1 });
});
it("length-maximum", async () => {
const parameters = {
  "length": 24
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 24
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 1099.3069601740478, lessThanOrEqual: 1099.3089601740478 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 3.5,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 9.237604307034013,
  "y": 8,
  "z": 24
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "width": 6.4,
  "bore": 2.8000000000000003,
  "length": 16
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 7.39008344562721,
  "y": 6.4,
  "z": 16
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 469.03706300759393, lessThanOrEqual: 469.0390630075939 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 2.8000000000000003,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 7.39008344562721,
  "y": 6.4,
  "z": 16
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "width": 9.6,
  "bore": 4.2,
  "length": 24
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 11.085125168440815,
  "y": 9.6,
  "z": 24
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 1583.002462650629, lessThanOrEqual: 1583.004462650629 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.2,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 11.085125168440815,
  "y": 9.6,
  "z": 24
}, tolerance: 0.1 });
});
it("thin-wall-corner", async () => {
const parameters = {
  "width": 6.4,
  "bore": 4.2,
  "length": 20
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 7.39008344562721,
  "y": 6.4,
  "z": 20
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 432.3585387335925, lessThanOrEqual: 432.3605387335925 } });
expectGeo(exact).toHaveCircularHole({
  "diameter": 4.2,
  "center": {
    "x": 0,
    "y": 0
  },
  "axis": "z",
  "through": true,
  "tolerance": 0.05
});
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 7.39008344562721,
  "y": 6.4,
  "z": 20
}, tolerance: 0.1 });
});
});
