/* oxlint-disable no-bitwise -- The TypeScript compiler API models symbol and type state as bit flags. */

/**
 * The tscircuit authoring surface: the JSX intrinsic elements a `main.tsx`
 * writes, their props, the named prop types those props reference, the
 * footprint-string functions and the few helpers authors import.
 *
 * The surface is not a module's exports. `@tscircuit/core` registers its
 * elements on a non-exported `TscircuitElements` interface that augments
 * `JSX.IntrinsicElements`, and half of `@tscircuit/props`' prop types are
 * `z.input<typeof xProps>` aliases whose declarations are Zod schemas. So this
 * front-end walks that interface with the checker instead of
 * `checker.getExportsOfModule`, names each element by its tag (`<resistor>`)
 * so it is greppable from JSX, prints a Zod-derived prop as the type the
 * checker resolves rather than its schema, and lists only the props an element
 * adds over the largest shared base (`CommonComponentProps` and friends), which
 * become entries of their own.
 *
 * The corpus is committed (`generated/tscircuit/tscircuit.corpus.json`) and
 * regenerated by `nx run api-extractor:extract-tscircuit`: the program spans
 * ~20 MB of declarations that pnpm links only into the plugin's own
 * `node_modules`, and a committed file regenerates bundles identically without
 * either.
 *
 * @module
 */

import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import ts from 'typescript';

import { typescriptCompilerOptions, typescriptEntryDrafts } from '#languages/typescript/extract.js';
import type { ApiEntryDraft } from '#model/api-corpus.js';
import { createApiCorpus } from '#model/api-corpus.js';
import type { ApiCorpus, ApiEntry } from '#model/api-corpus.types.js';

/** The committed corpus. @internal */
export const tscircuitCorpusFile: string = fileURLToPath(
  new URL('../../generated/tscircuit/tscircuit.corpus.json', import.meta.url),
);

/**
 * Read the committed tscircuit corpus.
 *
 * @returns The corpus `extract-tscircuit` wrote.
 * @public
 */
export const loadTscircuitCorpus = (): ApiCorpus => JSON.parse(readFileSync(tscircuitCorpusFile, 'utf8')) as ApiCorpus;

/**
 * The reference grouping: the category assigned at extraction.
 *
 * @param entry - A top-level entry.
 * @returns Its group title.
 * @public
 */
export const byTscircuitGroup = (entry: ApiEntry): string => entry.category ?? 'Other';

/** Shared prop bases an element's own props are listed against, by name in `@tscircuit/props`. */
const sharedBases = [
  'CommonComponentProps',
  'CommonLayoutProps',
  'PcbLayoutProps',
  'SubcircuitGroupProps',
  'BaseGroupProps',
] as const;

/** Authoring helpers `@tscircuit/core` exports (and `tscircuit` re-exports). */
const helperNames = ['sel', 'useChip', 'useResistor', 'useCapacitor', 'useDiode', 'useLed', 'createUseComponent'];

/** Ponytail: a referenced type or helper longer than this is a generated union (KiCad paths, inlined Zod output), not reference material. */
const maxTypeTextLength = 1500;

/** A base may lack this many of its props and still be the base (`BoardProps` omits two of `SubcircuitGroupProps`). */
const maxOmittedBaseProps = 3;

const propsFileSuffix = '/@tscircuit/props/dist/index.d.ts';

const boardTags = new Set([
  'board',
  'group',
  'subcircuit',
  'panel',
  'subpanel',
  'mountedboard',
  'breakout',
  'breakoutpoint',
  'fanout',
  'fanoutpoint',
  'autoroutingphase',
  'constraint',
  'constrainedlayout',
  'drccheck',
]);
/** Second names for one element; the canonical tag lists the props and the alias points at it. */
const aliasTags = new Set(['bug', 'fanout', 'fanoutpoint']);

const connectivityTags = new Set([
  'trace',
  'net',
  'netlabel',
  'bus',
  'differentialpair',
  'tracehint',
  'pcbtrace',
  'port',
]);

const elementCategory = (tag: string, base: string | undefined): string => {
  if (boardTags.has(tag)) {
    return 'Boards, groups and layout';
  }
  if (connectivityTags.has(tag)) {
    return 'Connectivity';
  }
  if (tag.startsWith('schematic')) {
    return 'Schematic drawing';
  }
  if (tag.startsWith('analog') || tag === 'spicemodel') {
    return 'Simulation';
  }
  return base === 'CommonComponentProps' ? 'Components' : 'PCB, footprint and CAD primitives';
};

/** One line of declaration text: comments dropped, whitespace collapsed, `_tscircuit_props.` unqualified. */
const collapse = (text: string): string =>
  text
    .replaceAll(/\/\*[\S\s]*?\*\//gu, '')
    .replaceAll(/\b_tscircuit_props\./gu, '')
    .replaceAll(/\s+/gu, ' ')
    .replaceAll(/([([{<]) /gu, '$1')
    .replaceAll(/ ([)\]>])/gu, '$1')
    .trim();

/** A Zod schema type is unreadable as a prop type; the checker's resolved type replaces it. */
const isSchemaText = (text: string): boolean => /\bz\.|\bZod[A-Z]|\btypeof\b/u.test(text);

const sourceOf = (node: ts.Node): { file: string; line: number } => {
  const file = node.getSourceFile();
  const marker = file.fileName.lastIndexOf('/node_modules/');
  return {
    file: marker === -1 ? file.fileName : file.fileName.slice(marker + '/node_modules/'.length),
    line: file.getLineAndCharacterOfPosition(node.getStart(file)).line + 1,
  };
};

const summaryOf = (symbol: ts.Symbol | undefined, checker: ts.TypeChecker): string =>
  symbol === undefined
    ? ''
    : collapse(ts.displayPartsToString(symbol.getDocumentationComment(checker)).split(/\n\s*\n/u)[0] ?? '');

const isDeprecated = (symbol: ts.Symbol, checker: ts.TypeChecker): boolean =>
  symbol.getJsDocTags(checker).some((tag) => tag.name === 'deprecated');

const isOptional = (symbol: ts.Symbol): boolean => (symbol.flags & ts.SymbolFlags.Optional) !== 0;

const typeParametersText = (declaration: ts.InterfaceDeclaration | ts.TypeAliasDeclaration): string =>
  declaration.typeParameters === undefined
    ? ''
    : `<${declaration.typeParameters.map((parameter) => parameter.getText()).join(', ')}>`;

const typescript = { language: 'typescript' } as const;

type Extraction = {
  readonly checker: ts.TypeChecker;
  /** Each shared base's prop names. */
  readonly bases: ReadonlyMap<string, readonly string[]>;
  /** Named `@tscircuit/props` types a rendered prop references, in discovery order. */
  readonly referenced: Set<ts.Declaration>;
};

/** Queue every `@tscircuit/props` interface or alias a type node names. */
const collectReferences = (node: ts.Node, extraction: Extraction): void => {
  const visit = (current: ts.Node): void => {
    const name = ts.isTypeReferenceNode(current)
      ? current.typeName
      : ts.isExpressionWithTypeArguments(current)
        ? current.expression
        : undefined;
    if (name !== undefined) {
      let symbol = extraction.checker.getSymbolAtLocation(name);
      if (symbol !== undefined && (symbol.flags & ts.SymbolFlags.Alias) !== 0) {
        symbol = extraction.checker.getAliasedSymbol(symbol);
      }
      const declaration = symbol?.declarations?.[0];
      if (
        declaration !== undefined &&
        (ts.isInterfaceDeclaration(declaration) || ts.isTypeAliasDeclaration(declaration)) &&
        declaration.getSourceFile().fileName.endsWith(propsFileSuffix)
      ) {
        extraction.referenced.add(declaration);
      }
    }
    ts.forEachChild(current, visit);
  };
  visit(node);
};

/** A prop as one property entry: its declared type when readable, otherwise the type the checker resolves. */
const propertyEntry = (property: ts.Symbol, extraction: Extraction): ApiEntryDraft => {
  const { checker } = extraction;
  const declaration = property.valueDeclaration ?? property.declarations?.[0];
  const declared =
    declaration !== undefined && ts.isPropertySignature(declaration) && declaration.type !== undefined
      ? declaration.type
      : undefined;
  let text: string;
  if (declared === undefined || isSchemaText(declared.getText())) {
    text = checker.typeToString(
      checker.getTypeOfSymbol(property),
      undefined,
      ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope,
    );
  } else {
    text = collapse(declared.getText());
    collectReferences(declared, extraction);
  }
  if (isOptional(property)) {
    text = text.replace(/ \| undefined$/u, '');
  }
  const summary = summaryOf(property, checker);
  return {
    name: property.name,
    kind: 'property',
    type: { text },
    ...(isOptional(property) ? { optional: true } : {}),
    ...(summary === '' ? {} : { docs: { summary } }),
    ...(declaration === undefined ? {} : { source: sourceOf(declaration) }),
    languageSpecific: typescript,
  };
};

/** Every prop a type accepts; for a union of variants (`<trace>`'s `from`/`to` or `path`), every variant's. */
const propertiesOf = (type: ts.Type, checker: ts.TypeChecker): ts.Symbol[] => {
  const variants = type.isUnion() ? type.types : [type];
  const byName = new Map<string, ts.Symbol>();
  for (const property of variants.flatMap((variant) => checker.getPropertiesOfType(variant))) {
    if (!byName.has(property.name) && property.name !== 'key' && !property.name.startsWith('_')) {
      byName.set(property.name, property);
    }
  }
  return [...byName.values()];
};

type PropsShape = {
  /** `CommonComponentProps`, or `Omit<SubcircuitGroupProps, "subcircuit">` for a base it narrows. */
  readonly heritage: string | undefined;
  readonly base: string | undefined;
  readonly own: readonly ts.Symbol[];
  readonly required: readonly string[];
};

/** Split a props type into the largest shared base it (almost) contains and the props it adds. */
const propsShape = (type: ts.Type, extraction: Extraction, self?: string): PropsShape => {
  const { bases, checker } = extraction;
  const properties = propertiesOf(type, checker);
  const names = new Set(properties.map((property) => property.name));
  let best: { name: string; shared: number; omitted: readonly string[] } | undefined;
  for (const [name, baseNames] of bases) {
    const omitted = baseNames.filter((baseName) => !names.has(baseName));
    const shared = baseNames.length - omitted.length;
    if (name !== self && omitted.length <= maxOmittedBaseProps && shared > (best?.shared ?? 0)) {
      best = { name, shared, omitted };
    }
  }
  const inherited = new Set(best === undefined ? [] : bases.get(best.name));
  const required = (type.isUnion() ? checker.getPropertiesOfType(type) : properties)
    .filter((property) => !isOptional(property) && property.name !== 'key')
    .map((property) => property.name);
  return {
    heritage:
      best === undefined
        ? undefined
        : best.omitted.length === 0
          ? best.name
          : `Omit<${best.name}, ${best.omitted.map((name) => JSON.stringify(name)).join(' | ')}>`,
    base: best?.name,
    own: properties.filter((property) => !inherited.has(property.name) && !isDeprecated(property, checker)),
    required,
  };
};

/** One named prop type an element reached, rendered in its own language. */
const referencedEntry = (declaration: ts.Declaration, extraction: Extraction): ApiEntryDraft | undefined => {
  const { checker } = extraction;
  if (ts.isInterfaceDeclaration(declaration)) {
    for (const clause of declaration.heritageClauses ?? []) {
      collectReferences(clause, extraction);
    }
    const heritage = (declaration.heritageClauses ?? []).map((clause) => ` ${clause.getText()}`).join('');
    const symbols = declaration.members.flatMap((member): ts.Symbol[] => {
      const symbol = member.name === undefined ? undefined : checker.getSymbolAtLocation(member.name);
      return symbol === undefined || isDeprecated(symbol, checker) ? [] : [symbol];
    });
    const members = symbols.map((symbol) => propertyEntry(symbol, extraction));
    // An object prop's required keys are the misuse the kernel reports (`{ pins }` without `direction`).
    const required = symbols.filter((symbol) => !isOptional(symbol)).map((symbol) => symbol.name);
    const ownSummary = summaryOf(checker.getSymbolAtLocation(declaration.name), checker);
    const summary =
      required.length === 0
        ? ownSummary
        : `Required ${required.join(', ')}${ownSummary === '' ? '' : ` — ${ownSummary}`}`;
    return {
      name: declaration.name.text,
      kind: 'interface',
      category: 'Prop types',
      type: { text: collapse(`interface ${declaration.name.text}${typeParametersText(declaration)}${heritage}`) },
      ...(summary === '' ? {} : { docs: { summary } }),
      ...(members.length === 0 ? {} : { members }),
      source: sourceOf(declaration),
      languageSpecific: typescript,
    };
  }
  if (!ts.isTypeAliasDeclaration(declaration)) {
    return undefined;
  }
  const declared = declaration.type.getText();
  const schema = isSchemaText(declared);
  const text = schema
    ? checker.typeToString(
        checker.getTypeAtLocation(declaration.type),
        undefined,
        ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.InTypeAlias,
      )
    : collapse(declared);
  if (text.length > maxTypeTextLength) {
    return undefined;
  }
  if (!schema) {
    collectReferences(declaration.type, extraction);
  }
  const summary = summaryOf(checker.getSymbolAtLocation(declaration.name), checker);
  return {
    name: `${declaration.name.text}${typeParametersText(declaration)}`,
    kind: 'type',
    category: 'Prop types',
    type: { text },
    ...(summary === '' ? {} : { docs: { summary } }),
    source: sourceOf(declaration),
    languageSpecific: typescript,
  };
};

/** What one tscircuit extraction needs. @internal */
export type TscircuitExtractionConfig = {
  /** Absolute path to `@tscircuit/core`'s `dist/index.d.ts`, as resolved from the tscircuit plugin. */
  readonly coreDeclarations: string;
  /** Absolute path to `@tscircuit/footprinter`'s `dist/index.d.ts`. */
  readonly footprinterDeclarations: string;
  readonly packageVersion: string;
  /** Metadata extractor note, e.g. naming the `@tscircuit/props` version. */
  readonly extractor?: string;
};

const findDeclaration = <T extends ts.InterfaceDeclaration | ts.TypeAliasDeclaration>(
  file: ts.SourceFile,
  guard: (statement: ts.Statement) => statement is T,
  name: string,
): T => {
  const found = file.statements.find((statement): statement is T => guard(statement) && statement.name.text === name);
  if (found === undefined) {
    throw new Error(`${name} not found in ${file.fileName}`);
  }
  return found;
};

const isInterfaceOrAlias = (statement: ts.Statement): statement is ts.InterfaceDeclaration | ts.TypeAliasDeclaration =>
  ts.isInterfaceDeclaration(statement) || ts.isTypeAliasDeclaration(statement);

type BaseDeclaration = ts.InterfaceDeclaration | ts.TypeAliasDeclaration;

/** One entry per intrinsic element, canonical tags first, and the shared bases they list against. */
const elementEntries = (
  registry: ts.InterfaceDeclaration,
  extraction: Extraction,
): { readonly elements: ApiEntryDraft[]; readonly usedBases: Set<string> } => {
  const { checker } = extraction;
  const elements: ApiEntryDraft[] = [];
  const usedBases = new Set<string>();
  const firstTagByProps = new Map<string, string>();
  const ordered = [...registry.members].sort(
    (left, right) =>
      Number(aliasTags.has(left.name?.getText() ?? '')) - Number(aliasTags.has(right.name?.getText() ?? '')),
  );
  for (const member of ordered) {
    const type = ts.isPropertySignature(member) && member.type !== undefined ? member.type : undefined;
    // `<custom>` and `<jscad>` accept anything.
    if (type === undefined || (checker.getTypeFromTypeNode(type).flags & ts.TypeFlags.Any) !== 0) {
      continue;
    }
    const tag = member.name?.getText() ?? '';
    const propsName = collapse(type.getText());
    const shape = propsShape(checker.getTypeFromTypeNode(type), extraction, propsName);
    const sameAs = firstTagByProps.get(propsName);
    if (shape.base !== undefined) {
      usedBases.add(shape.base);
    }
    const required = shape.required.length === 0 ? '' : `, required ${shape.required.join(', ')}`;
    elements.push({
      name: `<${tag}>`,
      kind: 'interface',
      category: elementCategory(tag, shape.base),
      type: { text: `${propsName}${shape.heritage === undefined ? '' : ` extends ${shape.heritage}`}` },
      docs: {
        summary:
          sameAs === undefined ? `JSX element <${tag}> with ${propsName}${required}` : `Same props as <${sameAs}>`,
      },
      ...(sameAs === undefined ? { members: shape.own.map((property) => propertyEntry(property, extraction)) } : {}),
      source: sourceOf(member),
      languageSpecific: typescript,
    });
    if (sameAs === undefined) {
      firstTagByProps.set(propsName, tag);
    }
  }
  return { elements, usedBases };
};

/** Each used base lists what it adds over its own largest base, transitively. */
const baseEntries = (
  usedBases: ReadonlySet<string>,
  declarations: ReadonlyMap<string, BaseDeclaration>,
  extraction: Extraction,
): ApiEntryDraft[] => {
  const bases: ApiEntryDraft[] = [];
  const pending = [...usedBases];
  for (let name = pending.shift(); name !== undefined; name = pending.shift()) {
    const declaration = declarations.get(name);
    if (declaration === undefined || bases.some((entry) => entry.name === name)) {
      continue;
    }
    const shape = propsShape(extraction.checker.getTypeAtLocation(declaration.name), extraction, name);
    if (shape.base !== undefined) {
      pending.push(shape.base);
    }
    bases.push({
      name,
      kind: 'interface',
      category: 'Shared props',
      type: { text: `interface ${name}${shape.heritage === undefined ? '' : ` extends ${shape.heritage}`}` },
      docs: { summary: `Props every element extending ${name} accepts` },
      members: shape.own.map((property) => propertyEntry(property, extraction)),
      source: sourceOf(declaration),
      languageSpecific: typescript,
    });
  }
  return bases;
};

/** Every referenced prop type, sorted by name; rendering one can reference more, which the live set iteration reaches. */
const referencedEntries = (extraction: Extraction, alreadyRendered: Iterable<ts.Declaration>): ApiEntryDraft[] => {
  const rendered = new Set(alreadyRendered);
  const types: ApiEntryDraft[] = [];
  for (const declaration of extraction.referenced) {
    if (!rendered.has(declaration)) {
      rendered.add(declaration);
      const entry = referencedEntry(declaration, extraction);
      if (entry !== undefined) {
        types.push(entry);
      }
    }
  }
  return types.sort((left, right) => left.name.localeCompare(right.name));
};

/** The footprint-string functions, one member each. */
const footprintEntry = (footprinter: ts.SourceFile, extraction: Extraction): ApiEntryDraft => {
  const declaration = findDeclaration(footprinter, ts.isTypeAliasDeclaration, 'Footprinter');
  const type = extraction.checker.getTypeAtLocation(declaration.name);
  // Footprinter's own builder types are not authoring material, so its members collect no references.
  const isolated: Extraction = { ...extraction, referenced: new Set() };
  return {
    name: 'footprint strings',
    kind: 'type',
    category: 'Footprint strings',
    type: { text: 'string' },
    docs: {
      summary:
        'Valid footprint functions — a footprint string is a function name, an optional pin count, then _<param><value> pairs, like soic8_p1.27mm, pinrow6_p2.54mm or 0402',
    },
    members: extraction.checker.getPropertiesOfType(type).map((property) => propertyEntry(property, isolated)),
    source: sourceOf(declaration),
    languageSpecific: typescript,
  };
};

/** The helper exports, through the shared TypeScript front-end, without generated member lists. */
const helperEntries = (program: ts.Program, helpersEntry: string): ApiEntryDraft[] =>
  typescriptEntryDrafts(program, [helpersEntry])
    .filter((entry) => (entry.signatures ?? []).every((signature) => signature.text.length <= maxTypeTextLength))
    .map(({ members: _members, ...entry }) => ({
      ...entry,
      category: 'Helpers',
      ...(entry.name === 'sel'
        ? {
            docs: {
              summary:
                'Typed selector builder — sel.U1.VCC is ".U1 > .VCC", sel.net.GND is "net.GND", sel("U1").VCC takes any reference designator',
            },
          }
        : {}),
    }));

/**
 * Extract the tscircuit authoring surface.
 *
 * @param config - Declaration paths and version.
 * @returns One corpus: elements, shared props, prop types, footprint strings, helpers.
 * @throws When the elements interface, a shared base or `Footprinter` is missing upstream.
 * @internal
 */
export const extractTscircuitApi = (config: TscircuitExtractionConfig): ApiCorpus => {
  const directory = mkdtempSync(join(tmpdir(), 'tau-tscircuit-api-'));
  try {
    const helpersEntry = join(directory, 'helpers.ts');
    writeFileSync(
      helpersEntry,
      `export { ${helperNames.join(', ')} } from ${JSON.stringify(config.coreDeclarations.replace(/\.d\.ts$/u, ''))};\n`,
    );
    const program = ts.createProgram([helpersEntry, config.coreDeclarations, config.footprinterDeclarations], {
      ...typescriptCompilerOptions,
    });
    const checker = program.getTypeChecker();
    const core = program.getSourceFile(config.coreDeclarations);
    const props = program.getSourceFiles().find((file) => file.fileName.endsWith(propsFileSuffix));
    const footprinter = program.getSourceFile(config.footprinterDeclarations);
    if (core === undefined || props === undefined || footprinter === undefined) {
      throw new Error('tscircuit declarations are not in the program');
    }

    const baseDeclarations = new Map(
      sharedBases.map((name) => [name, findDeclaration(props, isInterfaceOrAlias, name)] as const),
    );
    const extraction: Extraction = {
      checker,
      referenced: new Set(),
      bases: new Map(
        [...baseDeclarations].map(([name, declaration]) => [
          name,
          propertiesOf(checker.getTypeAtLocation(declaration.name), checker).map((property) => property.name),
        ]),
      ),
    };

    const { elements, usedBases } = elementEntries(
      findDeclaration(core, ts.isInterfaceDeclaration, 'TscircuitElements'),
      extraction,
    );
    const bases = baseEntries(usedBases, baseDeclarations, extraction);
    const types = referencedEntries(extraction, baseDeclarations.values());

    return createApiCorpus(
      {
        language: 'typescript',
        packageName: '@tscircuit/core',
        packageVersion: config.packageVersion,
        extractor: config.extractor ?? `TypeScript ${ts.version}`,
        extractionDate: new Date().toISOString(),
      },
      [
        ...elements,
        ...bases,
        ...types,
        footprintEntry(footprinter, extraction),
        ...helperEntries(program, helpersEntry),
      ],
    );
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
};
