/**
 * Bambu `.gcode.3mf` container reader and writer.
 *
 * The container is an OPC package (a ZIP with `[Content_Types].xml` and
 * relationships) whose printable payload is the plate G-code member. Member
 * names follow the S-M4 census of real print-ready archives; every member's
 * content is authored here. Output bytes are deterministic: fixed member
 * order, fixed timestamps, no environment-dependent fields.
 *
 * @module
 */

import { strToU8, Unzip, UnzipInflate, unzipSync, zipSync } from 'fflate';
import type { Zippable } from 'fflate';

import { bambuPlates } from '#bambu-studio/types.js';
import { md5Hex, sha256Hex } from '#hashes.js';

/** The plate member every print-ready Bambu container carries. @public */
export const bambuPlateMember = 'Metadata/plate_1.gcode';

/** Media type of a print-ready Bambu container. @public */
export const bambuContainerMediaType = 'application/vnd.bambulab.gcode-3mf';

/** Member names written by {@link writeBambuContainer}, in archive order. @public */
export const bambuContainerMembers = [
  '[Content_Types].xml',
  '_rels/.rels',
  '3D/3dmodel.model',
  bambuPlateMember,
  'Metadata/plate_1.gcode.md5',
  'Metadata/plate_1.json',
  'Metadata/slice_info.config',
  'Metadata/model_settings.config',
] as const;

const thumbnailMember = 'Metadata/plate_1.png';
const plateMetadataMember = 'Metadata/plate_1.json';
const maximumArchiveBytes = 256 * 1024 * 1024;
const maximumEntries = 512;
const maximumExpandedBytes = 512 * 1024 * 1024;
const maximumPlateBytes = 128 * 1024 * 1024;
const sliceInfoMember = 'Metadata/slice_info.config';
const maximumSliceInfoBytes = 1024 * 1024;
const producerScanBytes = 16 * 1024;
const producerPushBytes = 16 * 1024;
const bambuStudioLine = /^; BambuStudio(?: ([\w.-]{1,64}))?$/u;
const referenceEngineLine = '; generated by @taucad/slicer reference engine';
const clientType = /<header_item\s+key="X-BBL-Client-Type"\s+value="([^"<>]{0,64})"/u;
const clientVersion = /<header_item\s+key="X-BBL-Client-Version"\s+value="([\w.-]{1,64})"/u;
const hexColor = /^#[\dA-F]{6}$/iu;
const filamentColorSetting = /^;\s*filament_colour\s*=\s*(.+?)\s*$/mu;
// Some slicers append an alpha byte; the colour is the first three.
const filamentColorEntry = /^#([\dA-F]{6})(?:[\dA-F]{2})?$/iu;
const maximumFilamentColors = 64;
// Each fact lands in a `; key = value` G-code comment: no list separators, quotes or line breaks.
const settingText = /^[\w .+-]{1,64}$/u;
const isMillimetres = (value: number): boolean => Number.isFinite(value) && value > 0 && value <= 10;
// Bambu Studio writes its config block at the head of the plate, Orca at the tail.
const configScanBytes = 64 * 1024;
// ZIP stores DOS local time; a fixed date keeps the archive byte-identical across runs and zones.
const fixedTimestamp = new Date(2000, 0, 1, 0, 0, 0);

/** Input to {@link writeBambuContainer}. @public */
export type WriteBambuContainerInput = Readonly<{
  /** Plate G-code text or bytes. */
  gcode: Uint8Array<ArrayBuffer> | string;
  /** Part name recorded in the 3MF model and the plate metadata. */
  modelName: string;
  /**
   * Build plate identifier recorded in the plate metadata; a Bambu plate id (`'textured-pei'`) is also recorded as
   * Bambu Studio's `curr_bed_type` (`Textured PEI Plate`).
   */
  plate?: string;
  /** Bambu Studio's `printer_model` the plate was sliced for, such as `Bambu Lab X1 Carbon`. */
  printerModel?: string;
  /** Nozzle diameter the plate was sliced for, in millimetres (`nozzle_diameter`). */
  nozzleDiameter?: number;
  /** Material per filament, in filament order, such as `PLA` (`filament_type`). */
  filamentTypes?: readonly string[];
  /** Filament diameter per filament, in filament order, in millimetres (`filament_diameter`). */
  filamentDiameters?: readonly number[];
  /** PNG bytes for the plate thumbnail. */
  thumbnail?: Uint8Array<ArrayBuffer>;
  /**
   * `#RRGGBB` per filament, in filament order: entry *i* is the colour tool `T<i>` prints (`filament_colour`).
   * Nothing is recorded when absent or empty.
   *
   * Every fact given here is recorded where Bambu Studio records it, so a printer's job checks can read what the
   * plate was sliced for: as a setting in a config block at the head of the plate G-code, and each filament's
   * material and colour in `Metadata/slice_info.config`.
   */
  filamentColors?: readonly string[];
}>;

/** What {@link readBambuContainer} recovered from a container. @public */
export type BambuContainer = Readonly<{
  /** The plate G-code bytes. */
  gcode: Uint8Array<ArrayBuffer>;
  /** Lowercase MD5 recorded beside the plate, when that member exists. */
  recordedMd5: string | undefined;
  /** Whether the recorded MD5 matches the plate bytes. */
  md5Verified: boolean;
  /**
   * The `bed_type` recorded in `Metadata/plate_1.json`: a Tau plate id such as `'textured-pei'`
   * from the reference engine, or Bambu Studio's own (`'hot_plate'`, `'textured_plate'`, …).
   * Absent when the member is missing, unreadable or names no plate.
   */
  bedType: string | undefined;
  /**
   * `#RRGGBB` per filament the plate was sliced with, in filament order: entry *i* is the colour tool
   * `T<i>` prints. Read from the plate G-code's `filament_colour` setting in its first 64 KiB, else its
   * last. Empty when the plate records none or an entry is not a colour.
   */
  filamentColors: readonly string[];
  /** Every member with its inflated length and SHA-256 digest, in archive order. */
  members: ReadonlyArray<Readonly<{ name: string; length: number; digest: `sha256:${string}` }>>;
}>;

/**
 * The slicer that produced a Bambu container, as {@link readBambuContainerProducer} recognizes it.
 *
 * `'Bambu Studio'` needs both of its signals: a `; BambuStudio <version>` line in the plate
 * G-code's leading comment block and `X-BBL-Client-Type` `slicer` in `Metadata/slice_info.config`.
 * `'@taucad/slicer reference'` is the reference engine's `; generated by` header line.
 * @public
 */
export type BambuContainerProducer = Readonly<{
  name: 'Bambu Studio' | '@taucad/slicer reference';
  /** The producer's version: the header line's, else `X-BBL-Client-Version`. */
  version?: string;
}>;

const escapeXml = (value: string): string =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');

const xmlHeader = '<?xml version="1.0" encoding="UTF-8"?>\n';

const contentTypes = (thumbnail: boolean): string =>
  `${xmlHeader}<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n` +
  ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n' +
  ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n' +
  ' <Default Extension="gcode" ContentType="text/x.gcode"/>\n' +
  (thumbnail ? ' <Default Extension="png" ContentType="image/png"/>\n' : '') +
  '</Types>\n';

const relationships = (thumbnail: boolean): string =>
  `${xmlHeader}<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n` +
  ' <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n' +
  (thumbnail
    ? ` <Relationship Target="/${thumbnailMember}" Id="rel-2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail"/>\n`
    : '') +
  '</Relationships>\n';

const model = (name: string): string =>
  `${xmlHeader}<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n` +
  ` <metadata name="Title">${name}</metadata>\n` +
  ' <metadata name="Application">@taucad/slicer</metadata>\n' +
  ' <resources/>\n' +
  ' <build/>\n' +
  '</model>\n';

type Filament = Readonly<{ type?: string; color?: string }>;

const sliceInfo = (name: string, nozzleDiameter: number | undefined, filaments: readonly Filament[]): string =>
  `${xmlHeader}<config>\n` +
  ' <plate>\n' +
  '  <metadata key="index" value="1"/>\n' +
  (nozzleDiameter === undefined ? '' : `  <metadata key="nozzle_diameters" value="${String(nozzleDiameter)}"/>\n`) +
  `  <object identify_id="1" name="${name}" skipped="false"/>\n` +
  filaments
    .map(
      ({ type, color }, index) =>
        `  <filament id="${index + 1}"${type === undefined ? '' : ` type="${type}"`}${color === undefined ? '' : ` color="${color}"`}/>\n`,
    )
    .join('') +
  ' </plate>\n' +
  '</config>\n';

// A `; key = value` block like the one Bambu Studio writes (keys in its order), which previews and Bambu tools read.
const configBlock = (settings: ReadonlyArray<readonly [string, string]>): string =>
  `; CONFIG_BLOCK_START\n${settings.map(([key, value]) => `; ${key} = ${value}\n`).join('')}; CONFIG_BLOCK_END\n`;

const modelSettings = (name: string): string =>
  `${xmlHeader}<config>\n` +
  ' <object id="1">\n' +
  `  <metadata key="name" value="${name}"/>\n` +
  ' </object>\n' +
  ' <plate>\n' +
  '  <metadata key="plater_id" value="1"/>\n' +
  `  <metadata key="gcode_file" value="${bambuPlateMember}"/>\n` +
  ' </plate>\n' +
  '</config>\n';

const readBedType = (metadata: string | undefined): string | undefined => {
  if (metadata === undefined) {
    return undefined;
  }
  try {
    const { bed_type: bedType } = JSON.parse(metadata) as { bed_type?: unknown };
    return typeof bedType === 'string' && bedType !== '' && bedType.length <= 64 ? bedType : undefined;
  } catch {
    return undefined;
  }
};

// Views from fflate may sit over any buffer kind; copying pins them to a plain ArrayBuffer.
const copyBytes = (bytes: ArrayLike<number>): Uint8Array<ArrayBuffer> => Uint8Array.from(bytes);

const readFilamentColors = (gcode: Uint8Array<ArrayBuffer>): readonly string[] => {
  const decoder = new TextDecoder();
  const settingIn = (bytes: Uint8Array<ArrayBuffer>): string | undefined =>
    filamentColorSetting.exec(decoder.decode(bytes))?.[1];
  const value =
    settingIn(gcode.subarray(0, configScanBytes)) ??
    (gcode.byteLength > configScanBytes ? settingIn(gcode.subarray(-configScanBytes)) : undefined);
  const entries = value?.split(';') ?? [];
  if (entries.length > maximumFilamentColors) {
    return [];
  }
  const colors: string[] = [];
  for (const entry of entries) {
    const hex = filamentColorEntry.exec(entry.trim())?.[1];
    if (hex === undefined) {
      return [];
    }
    colors.push(`#${hex.toUpperCase()}`);
  }
  return colors;
};

const assertSliceFacts = ({
  filamentTypes: types = [],
  filamentDiameters: diameters = [],
  printerModel,
  nozzleDiameter,
}: WriteBambuContainerInput): void => {
  if (
    types.length > maximumFilamentColors ||
    diameters.length > maximumFilamentColors ||
    !types.every((type) => settingText.test(type)) ||
    !diameters.every((diameter) => isMillimetres(diameter)) ||
    (printerModel !== undefined && !settingText.test(printerModel)) ||
    (nozzleDiameter !== undefined && !isMillimetres(nozzleDiameter))
  ) {
    throw new TypeError('SLICER_CONTAINER_SETTING_INVALID');
  }
};

/**
 * Write one print-ready Bambu container around plate G-code.
 *
 * With any slice fact (filament colours, materials or diameters, nozzle, printer, a Bambu plate), the plate starts
 * with a config block recording them; the rest of the plate is the given G-code unchanged.
 *
 * @param input - Plate G-code, part name, plate identifier, slice facts and optional thumbnail.
 * @returns Deterministic container bytes.
 * @throws TypeError - `SLICER_CONTAINER_PLATE_EMPTY` for empty G-code, `SLICER_CONTAINER_COLOR_INVALID` for a
 * filament colour that is not `#RRGGBB` or more than 64 colours, `SLICER_CONTAINER_SETTING_INVALID` for a printer
 * model or material that is not 1–64 letters, digits, spaces, `.`, `+` or `-`, a diameter that is not over 0 and at
 * most 10 mm, or more than 64 filaments.
 * @public
 * @example <caption>Wrap reference G-code for a Bambu upload</caption>
 * ```typescript
 * import { writeBambuContainer } from '@taucad/slicer/container';
 *
 * const bytes = writeBambuContainer({ gcode: 'G28\nG90\n', modelName: 'bracket', plate: 'textured-pei' });
 * ```
 * @example <caption>Record the filament colour the preview draws</caption>
 * ```typescript
 * import { writeBambuContainer } from '@taucad/slicer/container';
 *
 * const bytes = writeBambuContainer({ gcode: 'G28\nG90\n', modelName: 'bracket', filamentColors: ['#F5A623'] });
 * ```
 */
export const writeBambuContainer = (input: WriteBambuContainerInput): Uint8Array<ArrayBuffer> => {
  const body = typeof input.gcode === 'string' ? copyBytes(strToU8(input.gcode)) : input.gcode;
  if (body.byteLength === 0) {
    throw new TypeError('SLICER_CONTAINER_PLATE_EMPTY');
  }
  const colors = input.filamentColors ?? [];
  if (colors.length > maximumFilamentColors || !colors.every((color) => hexColor.test(color))) {
    throw new TypeError('SLICER_CONTAINER_COLOR_INVALID');
  }
  const recorded = colors.map((color) => color.toUpperCase());
  const types = input.filamentTypes ?? [];
  const diameters = input.filamentDiameters ?? [];
  const { printerModel, nozzleDiameter } = input;
  assertSliceFacts(input);
  const bedType = bambuPlates.find(({ id }) => id === input.plate)?.bambuName;
  const stated: ReadonlyArray<readonly [string, string | undefined]> = [
    ['curr_bed_type', bedType],
    ['filament_colour', recorded.join(';')],
    ['filament_diameter', diameters.map(String).join(',')],
    ['filament_type', types.join(';')],
    ['nozzle_diameter', nozzleDiameter === undefined ? undefined : String(nozzleDiameter)],
    ['printer_model', printerModel],
  ];
  const settings = stated.flatMap(
    ([key, value]): Array<readonly [string, string]> => (value === undefined || value === '' ? [] : [[key, value]]),
  );
  let gcode = body;
  if (settings.length > 0) {
    const block = strToU8(configBlock(settings));
    gcode = new Uint8Array(block.byteLength + body.byteLength);
    gcode.set(block);
    gcode.set(body, block.byteLength);
  }
  const name = escapeXml(input.modelName);
  const thumbnail = input.thumbnail !== undefined;
  // eslint-disable-next-line @typescript-eslint/naming-convention -- Bambu plate_1.json field names are fixed.
  const plate = JSON.stringify({ version: 2, name: input.modelName, bed_type: input.plate ?? 'unspecified' });
  const entries: Zippable = {
    '[Content_Types].xml': strToU8(contentTypes(thumbnail)),
    '_rels/.rels': strToU8(relationships(thumbnail)),
    '3D/3dmodel.model': strToU8(model(name)),
    [bambuPlateMember]: gcode,
    'Metadata/plate_1.gcode.md5': strToU8(md5Hex(gcode)),
    [plateMetadataMember]: strToU8(plate),
    'Metadata/slice_info.config': strToU8(
      sliceInfo(
        name,
        nozzleDiameter,
        Array.from({ length: Math.max(recorded.length, types.length) }, (_, index) => ({
          ...(types[index] === undefined ? {} : { type: types[index] }),
          ...(recorded[index] === undefined ? {} : { color: recorded[index] }),
        })),
      ),
    ),
    'Metadata/model_settings.config': strToU8(modelSettings(name)),
    ...(input.thumbnail === undefined ? {} : { [thumbnailMember]: [input.thumbnail, { level: 0 }] as const }),
  };
  return copyBytes(zipSync(entries, { level: 6, mtime: fixedTimestamp }));
};

const safeMemberName = (name: string): string => {
  if (
    name.length === 0 ||
    name.length > 512 ||
    !name.isWellFormed() ||
    name.includes('\\') ||
    name.startsWith('/') ||
    name.endsWith('/') ||
    name.split('/').some((segment) => segment === '' || segment === '.' || segment === '..')
  ) {
    throw new TypeError('SLICER_CONTAINER_MEMBER_INVALID');
  }
  return name.normalize('NFC');
};

/**
 * Read a bounded Bambu container: the plate G-code, its recorded MD5 and every member digest.
 *
 * Refuses archives over 256 MiB, more than 512 members, members that expand past
 * 512 MiB in total, plates over 128 MiB, unsafe member names and archives
 * without a plate.
 *
 * @param bytes - The archive to inspect.
 * @returns The plate and member inventory.
 * @throws TypeError - With a `SLICER_CONTAINER_*` code when the archive is refused.
 * @public
 * @example <caption>Recover the plate for the printer viewer</caption>
 * ```typescript
 * import { readBambuContainer } from '@taucad/slicer/container';
 * import { parseGcode } from '@taucad/slicer/toolpath';
 *
 * const container = readBambuContainer(new Uint8Array(await new Response(new Blob([])).arrayBuffer()));
 * const program = parseGcode(container.gcode);
 * ```
 */
export const readBambuContainer = (bytes: Uint8Array<ArrayBuffer>): BambuContainer => {
  if (bytes.byteLength === 0 || bytes.byteLength > maximumArchiveBytes) {
    throw new TypeError('SLICER_CONTAINER_LIMIT');
  }
  const names: string[] = [];
  let expanded = 0;
  let extracted: ReturnType<typeof unzipSync>;
  try {
    extracted = unzipSync(bytes, {
      filter(file) {
        if (file.name.endsWith('/')) {
          return false;
        }
        const name = safeMemberName(file.name);
        expanded += file.originalSize;
        if (
          names.length >= maximumEntries ||
          expanded > maximumExpandedBytes ||
          names.some((existing) => existing.toLowerCase() === name.toLowerCase())
        ) {
          throw new TypeError('SLICER_CONTAINER_LIMIT');
        }
        if (name === bambuPlateMember && (file.originalSize === 0 || file.originalSize > maximumPlateBytes)) {
          throw new TypeError('SLICER_CONTAINER_PLATE_INVALID');
        }
        names.push(name);
        return true;
      },
    });
  } catch (error) {
    if (error instanceof TypeError && error.message.startsWith('SLICER_CONTAINER_')) {
      throw error;
    }
    throw new TypeError('SLICER_CONTAINER_INVALID', { cause: error });
  }
  const plate = extracted[bambuPlateMember];
  if (plate === undefined) {
    throw new TypeError('SLICER_CONTAINER_PLATE_MISSING');
  }
  const recorded = extracted['Metadata/plate_1.gcode.md5'];
  const metadata = extracted[plateMetadataMember];
  const recordedMd5 = recorded === undefined ? undefined : new TextDecoder().decode(recorded).trim().toLowerCase();
  const gcode = copyBytes(plate);
  return {
    gcode,
    recordedMd5,
    bedType: readBedType(metadata === undefined ? undefined : new TextDecoder().decode(metadata)),
    filamentColors: readFilamentColors(gcode),
    md5Verified: recordedMd5 !== undefined && recordedMd5 === md5Hex(gcode),
    members: names.map((name) => {
      const member = extracted[name]!;
      return { name, length: member.byteLength, digest: `sha256:${sha256Hex(copyBytes(member))}` };
    }),
  };
};

const producerOf = (head: string, sliceInfo: string): BambuContainerProducer | undefined => {
  for (const line of head.split('\n', 64)) {
    const text = line.trimEnd();
    if (text === referenceEngineLine) {
      return { name: '@taucad/slicer reference' };
    }
    const studio = bambuStudioLine.exec(text);
    if (studio) {
      if (clientType.exec(sliceInfo)?.[1] !== 'slicer') {
        return undefined;
      }
      const version = studio[1] ?? clientVersion.exec(sliceInfo)?.[1];
      return version === undefined ? { name: 'Bambu Studio' } : { name: 'Bambu Studio', version };
    }
    if (text !== '' && !text.startsWith(';')) {
      return undefined;
    }
  }
  return undefined;
};

/**
 * Name the slicer that produced a Bambu container without inflating the whole plate.
 *
 * Reads at most the first 16 KiB of `Metadata/plate_1.gcode` and a `Metadata/slice_info.config`
 * of at most 1 MiB. Archives that are empty, over 256 MiB or unreadable name no producer.
 *
 * @param bytes - The archive to inspect.
 * @returns The recognized producer, or `undefined` when neither Bambu Studio nor the reference engine made it.
 * @public
 * @example <caption>Show who sliced a file before it goes to a printer</caption>
 * ```typescript
 * import { readBambuContainerProducer } from '@taucad/slicer/container';
 *
 * const producer = readBambuContainerProducer(new Uint8Array(await new Response(new Blob([])).arrayBuffer()));
 * const label = producer ? `${producer.name} ${producer.version ?? ''}`.trim() : 'Unknown slicer';
 * ```
 */
export const readBambuContainerProducer = (bytes: Uint8Array<ArrayBuffer>): BambuContainerProducer | undefined => {
  if (bytes.byteLength === 0 || bytes.byteLength > maximumArchiveBytes) {
    return undefined;
  }
  try {
    const sliceInfo = unzipSync(bytes, {
      filter: (file) => file.name === sliceInfoMember && file.originalSize <= maximumSliceInfoBytes,
    })[sliceInfoMember];
    // Stream only until the plate's head is in hand; the rest of the plate is never inflated.
    const decoder = new TextDecoder();
    const plate = { head: '', bytes: 0, complete: false };
    const unzip = new Unzip((file) => {
      if (file.name !== bambuPlateMember || plate.complete) {
        return;
      }
      file.ondata = (error, chunk, final) => {
        if (error) {
          throw error;
        }
        if (!plate.complete) {
          const taken = chunk.subarray(0, producerScanBytes - plate.bytes);
          plate.head += decoder.decode(taken, { stream: true });
          plate.bytes += taken.byteLength;
          plate.complete = final || plate.bytes >= producerScanBytes;
        }
      };
      file.start();
    });
    unzip.register(UnzipInflate);
    for (let offset = 0; offset < bytes.byteLength; offset += producerPushBytes) {
      unzip.push(bytes.subarray(offset, offset + producerPushBytes), offset + producerPushBytes >= bytes.byteLength);
      if (plate.complete) {
        break;
      }
    }
    return producerOf(plate.head, sliceInfo === undefined ? '' : decoder.decode(sliceInfo));
  } catch {
    return undefined;
  }
};

/** Preview payload and producer, without an all-member inventory. @public */
export type BambuPreview = Omit<BambuContainer, 'members'> & Readonly<{ producer?: BambuContainerProducer }>;

/**
 * Extract only the plate and bounded preview metadata after validating the complete ZIP directory.
 * The inventory reader retains its all-member contract. Unselected model/thumbnail bytes never inflate here.
 *
 * @param bytes - The sliced archive.
 * @returns Verified plate bytes and recorded metadata.
 * @throws TypeError - A `SLICER_CONTAINER_*` refusal for unsafe or malformed archives.
 * @public
 */
export const readBambuPreview = (bytes: Uint8Array<ArrayBuffer>): BambuPreview => {
  if (bytes.byteLength === 0 || bytes.byteLength > maximumArchiveBytes) {
    throw new TypeError('SLICER_CONTAINER_LIMIT');
  }
  const names = new Set<string>();
  const limits = new Map<string, number>([
    [bambuPlateMember, maximumPlateBytes],
    ['Metadata/plate_1.gcode.md5', 128],
    [plateMetadataMember, maximumSliceInfoBytes],
    [sliceInfoMember, maximumSliceInfoBytes],
  ]);
  let expanded = 0;
  try {
    // No member is materialized in this admission pass; even unselected members are validated.
    unzipSync(bytes, {
      filter(file) {
        const isDirectory = file.name.endsWith('/');
        const name = safeMemberName(isDirectory ? file.name.slice(0, -1) : file.name);
        const key = name.toLowerCase();
        expanded += file.originalSize;
        if (names.has(key) || names.size >= maximumEntries || expanded > maximumExpandedBytes) {
          throw new TypeError('SLICER_CONTAINER_LIMIT');
        }
        names.add(key);
        const limit = limits.get(name);
        if (
          limit !== undefined &&
          (file.originalSize > limit || (name === bambuPlateMember && file.originalSize === 0))
        ) {
          throw new TypeError('SLICER_CONTAINER_PLATE_INVALID');
        }
        return false;
      },
    });
    const selected: Record<string, Uint8Array<ArrayBuffer>> = {};
    const localNames = new Set<string>();
    const unzip = new Unzip((file) => {
      const name = safeMemberName(file.name.endsWith('/') ? file.name.slice(0, -1) : file.name);
      if (!names.has(name.toLowerCase()) || localNames.has(name.toLowerCase())) {
        throw new TypeError('SLICER_CONTAINER_INVALID');
      }
      localNames.add(name.toLowerCase());
      const limit = limits.get(file.name);
      if (limit === undefined) {
        return;
      }
      const chunks: Array<Uint8Array<ArrayBuffer>> = [];
      let length = 0;
      file.ondata = (error, data, final) => {
        if (error) {
          throw error;
        }
        length += data.byteLength;
        if (length > limit) {
          file.terminate();
          throw new TypeError('SLICER_CONTAINER_LIMIT');
        }
        chunks.push(data);
        if (final) {
          const output = new Uint8Array(length);
          let offset = 0;
          for (const chunk of chunks) {
            output.set(chunk, offset);
            offset += chunk.byteLength;
          }
          chunks.length = 0;
          selected[file.name] = output;
        }
      };
      file.start();
    });
    unzip.register(UnzipInflate);
    // Bound each inflater emission too: a lying directory cannot request an unbounded output allocation.
    const pushBytes = 4096;
    for (let offset = 0; offset < bytes.byteLength; offset += pushBytes) {
      unzip.push(bytes.subarray(offset, offset + pushBytes), offset + pushBytes >= bytes.byteLength);
    }
    const plate = selected[bambuPlateMember];
    if (!plate?.byteLength) {
      throw new TypeError('SLICER_CONTAINER_PLATE_MISSING');
    }
    const gcode = plate;
    const decoder = new TextDecoder();
    const recorded = selected['Metadata/plate_1.gcode.md5'];
    const recordedMd5 = recorded === undefined ? undefined : decoder.decode(recorded).trim().toLowerCase();
    const md5Verified = recordedMd5 !== undefined && recordedMd5 === md5Hex(gcode);
    if (recordedMd5 !== undefined && !md5Verified) {
      throw new TypeError('SLICER_CONTAINER_CHECKSUM_INVALID');
    }
    const metadata = selected[plateMetadataMember];
    const sliceInfo = selected[sliceInfoMember];
    return {
      gcode,
      recordedMd5,
      md5Verified,
      bedType: readBedType(metadata === undefined ? undefined : decoder.decode(metadata)),
      filamentColors: readFilamentColors(gcode),
      producer: producerOf(
        decoder.decode(gcode.subarray(0, producerScanBytes)),
        sliceInfo === undefined ? '' : decoder.decode(sliceInfo),
      ),
    };
  } catch (error) {
    if (error instanceof TypeError && error.message.startsWith('SLICER_CONTAINER_')) {
      throw error;
    }
    throw new TypeError('SLICER_CONTAINER_INVALID', { cause: error });
  }
};

/** Bambu Studio's header names the filaments a plate prints, counted from 1: `; filament: 1,2`. */
const printedFilaments = /^;\s*filament:\s*(\d+(?:\s*,\s*\d+)*)\s*$/mu;
/** Bambu Studio writes that header first, so the reader looks no further. */
const headerBytes = 65_536;
const headerDecoder = new TextDecoder();

/**
 * The colours of the filaments a slice prints, in filament order: entry *i* is filament *i* + 1,
 * which the plate prints with `T<i>`. Bambu Studio records a colour for every filament preset it
 * loaded, and a one-part slice loads every preset it is given, so the list stops at the last
 * filament its header says the plate prints. The planner and the Print pane's slice summary read
 * a slice's filaments through it.
 *
 * @param container - The slice as `readBambuContainer` read it.
 * @returns `#RRGGBB` per printed filament; empty when the slice records no colour.
 * @public
 */
export const slicedFilamentColors = ({
  gcode,
  filamentColors,
}: Pick<BambuContainer, 'gcode' | 'filamentColors'>): readonly string[] => {
  const printed = printedFilaments.exec(headerDecoder.decode(gcode.subarray(0, headerBytes)))?.[1];
  if (printed === undefined) {
    return filamentColors;
  }
  let last = 0;
  for (const id of printed.split(',')) {
    last = Math.max(last, Number(id));
  }
  return filamentColors.slice(0, last);
};
