// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
import { describe, it, expectGeo } from 'geospec';
import { loadModel } from 'geospec/model';
describe("Parallel key", () => {
it("default", async () => {
const parameters = {};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 24,
  "z": 6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 817.6450032938487, lessThanOrEqual: 817.6470032938487 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 24,
  "z": 6
}, tolerance: 0.1 });
});
it("width-minimum", async () => {
const parameters = {
  "width": 4.800000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 4.800000000000001,
  "y": 24,
  "z": 6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 661.5324421080634, lessThanOrEqual: 661.5344421080633 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 4.800000000000001,
  "y": 24,
  "z": 6
}, tolerance: 0.1 });
});
it("width-maximum", async () => {
const parameters = {
  "width": 7.199999999999999
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 7.199999999999999,
  "y": 24,
  "z": 6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 970.0492447431423, lessThanOrEqual: 970.0512447431422 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 7.199999999999999,
  "y": 24,
  "z": 6
}, tolerance: 0.1 });
});
it("length-minimum", async () => {
const parameters = {
  "length": 19.200000000000003
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 19.200000000000003,
  "z": 6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 644.845003293849, lessThanOrEqual: 644.847003293849 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 19.200000000000003,
  "z": 6
}, tolerance: 0.1 });
});
it("length-maximum", async () => {
const parameters = {
  "length": 28.799999999999997
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 28.799999999999997,
  "z": 6
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 990.4450032938487, lessThanOrEqual: 990.4470032938486 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 28.799999999999997,
  "z": 6
}, tolerance: 0.1 });
});
it("height-minimum", async () => {
const parameters = {
  "height": 4.800000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 24,
  "z": 4.800000000000001
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 654.1158026350791, lessThanOrEqual: 654.1178026350791 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 24,
  "z": 4.800000000000001
}, tolerance: 0.1 });
});
it("height-maximum", async () => {
const parameters = {
  "height": 7.199999999999999
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 24,
  "z": 7.199999999999999
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 981.1742039526184, lessThanOrEqual: 981.1762039526184 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 6,
  "y": 24,
  "z": 7.199999999999999
}, tolerance: 0.1 });
});
it("combined-min", async () => {
const parameters = {
  "width": 4.800000000000001,
  "length": 19.200000000000003,
  "height": 4.800000000000001
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 4.800000000000001,
  "y": 19.200000000000003,
  "z": 4.800000000000001
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 418.63375368645075, lessThanOrEqual: 418.6357536864507 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 4.800000000000001,
  "y": 19.200000000000003,
  "z": 4.800000000000001
}, tolerance: 0.1 });
});
it("combined-max", async () => {
const parameters = {
  "width": 7.199999999999999,
  "length": 28.799999999999997,
  "height": 7.199999999999999
};
const exact = await loadModel({ file: 'main.ts', parameters, format: 'step' });
expectGeo(exact).toHaveNoDiagnostics();
expectGeo(exact).toBeValidBrep({ closedShells: true, maxTolerance: 0.01 });
expectGeo(exact).toHaveStepUnits({ unit: 'mm' });
expectGeo(exact).toHaveBoundingBox({ size: {
  "x": 7.199999999999999,
  "y": 28.799999999999997,
  "z": 7.199999999999999
}, tolerance: 0.05 });
expectGeo(exact).toHaveTopologyCounts({ solids: 1 });
expectGeo(exact).toHaveVolume({ value: { greaterThanOrEqual: 1412.8912936917704, lessThanOrEqual: 1412.8932936917704 } });
const mesh = await loadModel({ file: 'main.ts', parameters, format: 'glb' });
expectGeo(mesh).toHaveNoDiagnostics();
expectGeo(mesh).toBeWatertight();
expectGeo(mesh).toHaveMeshIntegrity({ finitePositions: true, degenerateTriangles: { count: 0 } });
expectGeo(mesh).toHaveBoundingBox({ size: {
  "x": 7.199999999999999,
  "y": 28.799999999999997,
  "z": 7.199999999999999
}, tolerance: 0.1 });
});
});
