// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "diameter": 30,
  "length": 8
};
export const parameterDomains = {
  "diameter": {
    "min": 27,
    "max": 33
  },
  "length": {
    "min": 7.2,
    "max": 8.8
  }
};
export const design = "blind-flange";
