/** Regenerates the checked-in UI SVG sprite and its icon-id type. */
import { globSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import process from 'node:process';
import SVGSprite from 'svg-sprite';

const uiDirectory = join(import.meta.dirname, '..');
const rawDirectory = join(uiDirectory, 'app', 'components', 'icons', 'raw');
const generatedDirectory = join(uiDirectory, 'app', 'components', 'icons', 'generated');
const paymentIconIds = new Set([
  'amazon-pay',
  'amex',
  'diners-club',
  'discover',
  'jcb',
  'mastercard',
  'paypal',
  'unionpay',
  'usd',
  'visa',
]);

const compileSprite = async (iconPaths: readonly string[], name: string) => {
  const spriter = new SVGSprite({
    dest: generatedDirectory,
    mode: { symbol: { sprite: `../${name}` } },
    shape: {},
    svg: { xmlDeclaration: false },
  });

  for (const iconPath of iconPaths) {
    spriter.add(iconPath, relative(rawDirectory, iconPath), readFileSync(iconPath, 'utf8'));
  }

  return spriter.compileAsync();
};

const generateSvgSprite = async (): Promise<void> => {
  const iconPaths = globSync(join(rawDirectory, '**', '*.svg')).sort();
  const paymentIconPaths = iconPaths.filter((iconPath) =>
    paymentIconIds.has(relative(rawDirectory, iconPath).slice(0, -4)),
  );
  const baseIconPaths = iconPaths.filter((iconPath) => !paymentIconPaths.includes(iconPath));
  const [{ result }, { result: paymentResult }] = await Promise.all([
    compileSprite(baseIconPaths, 'sprite.svg'),
    compileSprite(paymentIconPaths, 'payment-sprite.svg'),
  ]);
  const iconIds = iconPaths.map((iconPath) => `'${relative(rawDirectory, iconPath).slice(0, -4)}'`);
  const typeDeclaration = [
    '/* this file was generated by generate-svg-sprite.mts */',
    `export type SvgIcons = ${iconIds.join(' | ')}`,
    '',
  ].join('\n');
  const { sprite } = result.symbol;
  const { sprite: paymentSprite } = paymentResult.symbol;

  mkdirSync(generatedDirectory, { recursive: true });
  writeFileSync(sprite.path, sprite.contents.toString());
  writeFileSync(paymentSprite.path, paymentSprite.contents.toString());
  writeFileSync(join(generatedDirectory, 'svg-icons.d.ts'), typeDeclaration);

  console.info(`✓ generated ${relative(uiDirectory, sprite.path)}`);
  console.info(`✓ generated ${relative(uiDirectory, paymentSprite.path)}`);
  console.info(`✓ generated ${relative(uiDirectory, join(generatedDirectory, 'svg-icons.d.ts'))}`);
};

try {
  await generateSvgSprite();
} catch (error) {
  console.error('SVG sprite generation failed:', error);
  process.exit(1);
}
