import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import process from 'node:process';
import type { LanguageRegistration } from 'shiki';
import python from 'shiki/langs/python.mjs';
import { defaultJavaScriptRegexConstructor } from 'shiki/engine/javascript';

// Precompile Python's cross-rule quote backreferences as separate literal-delimiter rules.
// Usage: node apps/ui/scripts/precompile-python.mts [--check]. No environment variables required.
// Exits 0 on success, 1 on unsupported grammar changes or stale generated output.
type Rule = NonNullable<LanguageRegistration['repository']>[string];

const splitRule = (rule: Rule, original: string): string[] => {
  const beginSource = rule.begin;
  const endSource = rule.end;
  if (typeof beginSource !== 'string' || typeof endSource !== 'string') {
    throw new TypeError('Python quote rule must have begin and end patterns');
  }
  const quoteAlternatives = beginSource.includes(`'''|"""|["']`)
    ? `'''|"""|["']`
    : beginSource.includes(`'''|"""`)
      ? `'''|"""`
      : `["']`;
  if (!beginSource.includes(quoteAlternatives)) {
    throw new Error(`Unsupported Python quote pattern: ${beginSource}`);
  }
  const delimiters =
    quoteAlternatives === `'''|"""|["']`
      ? ["'''", '"""', "'", '"']
      : quoteAlternatives === `'''|"""`
        ? ["'''", '"""']
        : ["'", '"'];
  return delimiters.map((delimiter) => {
    const begin = defaultJavaScriptRegexConstructor(beginSource.replace(quoteAlternatives, delimiter), {
      target: 'ES2024',
    });
    const end = defaultJavaScriptRegexConstructor(endSource.replaceAll(/\\[1-9]/gu, delimiter), { target: 'ES2024' });
    return `{ ...${original}, begin: ${begin}, end: ${end} }`;
  });
};

const main = (): void => {
  const grammar = Array.isArray(python) ? python[0]! : python;
  const overrides: string[] = [];
  for (const [key, rule] of Object.entries(grammar.repository)) {
    const original = `repository[${JSON.stringify(key)}]!`;
    if (typeof rule.end === 'string' && /\\[1-9]/u.test(rule.end)) {
      overrides.push(`${JSON.stringify(key)}: { patterns: [${splitRule(rule, original).join(',\n')}] }`);
    } else if (rule.patterns?.some((pattern) => typeof pattern.end === 'string' && /\\[1-9]/u.test(pattern.end))) {
      const patterns = rule.patterns.flatMap((pattern, index) => {
        const expression = `${original}.patterns![${index}]!`;
        return typeof pattern.end === 'string' && /\\[1-9]/u.test(pattern.end)
          ? splitRule(pattern, expression)
          : [expression];
      });
      overrides.push(`${JSON.stringify(key)}: { ...${original}, patterns: [${patterns.join(',\n')}] }`);
    }
  }
  if (overrides.length === 0) {
    throw new Error('No Python quote backreferences found');
  }
  const destination = resolve(import.meta.dirname, '../app/lib/python-language/python-shiki-precompiled.ts');
  const source = `// Generated by node apps/ui/scripts/precompile-python.mts; do not edit.
// Python grammar: Shiki / MagicPython (MIT), https://github.com/MagicStack/MagicPython.
// Split cross-rule backreferences before precompilation; the raw engine only needs literal regexes.
import python from '@shikijs/langs-precompiled/python';
const grammar = python[0]!;
const { repository } = grammar;
const languages = [{ ...grammar, repository: { ...repository, ${overrides.join(',\n')} } }];
export default languages;
`;
  const formatted = execFileSync(
    resolve(import.meta.dirname, '../../../node_modules/.bin/oxfmt'),
    ['--stdin-filepath', destination],
    { input: source, encoding: 'utf8' },
  );
  if (process.argv.includes('--check')) {
    if (readFileSync(destination, 'utf8') !== formatted) {
      throw new Error('Python precompiled grammar is stale; regenerate it');
    }
  } else {
    writeFileSync(destination, formatted);
  }
};

try {
  main();
} catch (error) {
  console.error('Python grammar precompilation failed:', error);
  process.exit(1);
}
