/**
 * The one table naming every package that owns a skill bundle, and the run that
 * regenerates all of them.
 *
 * Everything an owner cannot derive from its API — slug, title, description,
 * when to activate, and the axis its reference files are grouped along — is
 * declared here once. Everything else is read: the corpus from its extractor or
 * its committed artifact, the authored prose from the owner's `agent/doctrine.md`,
 * and the version from the owner's own `package.json`, because a bundle ships in
 * the same tarball at the same version as the API it describes (R10).
 *
 * The grouping axis is explicit per owner and never inferred, for the reason
 * `shard-plan.ts` gives: no single field is populated across every language.
 *
 * @module
 */

import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import type { TauSkillsManifest } from '#bundle/bundle.types.js';
import { doctrineFile, skillsManifestFile } from '#bundle/bundle.types.js';
import type { WrittenBundle } from '#bundle/write-bundle.js';
import { readDoctrine, writeCorpusBundle, writeDoctrineBundle } from '#bundle/write-bundle.js';
import { loadKclCorpus } from '#languages/kcl/extract.js';
import { loadOpenscadCorpus } from '#languages/openscad/extract.js';
import { extractTypescriptApi } from '#languages/typescript/extract.js';
import type { ApiCorpus, ApiEntry, ApiSignature } from '#model/api-corpus.types.js';

/** Workspace root, from this file's own location. @internal */
const workspaceRoot = fileURLToPath(new URL('../../../../', import.meta.url));

const generatedRoot = fileURLToPath(new URL('../generated/', import.meta.url));

const readJson = <T>(path: string): T => JSON.parse(readFileSync(path, 'utf8')) as T;

const resourcesModuleFile = 'resources.js';
const resourcesTypesFile = 'resources.d.ts';

const resourcesTypes = `declare const bundles: readonly {
  readonly slug: string;
  readonly name: string;
  readonly description: string;
  readonly version: string;
  readonly whenToUse: string;
  readonly body: string;
  readonly fingerprint: string;
  readonly files: readonly {
    readonly path: string;
    readonly url: string;
    readonly byteLength: number;
    readonly lineCount: number;
    readonly contentKind: "text";
    readonly mediaType: "text/markdown";
    readonly sha256: string;
  }[];
}[];
export default bundles;
`;

const sha256 = (bytes: Uint8Array<ArrayBuffer>): string => createHash('sha256').update(bytes).digest('hex');

const lineCount = (bytes: Uint8Array<ArrayBuffer>): number => {
  let count = 1;
  for (const byte of bytes) {
    if (byte === 0x0a) {
      count++;
    }
  }
  return count;
};

/** Render the browser-and-Node resource module beside one owner's manifest. */
const renderResourcesModule = async (agentDirectory: string, declaration: TauSkillsManifest['bundles'][number]) => {
  const files = await Promise.all(
    declaration.files.map(async (path) => {
      if (!path.endsWith('.md')) {
        throw new Error(`skill resource must be Markdown: ${declaration.slug}/${path}`);
      }
      const bytes = new Uint8Array(await readFile(join(agentDirectory, declaration.directory, path)));
      return {
        path,
        byteLength: bytes.byteLength,
        lineCount: lineCount(bytes),
        sha256: sha256(bytes),
      };
    }),
  );
  const fingerprint = sha256(
    new TextEncoder().encode(JSON.stringify(files.map(({ path, sha256: digest }) => ({ path, sha256: digest })))),
  );
  const resourceRows = files
    .map(
      (file) =>
        `      Object.freeze({ path: ${JSON.stringify(file.path)}, url: new URL(${JSON.stringify(`./${declaration.directory}/${file.path}`)}, import.meta.url).href, byteLength: ${String(file.byteLength)}, lineCount: ${String(file.lineCount)}, contentKind: 'text', mediaType: 'text/markdown', sha256: ${JSON.stringify(file.sha256)} })`,
    )
    .join(',\n');
  return `/* Generated by @taucad/api-extractor. Do not edit. */\nexport default Object.freeze([\n  Object.freeze({\n    slug: ${JSON.stringify(declaration.slug)},\n    name: ${JSON.stringify(declaration.name)},\n    description: ${JSON.stringify(declaration.description)},\n    version: ${JSON.stringify(declaration.version)},\n    whenToUse: ${JSON.stringify(declaration.whenToUse)},\n    body: ${JSON.stringify(declaration.body)},\n    fingerprint: ${JSON.stringify(fingerprint)},\n    files: Object.freeze([\n${resourceRows}\n    ]),\n  }),\n]);\n`;
};

/** A package's declared version, read from the installed or workspace manifest. */
const versionOf = (packageDirectory: string): string =>
  readJson<{ readonly version: string }>(join(packageDirectory, 'package.json')).version;

/** A committed corpus artifact under `src/generated`. */
const committedCorpus =
  (relativePath: string): (() => ApiCorpus) =>
  (): ApiCorpus =>
    readJson<ApiCorpus>(join(generatedRoot, relativePath));

/**
 * A TypeScript surface, extracted with the checker.
 *
 * The version always comes from the installed package, because that is what the
 * declarations describe. `sourceRoot` redirects only the entry point, for the one
 * owner whose declarations ship as a committed module tree rather than a package.
 */
const typescriptCorpus = (packageName: string, entryPoint: string, sourceRoot?: string) => (): ApiCorpus => {
  const installed = join(workspaceRoot, 'node_modules', packageName);
  return extractTypescriptApi({
    packageName,
    packageVersion: versionOf(installed),
    entryPoints: [join(sourceRoot ?? installed, entryPoint)],
  });
};

type BundledTypescriptPackage = {
  readonly content: string;
  readonly files: Readonly<Record<string, string>>;
  readonly packageJson: {
    readonly exports: Readonly<Record<string, { readonly types: string }>>;
  };
};

/** Extract a TypeScript corpus from the committed declaration bundle produced for GeoSpec. */
const bundledTypescriptCorpus =
  (relativePath: string, packageName: string, packageDirectory: string) => (): ApiCorpus => {
    const bundled = readJson<Record<string, BundledTypescriptPackage>>(join(generatedRoot, relativePath))[packageName];
    if (bundled === undefined) {
      throw new Error(`missing ${packageName} declaration bundle in ${relativePath}`);
    }

    const directory = mkdtempSync(join(tmpdir(), `tau-${packageName}-api-`));
    try {
      const files = { 'index.d.ts': bundled.content, ...bundled.files };
      for (const [file, content] of Object.entries(files)) {
        const path = join(directory, file);
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, content, 'utf8');
      }
      return extractTypescriptApi({
        packageName,
        packageVersion: versionOf(join(workspaceRoot, packageDirectory)),
        entryPoints: Object.values(bundled.packageJson.exports).map(({ types }) => join(directory, types)),
      });
    } finally {
      rmSync(directory, { force: true, recursive: true });
    }
  };

const stripSignatureProse = ({ description: _description, parameters, ...signature }: ApiSignature): ApiSignature => ({
  ...signature,
  parameters: parameters.map(({ description: _description, ...parameter }) => parameter),
});

/** Keep factual API shape while excluding upstream prose from a redistributable corpus. */
const stripCorpusProse = (corpus: ApiCorpus): ApiCorpus => {
  const stripEntry = ({ docs: _docs, deprecated, signatures, members, ...entry }: ApiEntry): ApiEntry => ({
    ...entry,
    ...(deprecated === undefined ? {} : { deprecated: true }),
    ...(signatures === undefined
      ? {}
      : {
          signatures: signatures.map((signature) => stripSignatureProse(signature)),
        }),
    ...(members === undefined ? {} : { members: members.map((member) => stripEntry(member)) }),
  });
  return {
    ...corpus,
    entries: corpus.entries.map((entry) => stripEntry(entry)),
  };
};

/** Group label for a language whose only neutral axis is the kind of declaration. */
const byKind = (entry: ApiEntry): string => `${entry.kind.charAt(0).toUpperCase()}${entry.kind.slice(1)}s`;

/** OCCT's own namespacing: the prefix before the first underscore (R14). */
const byOcctPackage = (entry: ApiEntry): string => entry.name.split('_')[0] ?? 'other';

const byCategory = (entry: ApiEntry): string => entry.category ?? 'other';

/** One package that owns a bundle. @public */
export type BundleOwner = {
  readonly slug: string;
  /** Owning package directory, relative to the workspace root. */
  readonly packageDirectory: string;
  readonly name: string;
  readonly title: string;
  readonly description: string;
  readonly whenToUse: string;
  /** Absent for an authored-procedure bundle with no API behind it. */
  readonly corpus?: () => ApiCorpus;
  readonly groupBy?: (entry: ApiEntry) => string;
  /** Named groups materialize eagerly; every other group becomes cold. */
  readonly eagerGroups?: () => readonly string[];
};

/**
 * Every skill-owning package, and how its bundle is built.
 *
 * @public
 */
export const bundleOwners: readonly BundleOwner[] = [
  {
    slug: 'cad-replicad',
    packageDirectory: 'packages/plugins/replicad',
    name: 'Replicad authoring',
    title: 'Replicad authoring',
    description:
      'Guides precise Replicad BRep authoring in main.ts. Use when creating or editing TypeScript geometry imported from replicad.',
    whenToUse: 'Use when creating or editing TypeScript geometry imported from replicad.',
    corpus: typescriptCorpus('replicad', 'dist/replicad.d.ts'),
    groupBy: byKind,
  },
  {
    slug: 'cad-jscad',
    packageDirectory: 'packages/plugins/jscad',
    name: 'JSCAD authoring',
    title: 'JSCAD authoring',
    description:
      'Guides JSCAD modeling in main.ts with 2D-first CSG and deliberate tessellation. Use when creating or editing @jscad/modeling geometry.',
    whenToUse: 'Use when creating or editing @jscad/modeling geometry.',
    corpus: typescriptCorpus('@jscad/modeling', 'src/index.d.ts'),
    // Every top-level export is a namespace, which is the axis a JSCAD author
    // already navigates by (`primitives`, `booleans`, `transforms`).
    groupBy: (entry) => (entry.kind === 'namespace' ? entry.name : byKind(entry)),
  },
  {
    slug: 'cad-manifold',
    packageDirectory: 'packages/plugins/manifold',
    name: 'Manifold authoring',
    title: 'Manifold authoring',
    description:
      'Guides robust Manifold mesh CAD in main.ts. Use when creating or editing TypeScript geometry with manifold-3d/manifoldCAD.',
    whenToUse: 'Use when creating or editing TypeScript geometry with manifold-3d/manifoldCAD.',
    corpus: typescriptCorpus('manifold-3d', 'manifold.d.ts'),
    groupBy: byKind,
  },
  {
    slug: 'cad-opencascadejs',
    packageDirectory: 'packages/plugins/opencascade',
    name: 'OpenCascade.js authoring',
    title: 'OpenCascade.js authoring',
    description:
      'Guides direct OpenCascade.js BRep authoring in main.ts. Use when creating or editing libcascade geometry.',
    whenToUse: 'Use when creating or editing libcascade geometry.',
    // The committed module tree, not `node_modules`: the surface is the shipped
    // artifact, so the bundle regenerates identically without the kernel installed.
    corpus: () =>
      stripCorpusProse(
        typescriptCorpus('libcascade', 'index.d.ts', join(generatedRoot, 'opencascade/modules/libcascade'))(),
      ),
    groupBy: byOcctPackage,
    eagerGroups: () =>
      readJson<{ readonly eager: readonly string[] }>(join(generatedRoot, 'opencascade/opencascade.shards.json')).eager,
  },
  {
    slug: 'cad-build123d',
    packageDirectory: 'packages/plugins/build123d',
    name: 'Build123d authoring',
    title: 'Build123d authoring',
    description:
      'Guides native Build123d BRep authoring in main.py. Use when creating or editing trusted Python CAD projects in Tau Desktop.',
    whenToUse: 'Use when creating or editing trusted Python CAD projects in Tau Desktop.',
    corpus: committedCorpus('build123d/build123d.bundled.json'),
    groupBy: byCategory,
  },
  {
    slug: 'cad-picogk',
    packageDirectory: 'packages/plugins/picogk',
    name: 'PicoGK C# authoring',
    title: 'PicoGK C# authoring',
    description:
      'Guides trusted, upstream-compatible PicoGK C# voxel authoring in main.cs. Use when creating or editing PicoGK projects in Tau Desktop.',
    whenToUse: 'Use when creating or editing PicoGK projects in Tau Desktop.',
    corpus: committedCorpus('picogk/picogk.corpus.json'),
    // C# namespaces: `PicoGK`, `PicoGK.Shapes`, `System.Numerics`.
    groupBy: (entry) => entry.path ?? 'other',
  },
  {
    slug: 'cad-openscad',
    packageDirectory: 'packages/plugins/openrscad',
    name: 'OpenSCAD authoring',
    title: 'OpenSCAD authoring',
    description:
      'Guides OpenSCAD model authoring in main.scad with idiomatic CSG and adaptive tessellation. Use when creating or editing .scad geometry.',
    whenToUse: 'Use when creating or editing .scad geometry.',
    corpus: () => loadOpenscadCorpus(),
    groupBy: byCategory,
  },
  {
    slug: 'cad-zoo',
    packageDirectory: 'packages/plugins/zoo',
    name: 'Zoo KCL authoring',
    title: 'Zoo KCL authoring',
    description:
      'Guides Zoo KCL modeling in main.kcl with pipe-based analytical geometry. Use when creating or editing KCL models.',
    whenToUse: 'Use when creating or editing KCL models.',
    // The extraction timestamp never reaches a rendered file, so the default is safe.
    corpus: () => loadKclCorpus(),
    groupBy: byCategory,
  },
  {
    slug: 'geospec-authoring',
    packageDirectory: 'packages/geospec',
    name: 'GeoSpec authoring',
    title: 'GeoSpec authoring',
    description:
      'Guides deterministic GeoSpec test authoring and repair. Use before creating or editing *.geospec.ts or *.geospec.js files.',
    whenToUse: 'Use before creating or editing *.geospec.ts or *.geospec.js files.',
    corpus: bundledTypescriptCorpus('geospec/geospec.bundled.json', 'geospec', 'packages/geospec'),
    groupBy: byKind,
  },
];

/** What one owner's regeneration produced. @public */
export type GeneratedOwner = {
  readonly slug: string;
  readonly packageDirectory: string;
  readonly bundle: WrittenBundle;
};

/**
 * Regenerate every owner's bundle and its `agent/skills.json`.
 *
 * Authored doctrine is always read from the workspace, which is its only source
 * of truth; only the generated output is redirected, so the regeneration gate
 * can write into operating-system temporary storage and diff.
 *
 * @param options - `outputRoot` replaces the workspace root for writes only.
 * @returns One record per owner, in table order.
 * @public
 */
export const generateBundles = async (
  options: { readonly outputRoot?: string } = {},
): Promise<readonly GeneratedOwner[]> => {
  const outputRoot = options.outputRoot ?? workspaceRoot;
  const generated: GeneratedOwner[] = [];

  for (const owner of bundleOwners) {
    const sourceAgent = join(workspaceRoot, owner.packageDirectory, 'agent');
    const outputAgent = join(outputRoot, owner.packageDirectory, 'agent');
    const shared = {
      slug: owner.slug,
      name: owner.name,
      title: owner.title,
      description: owner.description,
      version: versionOf(join(workspaceRoot, owner.packageDirectory)),
      whenToUse: owner.whenToUse,
      // oxlint-disable-next-line no-await-in-loop -- Sequential by design: one owner compiles 12 MB of declarations, so overlapping the nine would multiply peak memory for no wall-clock gain.
      doctrine: await readDoctrine(join(sourceAgent, doctrineFile)),
    };

    const bundle =
      owner.corpus === undefined || owner.groupBy === undefined
        ? // oxlint-disable-next-line no-await-in-loop -- See above.
          await writeDoctrineBundle(join(outputAgent, owner.slug), shared)
        : // oxlint-disable-next-line no-await-in-loop -- See above.
          await writeCorpusBundle(owner.corpus(), join(outputAgent, owner.slug), {
            ...shared,
            groupBy: owner.groupBy,
            ...(owner.eagerGroups === undefined ? {} : { eagerGroups: owner.eagerGroups() }),
          });

    const manifest: TauSkillsManifest = { bundles: [bundle.declaration] };
    // oxlint-disable-next-line no-await-in-loop -- See above.
    await writeFile(join(outputAgent, skillsManifestFile), `${JSON.stringify(manifest, undefined, 2)}\n`, 'utf8');
    // oxlint-disable-next-line no-await-in-loop -- The module describes files written by this owner iteration.
    const resourcesModule = await renderResourcesModule(outputAgent, bundle.declaration);
    // oxlint-disable-next-line no-await-in-loop -- See above.
    await writeFile(join(outputAgent, resourcesModuleFile), resourcesModule, 'utf8');
    // oxlint-disable-next-line no-await-in-loop -- The declaration ships beside that generated module.
    await writeFile(join(outputAgent, resourcesTypesFile), resourcesTypes, 'utf8');

    generated.push({
      slug: owner.slug,
      packageDirectory: owner.packageDirectory,
      bundle,
    });
  }

  return generated;
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const generated = await generateBundles();
  for (const owner of generated) {
    console.log(
      `${owner.slug}: ${String(owner.bundle.shardCount)} shards, ${String(owner.bundle.bodyTokens)} body tokens, ${String(owner.bundle.bytes)} bytes -> ${owner.packageDirectory}/agent`,
    );
  }
}
