/**
 * Scans the example fixture directories and generates:
 *   - src/manifest.json  — machine-readable manifest of all examples
 *   - src/manifest.ts    — TypeScript types derived from the manifest
 *
 * Run via:  pnpm nx generate-manifest tau-examples
 */

import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(rootDir, 'src');
const kernelsDir = join(srcDir, 'kernels');

type ManifestEntry = {
  kernel: string;
  name: string;
  mainFile: string;
  files: string[];
};

function scanFixtures(): ManifestEntry[] {
  const entries: ManifestEntry[] = [];

  for (const kernelEntry of readdirSync(kernelsDir, { withFileTypes: true })) {
    if (!kernelEntry.isDirectory()) {
      continue;
    }

    const kernelDir = join(kernelsDir, kernelEntry.name);

    for (const exampleEntry of readdirSync(kernelDir, { withFileTypes: true })) {
      if (!exampleEntry.isDirectory()) {
        continue;
      }

      const exampleDir = join(kernelDir, exampleEntry.name);
      const files = readdirSync(exampleDir)
        .filter((f) => !f.startsWith('.'))
        .sort();

      if (files.length === 0) {
        continue;
      }

      entries.push({
        kernel: kernelEntry.name,
        name: exampleEntry.name,
        mainFile: 'main.ts',
        files,
      });
    }
  }

  return entries.sort((a, b) => a.kernel.localeCompare(b.kernel) || a.name.localeCompare(b.name));
}

const isValidIdentifier = (name: string): boolean => /^[a-zA-Z_$][\w$]*$/.test(name);

const formatKey = (name: string): string => (isValidIdentifier(name) ? name : `'${name}'`);

function generateManifestJson(entries: ManifestEntry[]): string {
  return JSON.stringify(entries, null, 2) + '\n';
}

function generateManifestTs(entries: ManifestEntry[]): string {
  const byKernel = new Map<string, string[]>();
  for (const entry of entries) {
    const list = byKernel.get(entry.kernel) ?? [];
    list.push(entry.name);
    byKernel.set(entry.kernel, list);
  }

  const lines: string[] = [
    '/* eslint-disable prettier/prettier -- Auto-generated code. */',
    '// AUTO-GENERATED by scripts/generate-manifest.ts — DO NOT EDIT.',
    '// Run `pnpm nx generate-manifest tau-examples` to regenerate.',
    '',
    '/** Map of kernel names to their available example fixture names. */',
    'export type ExampleManifest = {',
  ];

  for (const [kernel, examples] of [...byKernel.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const names = examples
      .sort()
      .map((n) => `'${n}'`)
      .join(' | ');
    lines.push(`  ${formatKey(kernel)}: ${names};`);
  }

  lines.push(
    '};',
    '',
    '/** Available kernel names. */',
    'export type KernelName = keyof ExampleManifest;',
    '',
    '/** Available example names for a given kernel. */',
    'export type ExampleName<K extends KernelName> = ExampleManifest[K];',
    '',
  );

  return lines.join('\n');
}

const entries = scanFixtures();

writeFileSync(join(srcDir, 'manifest.json'), generateManifestJson(entries));
writeFileSync(join(srcDir, 'manifest.ts'), generateManifestTs(entries));

const kernelCount = new Set(entries.map((entry) => entry.kernel)).size;
console.log(`Generated manifest: ${entries.length} examples across ${kernelCount} kernels`);
