/**
 * Generates stable WebP thumbnails for every manifest entry supported
 * by the composed repository runtime, plus a bundler-visible static asset map.
 *
 * Usage:
 *   pnpm nx generate-thumbnails tau-examples
 *   pnpm nx check-thumbnails tau-examples
 *   pnpm exec tsx libs/tau-examples/scripts/generate-thumbnails.mts --only=replicad/logo,replicad/tau-wordmark
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { createExampleRuntimeClient, exampleKernelIds } from '#scripts/runtime.js';
import { renderThumbnails } from '#scripts/render-thumbnail.js';

// Nx sets FORCE_COLOR while some shells set NO_COLOR; runtime workers would
// otherwise emit the same Node warning once for every plugin and example.
delete process.env['NO_COLOR'];

type ManifestEntry = {
  readonly kernel: string;
  readonly name: string;
  readonly mainFile?: string;
  readonly files: readonly string[];
  readonly featured?: true;
};

type RenderedThumbnail = {
  readonly entry: ManifestEntry & { readonly mainFile: string };
  readonly bytes: Uint8Array<ArrayBuffer>;
  readonly path: string;
};

const rootDirectory = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDirectory = join(rootDirectory, 'src');
const kernelsDirectory = join(sourceDirectory, 'kernels');
const manifestPath = join(sourceDirectory, 'manifest.json');
const assetMapPath = join(sourceDirectory, 'thumbnail.assets.ts');
const check = process.argv.includes('--check');
const only = new Set(
  process.argv
    .find((argument) => argument.startsWith('--only='))
    ?.slice('--only='.length)
    .split(',')
    .filter(Boolean) ?? [],
);
// Edge widths are output pixels. A featured card is drawn at twice a card's size, so its
// thumbnail halves the width to keep the same on-screen line weight.
const variants = [
  { file: 'thumbnail.webp', lineWidth: 6 },
  { file: 'thumbnail-featured.webp', lineWidth: 3 },
] as const;

const supportedKernels: ReadonlySet<string> = exampleKernelIds;
const engineIdForFixtureFamily = (kernel: string): string => (kernel === 'openscad' ? 'openrscad' : kernel);

const generateAssetMap = (entries: readonly ManifestEntry[]): string => {
  const lines = [
    '/* oxlint-disable prettier/prettier, eslint/no-restricted-imports -- Auto-generated Vite asset imports. */',
    '/* eslint-disable @typescript-eslint/naming-convention -- Generated keys are fixture paths. */',
    '// AUTO-GENERATED by scripts/generate-thumbnails.mts — DO NOT EDIT.',
    '// Run `pnpm nx generate-thumbnails tau-examples` to regenerate.',
    '',
  ];
  for (const [index, { kernel, name }] of entries.entries()) {
    lines.push(`import thumbnail${index} from './kernels/${kernel}/${name}/thumbnail.webp?url';`);
  }
  lines.push(
    '',
    '/** Static thumbnail URLs keyed by `<kernel>/<example>`. @public */',
    'export const thumbnailAssets = {',
  );
  for (const [index, { kernel, name }] of entries.entries()) {
    lines.push(`  '${kernel}/${name}': thumbnail${index},`);
  }
  lines.push(
    '} as const;',
    '',
    '/** Key of a generated example thumbnail asset. @public */',
    'export type ThumbnailAssetKey = keyof typeof thumbnailAssets;',
    '',
  );
  return lines.join('\n');
};

const bytesEqual = (left: Uint8Array<ArrayBuffer>, right: Uint8Array<ArrayBuffer>): boolean => {
  if (left.byteLength !== right.byteLength) {
    return false;
  }
  return left.every((byte, index) => byte === right[index]);
};

const decodeWebp = async (
  bytes: Uint8Array<ArrayBuffer>,
): Promise<{
  readonly width: number;
  readonly height: number;
  readonly pixels: Uint8Array<ArrayBuffer>;
}> => {
  const input = Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const { data, info } = await sharp(input).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  return {
    width: info.width,
    height: info.height,
    pixels: new Uint8Array(data),
  };
};

const imagesEquivalent = async (
  expected: Uint8Array<ArrayBuffer>,
  actual: Uint8Array<ArrayBuffer>,
): Promise<boolean> => {
  if (bytesEqual(expected, actual)) {
    return true;
  }

  const [left, right] = await Promise.all([decodeWebp(expected), decodeWebp(actual)]);
  if (left.width !== right.width || left.height !== right.height) {
    return false;
  }

  let changedPixels = 0;
  for (let offset = 0; offset < left.pixels.length; offset += 4) {
    let changed = false;
    for (let channel = 0; channel < 4; channel++) {
      const delta = Math.abs(left.pixels[offset + channel]! - right.pixels[offset + channel]!);
      if (delta > 3) {
        return false;
      }
      changed ||= delta > 0;
    }
    changedPixels += Number(changed);
  }

  // OCCT tessellation can vary triangle/line ordering between fresh processes,
  // moving a few raster boundary fragments by 1–3/255 on the same GPU. Keep the
  // golden strict enough that a shifted edge, material change, or rotation fails.
  return changedPixels <= left.width * left.height * 0.001;
};

const entries = JSON.parse(readFileSync(manifestPath, 'utf8')) as ManifestEntry[];
const allRenderable = entries.filter(
  (entry): entry is ManifestEntry & { readonly mainFile: string } =>
    entry.mainFile !== undefined && supportedKernels.has(engineIdForFixtureFamily(entry.kernel)),
);
const renderable =
  only.size === 0 ? allRenderable : allRenderable.filter((entry) => only.has(`${entry.kernel}/${entry.name}`));
const missing = [...only].filter((key) => !renderable.some((entry) => `${entry.kernel}/${entry.name}` === key));
if (missing.length > 0) {
  throw new Error(`Unknown or unsupported examples: ${missing.join(', ')}`);
}
const skipped = entries.filter(
  (entry) => entry.mainFile === undefined || !supportedKernels.has(engineIdForFixtureFamily(entry.kernel)),
);
const isolated = process.argv.includes('--isolated');
for (const entry of isolated ? [] : skipped) {
  const reason = entry.mainFile ? `kernel ${entry.kernel} is not composed` : 'no supported main entrypoint';
  console.log(`Skipping ${entry.kernel}/${entry.name}: ${reason}`);
}
if (!isolated) {
  for (const entry of renderable) {
    // Native kernel allocations can outlive client.terminate(); reclaim them between examples.
    const key = `${entry.kernel}/${entry.name}`;
    const child = spawnSync(
      process.execPath,
      ['--import', 'tsx', fileURLToPath(import.meta.url), '--isolated', `--only=${key}`, ...(check ? ['--check'] : [])],
      { cwd: rootDirectory, stdio: 'inherit' },
    );
    if (child.error) {
      throw child.error;
    }
    if (child.status !== 0) {
      throw new Error(`Thumbnail generation failed for ${key}: ${child.signal ?? child.status}`);
    }
  }
}

const thumbnails: RenderedThumbnail[] = [];
for (const entry of isolated ? renderable : []) {
  // One fresh client (and kernel WASM instance) per fixture: OCCT's shell/offset
  // results depend on accumulated heap state, so a shared instance makes a
  // fixture's bytes depend on the 47 fixtures rendered before it. A clean
  // instance is bit-reproducible. See
  // docs/research/tau-examples-thumbnail-nondeterminism.md (costs ~1s/fixture).
  // PicoGK's sandbox mirrors files beside the entry; C# File.ReadAllText uses that root.
  const picogkRoot = entry.kernel === 'picogk' ? join(kernelsDirectory, entry.kernel, entry.name) : undefined;
  // oxlint-disable-next-line eslint/no-await-in-loop -- Serial by design; see above.
  const client = await createExampleRuntimeClient(picogkRoot ?? kernelsDirectory);
  client.on('log', (logEntry) => {
    if (logEntry.level === 'error' || logEntry.level === 'warn') {
      console.warn(`[runtime:${logEntry.level}] ${logEntry.message}`);
    }
  });
  try {
    const key = `${entry.kernel}/${entry.name}`;
    const selected = entry.featured ? variants : variants.slice(0, 1);
    console.log(`Rendering ${key}`);
    // oxlint-disable-next-line eslint/no-await-in-loop -- One shared runtime/GPU queue renders fixtures serially.
    const images = await renderThumbnails(client, {
      label: key,
      sourcePath: picogkRoot ? entry.mainFile : `${key}/${entry.mainFile}`,
      lineWidths: selected.map(({ lineWidth }) => lineWidth),
      isExactLane: entry.kernel === 'picovoxel',
    });
    for (const [index, { file }] of selected.entries()) {
      thumbnails.push({ entry, bytes: images[index]!, path: join(kernelsDirectory, entry.kernel, entry.name, file) });
    }
  } finally {
    // oxlint-disable-next-line no-await-in-loop -- Each fixture owns one fresh kernel instance.
    await client.shutdown();
  }
}

// The asset map follows manifest rows with an actual thumbnail, independent of
// which native runtimes are composed for this invocation. A selected run can
// therefore add a new fixture without re-rendering unrelated kernels.
const assetMap = isolated
  ? undefined
  : generateAssetMap(
      entries.filter(
        (entry) =>
          entry.mainFile !== undefined &&
          existsSync(join(kernelsDirectory, entry.kernel, entry.name, 'thumbnail.webp')),
      ),
    );
if (check) {
  const drift: string[] = [];
  for (const thumbnail of thumbnails) {
    if (!existsSync(thumbnail.path)) {
      drift.push(`${thumbnail.entry.kernel}/${thumbnail.entry.name}: missing ${basename(thumbnail.path)}`);
      continue;
    }
    const existing = new Uint8Array(readFileSync(thumbnail.path));
    // oxlint-disable-next-line eslint/no-await-in-loop -- Compare serially with the corresponding generated fixture.
    if (!(await imagesEquivalent(existing, thumbnail.bytes))) {
      drift.push(`${thumbnail.entry.kernel}/${thumbnail.entry.name}: ${basename(thumbnail.path)} pixels differ`);
    }
  }
  if (assetMap !== undefined && (!existsSync(assetMapPath) || readFileSync(assetMapPath, 'utf8') !== assetMap)) {
    drift.push('thumbnail.assets.ts differs');
  }
  if (drift.length > 0) {
    throw new Error(`Generated thumbnail drift:\n${drift.map((item) => `- ${item}`).join('\n')}`);
  }
  console.log(`Verified ${renderable.length} thumbnails`);
} else {
  for (const thumbnail of thumbnails) {
    writeFileSync(thumbnail.path, thumbnail.bytes);
  }
  if (assetMap !== undefined) {
    writeFileSync(assetMapPath, assetMap);
  }
  console.log(`Generated ${renderable.length} thumbnails${assetMap ? ' and thumbnail.assets.ts' : ''}`);
}
