/**
 * Scans the example fixture directories and generates:
 *   - src/manifest.json  — machine-readable manifest of all examples
 *   - src/manifest.ts    — TypeScript types derived from the manifest
 *
 * Run via:  pnpm nx generate-manifest tau-examples
 */

import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDirectory = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDirectory = join(rootDirectory, 'src');
const kernelsDirectory = join(sourceDirectory, 'kernels');

type ManifestEntry = {
  kernel: string;
  name: string;
  mainFile?: string;
  files: string[];
};

const candidateMainFiles = ['main.ts', 'main.py', 'main.scad', 'main.cpp'] as const;
const excludedDirectories = new Set(['.tau', '__pycache__']);
const excludedFiles = new Set(['thumbnail.webp']);

function scanFiles(directory: string, prefix = ''): string[] {
  const files: string[] = [];

  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || excludedDirectories.has(entry.name)) {
      continue;
    }

    const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
    const absolutePath = join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...scanFiles(absolutePath, relativePath));
      continue;
    }

    if (entry.isFile() && !excludedFiles.has(entry.name)) {
      files.push(relativePath);
    }
  }

  return files.sort();
}

function scanFixtures(): ManifestEntry[] {
  const entries: ManifestEntry[] = [];

  for (const kernelEntry of readdirSync(kernelsDirectory, { withFileTypes: true })) {
    if (!kernelEntry.isDirectory()) {
      continue;
    }

    const kernelDirectory = join(kernelsDirectory, kernelEntry.name);

    for (const exampleEntry of readdirSync(kernelDirectory, {
      withFileTypes: true,
    })) {
      if (!exampleEntry.isDirectory()) {
        continue;
      }

      const exampleDirectory = join(kernelDirectory, exampleEntry.name);
      const files = scanFiles(exampleDirectory);

      if (files.length === 0) {
        continue;
      }

      const mainFile = candidateMainFiles.find((candidate) => files.includes(candidate));
      entries.push({
        kernel: kernelEntry.name,
        name: exampleEntry.name,
        ...(mainFile ? { mainFile } : {}),
        files,
      });
    }
  }

  return entries.sort((a, b) => a.kernel.localeCompare(b.kernel) || a.name.localeCompare(b.name));
}

const isValidIdentifier = (name: string): boolean => /^[$A-Z_a-z][\w$]*$/.test(name);

const formatKey = (name: string): string => (isValidIdentifier(name) ? name : `'${name}'`);

function generateManifestJson(entries: ManifestEntry[]): string {
  return JSON.stringify(entries, null, 2) + '\n';
}

function generateManifestTs(entries: ManifestEntry[]): string {
  const byKernel = new Map<string, string[]>();
  for (const entry of entries) {
    const list = byKernel.get(entry.kernel) ?? [];
    list.push(entry.name);
    byKernel.set(entry.kernel, list);
  }

  const lines: string[] = [
    '/* oxlint-disable prettier/prettier -- Auto-generated code. */',
    '// AUTO-GENERATED by scripts/generate-manifest.ts — DO NOT EDIT.',
    '// Run `pnpm nx generate-manifest tau-examples` to regenerate.',
    '',
    '/** Map of kernel names to their available example fixture names. */',
    'export type ExampleManifest = {',
  ];

  for (const [kernel, examples] of [...byKernel.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const names = examples
      .sort()
      .map((n) => `'${n}'`)
      .join(' | ');
    lines.push(`  ${formatKey(kernel)}: ${names};`);
  }

  lines.push(
    '};',
    '',
    '/** Available kernel names. */',
    'export type KernelName = keyof ExampleManifest;',
    '',
    '/** Available example names for a given kernel. */',
    'export type ExampleName<K extends KernelName> = ExampleManifest[K];',
    '',
  );

  return lines.join('\n');
}

const entries = scanFixtures();

writeFileSync(join(sourceDirectory, 'manifest.json'), generateManifestJson(entries));
writeFileSync(join(sourceDirectory, 'manifest.ts'), generateManifestTs(entries));

const kernelCount = new Set(entries.map((entry) => entry.kernel)).size;
console.log(`Generated manifest: ${entries.length} examples across ${kernelCount} kernels`);
