/**
 * Generates stable WebP thumbnails for every manifest entry supported
 * by the composed repository runtime, plus a bundler-visible static asset map.
 *
 * Usage:
 *   pnpm nx generate-thumbnails tau-examples
 *   pnpm nx check-thumbnails tau-examples
 *   pnpm exec tsx libs/tau-examples/scripts/generate-thumbnails.mts --only=replicad/logo,replicad/tau-wordmark
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createNodeClient } from '@taucad/runtime/node';
import sharp from 'sharp';
import { exampleKernelIds, exampleRuntime } from '#scripts/runtime.js';

type ManifestEntry = {
  readonly kernel: string;
  readonly name: string;
  readonly mainFile?: string;
  readonly files: readonly string[];
};

type RenderedThumbnail = {
  readonly entry: ManifestEntry & { readonly mainFile: string };
  readonly bytes: Uint8Array<ArrayBuffer>;
  readonly path: string;
};

const rootDirectory = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDirectory = join(rootDirectory, 'src');
const kernelsDirectory = join(sourceDirectory, 'kernels');
const manifestPath = join(sourceDirectory, 'manifest.json');
const assetMapPath = join(sourceDirectory, 'thumbnail.assets.ts');
const check = process.argv.includes('--check');
const only = new Set(
  process.argv
    .find((argument) => argument.startsWith('--only='))
    ?.slice('--only='.length)
    .split(',')
    .filter(Boolean) ?? [],
);
const thumbnailOptions = { width: 768, height: 576 } as const;
const thumbnailMargin = 0.1;

const runtime = exampleRuntime;
const supportedKernels: ReadonlySet<string> = exampleKernelIds;
const engineIdForFixtureFamily = (kernel: string): string => (kernel === 'openscad' ? 'openrscad' : kernel);

const generateAssetMap = (thumbnails: readonly RenderedThumbnail[]): string => {
  const lines = [
    '/* oxlint-disable prettier/prettier, eslint/no-restricted-imports -- Auto-generated Vite asset imports. */',
    '/* eslint-disable @typescript-eslint/naming-convention -- Generated keys are fixture paths. */',
    '// AUTO-GENERATED by scripts/generate-thumbnails.mts — DO NOT EDIT.',
    '// Run `pnpm nx generate-thumbnails tau-examples` to regenerate.',
    '',
  ];
  for (const [index, thumbnail] of thumbnails.entries()) {
    const { kernel, name } = thumbnail.entry;
    lines.push(`import thumbnail${index} from './kernels/${kernel}/${name}/thumbnail.webp?url';`);
  }
  lines.push(
    '',
    '/** Static thumbnail URLs keyed by `<kernel>/<example>`. @public */',
    'export const thumbnailAssets = {',
  );
  for (const [index, thumbnail] of thumbnails.entries()) {
    lines.push(`  '${thumbnail.entry.kernel}/${thumbnail.entry.name}': thumbnail${index},`);
  }
  lines.push(
    '} as const;',
    '',
    '/** Key of a generated example thumbnail asset. @public */',
    'export type ThumbnailAssetKey = keyof typeof thumbnailAssets;',
    '',
  );
  return lines.join('\n');
};

const bytesEqual = (left: Uint8Array<ArrayBuffer>, right: Uint8Array<ArrayBuffer>): boolean => {
  if (left.byteLength !== right.byteLength) {
    return false;
  }
  return left.every((byte, index) => byte === right[index]);
};

const isWebp = (bytes: Uint8Array<ArrayBuffer>): boolean =>
  bytes.byteLength >= 12 &&
  new TextDecoder().decode(bytes.subarray(0, 4)) === 'RIFF' &&
  new TextDecoder().decode(bytes.subarray(8, 12)) === 'WEBP';

const decodeWebp = async (
  bytes: Uint8Array<ArrayBuffer>,
): Promise<{ readonly width: number; readonly height: number; readonly pixels: Uint8Array<ArrayBuffer> }> => {
  const input = Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const { data, info } = await sharp(input).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  return { width: info.width, height: info.height, pixels: new Uint8Array(data) };
};

const imagesEquivalent = async (
  expected: Uint8Array<ArrayBuffer>,
  actual: Uint8Array<ArrayBuffer>,
): Promise<boolean> => {
  if (bytesEqual(expected, actual)) {
    return true;
  }

  const [left, right] = await Promise.all([decodeWebp(expected), decodeWebp(actual)]);
  if (left.width !== right.width || left.height !== right.height) {
    return false;
  }

  let changedPixels = 0;
  for (let offset = 0; offset < left.pixels.length; offset += 4) {
    let changed = false;
    for (let channel = 0; channel < 4; channel++) {
      const delta = Math.abs(left.pixels[offset + channel]! - right.pixels[offset + channel]!);
      if (delta > 3) {
        return false;
      }
      changed ||= delta > 0;
    }
    changedPixels += Number(changed);
  }

  // OCCT tessellation can vary triangle/line ordering between fresh processes,
  // moving a few raster boundary fragments by 1–3/255 on the same GPU. Keep the
  // golden strict enough that a shifted edge, material change, or rotation fails.
  return changedPixels <= left.width * left.height * 0.001;
};

const renderSvgThumbnail = async (svg: string): Promise<Uint8Array<ArrayBuffer>> => {
  const { width, height } = thumbnailOptions;
  const foreground = await sharp(Buffer.from(svg))
    .resize({
      width: Math.round(width * (1 - 2 * thumbnailMargin)),
      height: Math.round(height * (1 - 2 * thumbnailMargin)),
      fit: 'contain',
    })
    .png()
    .toBuffer();
  const thumbnail = await sharp({
    create: { width, height, channels: 4, background: '#000' },
  })
    .composite([{ input: foreground, gravity: 'center' }])
    .webp()
    .toBuffer();
  return new Uint8Array(thumbnail);
};

const entries = JSON.parse(readFileSync(manifestPath, 'utf8')) as ManifestEntry[];
const allRenderable = entries.filter(
  (entry): entry is ManifestEntry & { readonly mainFile: string } =>
    entry.mainFile !== undefined && supportedKernels.has(engineIdForFixtureFamily(entry.kernel)),
);
const renderable =
  only.size === 0 ? allRenderable : allRenderable.filter((entry) => only.has(`${entry.kernel}/${entry.name}`));
const missing = [...only].filter((key) => !renderable.some((entry) => `${entry.kernel}/${entry.name}` === key));
if (missing.length > 0) {
  throw new Error(`Unknown or unsupported examples: ${missing.join(', ')}`);
}
const skipped = entries.filter(
  (entry) => entry.mainFile === undefined || !supportedKernels.has(engineIdForFixtureFamily(entry.kernel)),
);
for (const entry of skipped) {
  const reason = entry.mainFile ? `kernel ${entry.kernel} is not composed` : 'no supported main entrypoint';
  console.log(`Skipping ${entry.kernel}/${entry.name}: ${reason}`);
}

const thumbnails: RenderedThumbnail[] = [];
for (const entry of renderable) {
  // One fresh client (and kernel WASM instance) per fixture: OCCT's shell/offset
  // results depend on accumulated heap state, so a shared instance makes a
  // fixture's bytes depend on the 47 fixtures rendered before it. A clean
  // instance is bit-reproducible. See
  // docs/research/tau-examples-thumbnail-nondeterminism.md (costs ~1s/fixture).
  // oxlint-disable-next-line eslint/no-await-in-loop -- Serial by design; see above.
  const client = await createNodeClient(kernelsDirectory, { runtime });
  client.on('log', (logEntry) => {
    if (logEntry.level === 'error' || logEntry.level === 'warn') {
      console.warn(`[runtime:${logEntry.level}] ${logEntry.message}`);
    }
  });
  try {
    const sourcePath = `${entry.kernel}/${entry.name}/${entry.mainFile}`;
    console.log(`Rendering ${entry.kernel}/${entry.name}`);
    // oxlint-disable-next-line eslint/no-await-in-loop -- One shared runtime/GPU queue renders fixtures serially.
    const outcome = await client.render({
      source: { path: sourcePath },
      content: { includeEdges: true },
    });
    if (outcome.superseded) {
      throw new Error(`Thumbnail render failed for ${entry.kernel}/${entry.name}: render was superseded`);
    }
    if (outcome.geometry.success && outcome.geometry.data.format === 'svg') {
      // oxlint-disable-next-line eslint/no-await-in-loop -- Preserve manifest order and the shared render queue.
      const bytes = await renderSvgThumbnail(outcome.geometry.data.content);
      thumbnails.push({
        entry,
        bytes,
        path: join(kernelsDirectory, entry.kernel, entry.name, 'thumbnail.webp'),
      });
      continue;
    }
    // oxlint-disable-next-line eslint/no-await-in-loop -- Re-export the settled 3D render through the image transcoder.
    const result = await client.export('webp', {
      ...(!outcome.geometry.success && { source: { path: sourcePath } }),
      content: { includeEdges: true },
      exportOptions: {
        mode: 'single',
        ...thumbnailOptions,
        lineWidth: 3,
        camera: {
          framing: 'bounds',
          direction: [0.612_372_435_7, -0.612_372_435_7, 0.5],
          up: [0, 0, 1],
          margin: thumbnailMargin,
          projection: { kind: 'perspective', verticalFieldOfView: 45 },
        },
        quality: 0.9,
      },
    });
    if (!result.success) {
      throw new Error(
        `Thumbnail export failed for ${entry.kernel}/${entry.name}: ${result.issues
          .map((issue) => issue.message)
          .join('; ')}`,
      );
    }
    const thumbnail = result.data[0];
    if (result.data.length !== 1 || thumbnail?.mimeType !== 'image/webp' || !isWebp(thumbnail.bytes)) {
      throw new Error(
        `Thumbnail export expected exactly one valid image/webp artifact, received: ${result.data.map((file) => `${file.mimeType} (${file.bytes.length} bytes)`).join(', ')}`,
      );
    }
    thumbnails.push({
      entry,
      bytes: thumbnail.bytes,
      path: join(kernelsDirectory, entry.kernel, entry.name, 'thumbnail.webp'),
    });
  } finally {
    client.terminate();
  }
}

const assetMap = only.size === 0 ? generateAssetMap(thumbnails) : undefined;
if (check) {
  const drift: string[] = [];
  for (const thumbnail of thumbnails) {
    if (!existsSync(thumbnail.path)) {
      drift.push(`${thumbnail.entry.kernel}/${thumbnail.entry.name}: missing thumbnail.webp`);
      continue;
    }
    const existing = new Uint8Array(readFileSync(thumbnail.path));
    // oxlint-disable-next-line eslint/no-await-in-loop -- Compare serially with the corresponding generated fixture.
    if (!(await imagesEquivalent(existing, thumbnail.bytes))) {
      drift.push(`${thumbnail.entry.kernel}/${thumbnail.entry.name}: thumbnail pixels differ`);
    }
  }
  if (assetMap !== undefined && (!existsSync(assetMapPath) || readFileSync(assetMapPath, 'utf8') !== assetMap)) {
    drift.push('thumbnail.assets.ts differs');
  }
  if (drift.length > 0) {
    throw new Error(`Generated thumbnail drift:\n${drift.map((item) => `- ${item}`).join('\n')}`);
  }
  console.log(`Verified ${thumbnails.length} thumbnails`);
} else {
  for (const thumbnail of thumbnails) {
    writeFileSync(thumbnail.path, thumbnail.bytes);
  }
  if (assetMap !== undefined) {
    writeFileSync(assetMapPath, assetMap);
  }
  console.log(`Generated ${thumbnails.length} thumbnails${assetMap ? ' and thumbnail.assets.ts' : ''}`);
}
