// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "module": 2,
  "teeth": 24,
  "width": 12,
  "bore": 10
};
export const parameterDomains = {
  "module": {
    "min": 1.5,
    "max": 2.5
  },
  "teeth": {
    "min": 20,
    "max": 32,
    "integer": true,
    "values": [
      20,
      24,
      32
    ]
  },
  "width": {
    "min": 8,
    "max": 16
  },
  "bore": {
    "min": 8,
    "max": 12
  }
};
export const design = "helical-gear";
export const parameterCases = [
  {
    "name": "module 1.5",
    "parameters": {
      "module": 1.5
    },
    "expectations": {
      "bounds": {
        "x": 39,
        "y": 39,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 9539.789704321893,
        "max": 12712.70010967716
      },
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "module 2.5",
    "parameters": {
      "module": 2.5
    },
    "expectations": {
      "bounds": {
        "x": 65,
        "y": 65,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 28174.931927253154,
        "max": 36988.571942128896
      },
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "teeth 20",
    "parameters": {
      "teeth": 20
    },
    "expectations": {
      "bounds": {
        "x": 44,
        "y": 44,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 11608.027775381606,
        "max": 16298.739766456525
      },
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "teeth 24",
    "parameters": {
      "teeth": 24
    },
    "expectations": {
      "bounds": {
        "x": 52,
        "y": 52,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 17692.664426854317,
        "max": 23333.39403637479
      },
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "teeth 32",
    "parameters": {
      "teeth": 32
    },
    "expectations": {
      "bounds": {
        "x": 68,
        "y": 68,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 33481.052466735186,
        "max": 41021.81731314676
      },
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "width 8",
    "parameters": {
      "width": 8
    },
    "expectations": {
      "bounds": {
        "x": 52,
        "y": 52,
        "z": 8
      },
      "solids": 1,
      "volume": {
        "min": 11795.10961790288,
        "max": 15555.596024249862
      },
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "width 16",
    "parameters": {
      "width": 16
    },
    "expectations": {
      "bounds": {
        "x": 52,
        "y": 52,
        "z": 16
      },
      "solids": 1,
      "volume": {
        "min": 23590.21923580576,
        "max": 31111.192048499724
      },
      "holes": [
        {
          "diameter": 10,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore 8",
    "parameters": {
      "bore": 8
    },
    "expectations": {
      "bounds": {
        "x": 52,
        "y": 52,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 18031.956433442014,
        "max": 23672.686042962487
      },
      "holes": [
        {
          "diameter": 8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "bore 12",
    "parameters": {
      "bore": 12
    },
    "expectations": {
      "bounds": {
        "x": 52,
        "y": 52,
        "z": 12
      },
      "solids": 1,
      "volume": {
        "min": 17277.974196580464,
        "max": 22918.703806100937
      },
      "holes": [
        {
          "diameter": 12,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "module": 1.5,
      "teeth": 20,
      "width": 8,
      "bore": 8
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 33,
        "z": 8
      },
      "solids": 1,
      "volume": {
        "min": 4304.31572963746,
        "max": 6063.332726290555
      },
      "holes": [
        {
          "diameter": 8,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "module": 2.5,
      "teeth": 32,
      "width": 16,
      "bore": 12
    },
    "expectations": {
      "bounds": {
        "x": 85,
        "y": 85,
        "z": 16
      },
      "solids": 1,
      "volume": {
        "min": 69906.13067905753,
        "max": 85616.057442415
      },
      "holes": [
        {
          "diameter": 12,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "module": 1.5,
      "teeth": 20,
      "width": 8,
      "bore": 12
    },
    "expectations": {
      "bounds": {
        "x": 33,
        "y": 33,
        "z": 8
      },
      "solids": 1,
      "volume": {
        "min": 3801.660905063093,
        "max": 5560.677901716188
      },
      "holes": [
        {
          "diameter": 12,
          "center": {
            "x": 0,
            "y": 0
          },
          "axis": "z"
        }
      ]
    }
  }
];
