export const defaultParams = {
  tabletSize: 20,
  tabletHeight: 2,
  cornerRadius: 4,
  edgeFilletRadius: 0.35,
  holeRadius: 2,
  holeCenterX: -6,
  holeCenterY: -6,
  holeFilletRadius: 0.3,
  logoSize: 16,
  logoCenterY: 0,
  logoHeight: 0.8,
  logoChamferSize: 0.1,
  tabletColor: '#000000',
  logoColor: '#00987c',
  backText: 'tau.new',
  backTextFontSize: 7,
  backTextLineGap: -1,
  backTextCenterX: 1.5,
  backTextCenterY: 2.5,
  backTextHeight: 0.4,
  backTextColor: '#ffffff',
};
