// Generated by warehouse:generate. Edit definitions, then regenerate.
/* oxlint-disable unicorn/numeric-separators-style -- JSON serialization preserves exact numerical oracle values. */
export const defaultParams = {
  "width": 80,
  "depth": 60,
  "height": 4,
  "hole": 5
};
export const parameterDomains = {
  "width": {
    "min": 72,
    "max": 88
  },
  "depth": {
    "min": 54,
    "max": 66
  },
  "height": {
    "min": 3.6,
    "max": 4.4
  },
  "hole": {
    "min": 4.5,
    "max": 5.5
  }
};
export const design = "perforated-plate";
export const parameterCases = [
  {
    "name": "width 72",
    "parameters": {
      "width": 72
    },
    "expectations": {
      "bounds": {
        "x": 72,
        "y": 60,
        "z": 4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": -23.400000000000002,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": -23.400000000000002,
            "y": 19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 23.400000000000002,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 23.400000000000002,
            "y": 19.5
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "width 88",
    "parameters": {
      "width": 88
    },
    "expectations": {
      "bounds": {
        "x": 88,
        "y": 60,
        "z": 4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": -28.6,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": -28.6,
            "y": 19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 28.6,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 28.6,
            "y": 19.5
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "depth 54",
    "parameters": {
      "depth": 54
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 54,
        "z": 4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": -17.55
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": 17.55
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": -17.55
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": 17.55
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "depth 66",
    "parameters": {
      "depth": 66
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 66,
        "z": 4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": -21.45
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": 21.45
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": -21.45
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": 21.45
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "height 3.6",
    "parameters": {
      "height": 3.6
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 60,
        "z": 3.6
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": 19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": 19.5
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "height 4.4",
    "parameters": {
      "height": 4.4
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 60,
        "z": 4.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": -26,
            "y": 19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5,
          "center": {
            "x": 26,
            "y": 19.5
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "hole 4.5",
    "parameters": {
      "hole": 4.5
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 60,
        "z": 4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 4.5,
          "center": {
            "x": -26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 4.5,
          "center": {
            "x": -26,
            "y": 19.5
          },
          "axis": "z"
        },
        {
          "diameter": 4.5,
          "center": {
            "x": 26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 4.5,
          "center": {
            "x": 26,
            "y": 19.5
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "hole 5.5",
    "parameters": {
      "hole": 5.5
    },
    "expectations": {
      "bounds": {
        "x": 80,
        "y": 60,
        "z": 4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5.5,
          "center": {
            "x": -26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": -26,
            "y": 19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": 26,
            "y": -19.5
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": 26,
            "y": 19.5
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined min",
    "parameters": {
      "width": 72,
      "depth": 54,
      "height": 3.6,
      "hole": 4.5
    },
    "expectations": {
      "bounds": {
        "x": 72,
        "y": 54,
        "z": 3.6
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 4.5,
          "center": {
            "x": -23.400000000000002,
            "y": -17.55
          },
          "axis": "z"
        },
        {
          "diameter": 4.5,
          "center": {
            "x": -23.400000000000002,
            "y": 17.55
          },
          "axis": "z"
        },
        {
          "diameter": 4.5,
          "center": {
            "x": 23.400000000000002,
            "y": -17.55
          },
          "axis": "z"
        },
        {
          "diameter": 4.5,
          "center": {
            "x": 23.400000000000002,
            "y": 17.55
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "combined max",
    "parameters": {
      "width": 88,
      "depth": 66,
      "height": 4.4,
      "hole": 5.5
    },
    "expectations": {
      "bounds": {
        "x": 88,
        "y": 66,
        "z": 4.4
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5.5,
          "center": {
            "x": -28.6,
            "y": -21.45
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": -28.6,
            "y": 21.45
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": 28.6,
            "y": -21.45
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": 28.6,
            "y": 21.45
          },
          "axis": "z"
        }
      ]
    }
  },
  {
    "name": "minimum envelope maximum openings",
    "parameters": {
      "width": 72,
      "depth": 54,
      "height": 3.6,
      "hole": 5.5
    },
    "expectations": {
      "bounds": {
        "x": 72,
        "y": 54,
        "z": 3.6
      },
      "solids": 1,
      "holes": [
        {
          "diameter": 5.5,
          "center": {
            "x": -23.400000000000002,
            "y": -17.55
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": -23.400000000000002,
            "y": 17.55
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": 23.400000000000002,
            "y": -17.55
          },
          "axis": "z"
        },
        {
          "diameter": 5.5,
          "center": {
            "x": 23.400000000000002,
            "y": 17.55
          },
          "axis": "z"
        }
      ]
    }
  }
];
